# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""Generate README.md from readme/README.md.j2 and the tested snippet files.

The README is generated, never hand-edited, so its code examples cannot drift
from working code: every Usage example lives in readme/snippets/ as a real
pytest test that runs against the built wheel (see scripts/test-wheel.sh
readme/snippets/), and this script splices the tested code into the prose.

Snippet extraction rule (deliberately simple, so what renders is exactly what
runs): a snippet is the block of lines strictly between the first
``# readme:begin`` and the next ``# readme:end`` marker in
readme/snippets/test_readme_<name>.py, with common leading indentation removed. The
two marker lines are dropped; nothing else is added, removed or reformatted.
Keep any assertions or fixtures a snippet should not show OUTSIDE the marked
region.

Output is deterministic (no timestamps), so the committed README.md is a pure
function of the template and the snippets; scripts/check_readme_regen.sh fails
CI if the committed file drifts from a fresh render.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

BEGIN_MARKER = "# readme:begin"
END_MARKER = "# readme:end"

CLIENT_DIRPATH = Path(__file__).resolve().parent.parent
README_DIRPATH = CLIENT_DIRPATH / "readme"
SNIPPETS_DIRPATH = README_DIRPATH / "snippets"
TEMPLATE_FILENAME = "README.md.j2"
OUTPUT_FILEPATH = CLIENT_DIRPATH / "README.md"

HEADER = (
    "<!-- Generated by scripts/generate_readme.py from readme/README.md.j2 and\n"
    "     the tested snippets in readme/snippets/. Do not edit this file directly:\n"
    "     edit the template or a snippet and run scripts/generate_readme.py.\n"
    "     See CONTRIBUTING.md. -->\n"
)


def extract_snippet(name: str) -> str:
    """Return the marked, dedented code region from snippets/test_readme_<name>.py.

    Snippet files carry a ``test_readme_`` prefix (not a bare ``test_``) so their
    basenames never collide with tests/ when pytest collects both together.
    """
    snippet_filepath = SNIPPETS_DIRPATH / f"test_readme_{name}.py"
    if not snippet_filepath.exists():
        raise FileNotFoundError(f"no snippet file for {name!r}: {snippet_filepath}")

    lines = snippet_filepath.read_text().splitlines()
    begin = end = None
    for index, line in enumerate(lines):
        if line.strip() == BEGIN_MARKER and begin is None:
            begin = index
        elif line.strip() == END_MARKER and begin is not None:
            end = index
            break
    if begin is None or end is None:
        raise ValueError(
            f"{snippet_filepath} must contain a {BEGIN_MARKER} ... {END_MARKER} region"
        )

    region = "\n".join(lines[begin + 1 : end])
    return textwrap.dedent(region).strip("\n")


def render() -> str:
    environment = Environment(
        loader=FileSystemLoader(str(README_DIRPATH)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        autoescape=False,
        trim_blocks=False,
        lstrip_blocks=False,
    )
    environment.globals["snippet"] = extract_snippet
    template = environment.get_template(TEMPLATE_FILENAME)
    body = template.render()
    if not body.endswith("\n"):
        body += "\n"
    return HEADER + body


def main(argv: list[str]) -> int:
    check_only = "--check" in argv[1:]
    rendered = render()
    if check_only:
        current = OUTPUT_FILEPATH.read_text() if OUTPUT_FILEPATH.exists() else ""
        if current != rendered:
            print(
                "README.md is out of date. Run scripts/generate_readme.py.",
                file=sys.stderr,
            )
            return 1
        print("README.md is up to date.")
        return 0
    OUTPUT_FILEPATH.write_text(rendered)
    print(f"Wrote {OUTPUT_FILEPATH.relative_to(CLIENT_DIRPATH)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
