// Copyright © 2026 Robert Smallshire <robert@smallshire.org.uk>
//
// This file is part of Beebium.
//
// Beebium is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version. Beebium is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with Beebium.
// If not, see <https://www.gnu.org/licenses/>.

#pragma once

#include "TubeHostBackend.hpp"
#include "TubeInspection.hpp"
#include "TubeCoprocessorBackend.hpp"

#include <algorithm>
#include <array>
#include <cstddef>
#include <cstdint>

namespace beebium {

// Tube ULA register model.
//
// Models the Acorn Tube ULA's four register sets, control flags, and
// interrupt outputs. This is the authoritative FIFO model used for both
// in-process testing and as the register bridge in the extension-based
// coprocessor architecture.
//
// All access is single-threaded. The host and coprocessor sides are driven
// from the same thread via interleaved clock ticking. Bus stretching is
// used to stall the host CPU when a register is full, deferring the
// write until the coprocessor has drained the register.
//
// The host and coprocessor sides see different views of the same registers:
// different status bits, different read/write targets. The caller selects
// the perspective by calling host_read/host_write or coprocessor_read/
// coprocessor_write.

class TubeUla : public TubeHostBackend, public TubeCoprocessorBackend, public TubeInspection {
public:
    // The status flag bits, control flag bits, TransferCounters and TraceEntry
    // types are inherited from TubeInspection, the single source of truth.

    TubeUla();

    // Full hardware reset (HRST) -- clears everything including control flags.
    void reset() override;

    // Host-side register access (offsets 0-7, mirrored from &FEE0-&FEE7).
    uint8_t host_read(uint8_t offset) override;
    uint8_t host_peek(uint8_t offset) const override;
    void host_write(uint8_t offset, uint8_t value) override;

    // Coprocessor-side register access (offsets 0-7, mirrored from &FEF8-&FEFF).
    uint8_t coprocessor_read(uint8_t offset) override;
    uint8_t coprocessor_peek(uint8_t offset) const override;
    void coprocessor_write(uint8_t offset, uint8_t value) override;

    // Interrupt outputs (active high in this model; caller inverts if needed).
    // These use the Tube-specific names from Application Note 004:
    //   hirq -- Host IRQ (active when Q=1 and R4 has P-to-H data)
    //   pirq -- Coprocessor IRQ (active when I=1 and R1 has data, or J=1 and R4 has data)
    //   pnmi -- Coprocessor NMI (edge-triggered from R3 activity when M=1)
    //   pnmi_level -- raw combinational PNMI output (for M6502 edge detection)
    // TubeSocket adapts hirq() to the generic IrqSource::irq_pending() interface.
    bool hirq() const override;
    bool pirq() const override;
    bool pnmi() const override;
    bool pnmi_level() const override;

    // Read control flags (bits 0-5: Q, I, J, M, V, P).
    uint8_t control_flags() const override {
        return control_flags_;
    }

    // The read-only diagnostic surface is this ULA itself.
    const TubeInspection* inspection() const override { return this; }

    // Test whether the coprocessor reset line is currently asserted.
    bool coprocessor_reset_active() const {
        return (control_flags_ & FLAG_P) != 0;
    }

    // Bus stretching: returns true while the host CPU should be stalled
    // waiting for a register to drain.
    bool stretched() const override { return host_stretched_; }

    // Attempt to complete a pending bus stretch operation.
    // Returns true if the stretch cleared (or was not active).
    bool try_complete_stretch() override;

    // Access the NMI edge detector state (coprocessor-local).
    bool prev_pnmi() const { return prev_pnmi_; }

    // Diagnostic accessors for current stretch state (write stretches only --
    // read stretches are not generated by this ULA model, matching hardware).
    uint8_t pending_offset() const { return pending_offset_; }

private:
    // Soft reset (T flag) -- clears all register data but preserves control flags.
    void soft_reset();

    // Recompute interrupt outputs (HIRQ, PIRQ, PNMI).
    void update_interrupts();

    // Control flag register (bits 0-5: Q, I, J, M, V, P).
    uint8_t control_flags_ = 0;

    // Data bus latches: the last byte each side drove into the ULA, whatever
    // the address. Reading an empty FIFO (R1 P-to-H, R3 either direction)
    // returns the opposite side's latch, as the hardware does.
    uint8_t host_bus_latch_ = 0;
    uint8_t coprocessor_bus_latch_ = 0;

    // Latch: 1-byte data with ready/full flags.
    // Used for R1 H-to-P, R2 both directions, R4 both directions.
    struct Latch {
        uint8_t data = 0;
        bool available = false;  // data waiting for consumer
        bool full = false;       // producer cannot write
    };

    // FIFO ring buffer (24 bytes, for R1 P-to-H).
    struct Fifo24 {
        std::array<uint8_t, 24> data{};
        uint8_t head = 0;   // consumer reads here
        uint8_t tail = 0;   // producer writes here
        uint8_t count = 0;
    };

    // 2-slot register (for R3, each direction).
    struct Reg3 {
        std::array<uint8_t, 2> data{};
        uint8_t head = 0;
        uint8_t tail = 0;
        uint8_t count = 0;
        bool pending = false;
    };

    // Register 1: H-to-P is a 1-byte latch; P-to-H is a 24-byte FIFO.
    Latch r1_h2p_;
    Fifo24 r1_p2h_;

    // Register 2: 1-byte latch in each direction.
    Latch r2_h2p_;
    Latch r2_p2h_;

    // Register 3: 2-byte FIFO in each direction.
    Reg3 r3_h2p_;
    Reg3 r3_p2h_;

    // Register 4: 1-byte latch in each direction.
    Latch r4_h2p_;
    Latch r4_p2h_;

    // Interrupt output state.
    bool hirq_ = false;
    bool pirq_ = false;
    bool pnmi_condition_ = false;  // raw PNMI condition (always computed)
    bool pnmi_level_ = false;      // M-gated NMI output
    bool prev_pnmi_ = false;       // PNMI edge detector
    bool pnmi_edge_ = false;

    // Bus stretch state (write stretches only).
    bool host_stretched_ = false;
    uint8_t pending_offset_ = 0;
    uint8_t pending_value_ = 0;

public:
    // Transfer counters and the protocol trace ring buffer accumulate across
    // the session (reset only by hard reset). TransferCounters, TraceEntry and
    // TRACE_SIZE are inherited from TubeInspection.
    const TransferCounters& counters() const override { return counters_; }

    // Snapshot the trace buffer. Returns entries oldest-first.
    size_t trace_snapshot(TraceEntry* out, size_t max_entries) const override {
        size_t pos = trace_pos_;
        size_t count = std::min(trace_count_, max_entries);
        count = std::min(count, TRACE_SIZE);
        size_t start = (pos >= count) ? pos - count : TRACE_SIZE - (count - pos);
        for (size_t i = 0; i < count; ++i) {
            out[i] = trace_[(start + i) % TRACE_SIZE];
        }
        return count;
    }

    size_t trace_count() const override { return trace_count_; }

private:
    void trace_event(uint8_t tag, uint8_t value) {
        trace_[trace_pos_] = {tag, value};
        trace_pos_ = (trace_pos_ + 1) % TRACE_SIZE;
        ++trace_count_;
    }

    TransferCounters counters_;
    std::array<TraceEntry, TRACE_SIZE> trace_{};
    size_t trace_pos_ = 0;
    size_t trace_count_ = 0;
};

}  // namespace beebium
