# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""Running a real PiEconetBridge for Beebium's AUN interop tests.

Two interchangeable implementations sit behind :class:`Bridge`: one runs the
upstream ``econet-hpbridge`` binary directly as a subprocess, the other runs it
in a container. Tests never learn which one they got.

Neither needs a Raspberry Pi, an Econet HAT, or the upstream kernel module. The
bridge's ``-l`` switch selects IP-only operation, and a configuration with no
``WIRE NET`` line yields what upstream calls Null networks -- ones carrying
local emulation and distant AUN hosts only.

See ``docs/discussion/pieconetbridge-aun-interop-testing.md``.
"""

from __future__ import annotations

import os
import shutil
import socket
import subprocess
import sys
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path

# Path to the repo root (five levels up from this file).
REPO_ROOT = Path(__file__).resolve().parents[4]

DOCKER_CONTEXT_DIRPATH = REPO_ROOT / "docker" / "pieconetbridge"
IMAGE_TAG = "beebium-pieb:test"

# The bridge logs this once every thread is up and it is ready for traffic.
READY_MARKER = "Main loop going to sleep."

# Logged when a fileserver finishes initialising. Checked separately so a
# fileserver that fails to start is reported as such rather than as a timeout.
FS_READY_MARKER = "successfully initialized on station"


class BridgeStartupError(RuntimeError):
    """The bridge did not reach a ready state."""


@dataclass(frozen=True)
class AunHost:
    """An AUN peer the bridge should know about.

    ``address`` is how *the bridge* reaches the peer, which is not necessarily
    how the peer reaches the bridge -- see :meth:`Bridge.peer_address`.
    """

    net: int
    station: int
    address: str
    port: int
    # Upstream's AUTOACK has the bridge acknowledge our data traffic itself,
    # to damp the duplicate transmissions emulators tend to produce. NONE
    # leaves acknowledgement to the real endpoint, which is the stricter test
    # and the one under which ack timing is observable.
    autoack: bool = False

    def to_config_line(self) -> str:
        mode = "AUTOACK" if self.autoack else "NONE"
        return (
            f"AUN MAP HOST {self.net}.{self.station} "
            f"ON {self.address} PORT {self.port} {mode}"
        )


@dataclass
class BridgeConfig:
    """The topology the bridge should present.

    Every network number must be non-zero: upstream requires it, and works out
    for itself when to present 0 to a given medium. Beebium's matching
    self-declaration is ``--aun net=N``.
    """

    fs_net: int = 1
    fs_station: int = 254
    aun_port: int = 32768
    peers: list[AunHost] = field(default_factory=list)
    # A net from which the bridge may allocate stations to AUN sources it does
    # not recognise. Needed only where NAT rewrites our source endpoint so
    # that no static AUN MAP HOST entry can match it -- see
    # ContainerBridge.natting.
    dynamic_net: int | None = None
    # Filestore disc directories, in upstream's "<disc-number><NAME>" form.
    discs: tuple[str, ...] = ("0BEEBIUM",)
    filestore_path: str = "/filestore"

    def render(self) -> str:
        """Render the configuration file.

        EXPOSE lines must come last: upstream documents this as a present
        limitation of its config parser.
        """
        lines = [
            "# Generated by Beebium's PiEconetBridge interop tests.",
            "# No WIRE NET line: every network here is a Null network.",
            f"FILESERVER ON {self.fs_net}.{self.fs_station} PATH {self.filestore_path}",
        ]
        lines += [peer.to_config_line() for peer in self.peers]
        if self.dynamic_net is not None:
            lines.append(f"DYNAMIC {self.dynamic_net} NONE")
        lines.append(
            f"EXPOSE HOST {self.fs_net}.{self.fs_station} ON PORT *:{self.aun_port}"
        )
        return "\n".join(lines)


class Bridge(ABC):
    """A running PiEconetBridge, however it happens to be hosted."""

    def __init__(self, config: BridgeConfig):
        self.config = config

    # ---- Addressing ----
    #
    # The two directions are not symmetric and must not be conflated. A
    # container reaches the host by one name and is seen by the host under
    # another, and Beebium's AUN backend silently discards datagrams whose
    # source is not in its peer table -- so getting this wrong looks exactly
    # like the packet-loss defects these tests exist to find.

    @abstractmethod
    def peer_address(self) -> str:
        """The address Beebium should use to reach the bridge, and the address
        Beebium should expect the bridge's datagrams to arrive from."""

    @abstractmethod
    def host_address_for_bridge(self) -> str:
        """The address the bridge should use to reach Beebium on this host."""

    @property
    def aun_port(self) -> int:
        return self.config.aun_port

    @property
    def fileserver(self) -> tuple[int, int]:
        return (self.config.fs_net, self.config.fs_station)

    def beebium_map_entry(self) -> str:
        """The ``--aun map=`` value pointing at this bridge's fileserver."""
        net, station = self.fileserver
        return f"{net}.{station}@{self.peer_address()}@{self.aun_port}"

    # ---- Lifecycle ----

    @abstractmethod
    def logs(self) -> str:
        """Everything the bridge has written so far, for failure diagnostics."""

    @abstractmethod
    def stop(self) -> None:
        ...

    def wait_until_ready(self, timeout_seconds: float = 30.0) -> None:
        deadline = time.monotonic() + timeout_seconds
        while time.monotonic() < deadline:
            log = self.logs()
            if READY_MARKER in log:
                if FS_READY_MARKER not in log:
                    raise BridgeStartupError(
                        "Bridge started but no fileserver initialised:\n" + log
                    )
                return
            if not self.is_running():
                raise BridgeStartupError("Bridge exited during startup:\n" + log)
            time.sleep(0.1)
        raise BridgeStartupError(
            f"Bridge not ready within {timeout_seconds}s:\n{self.logs()}"
        )

    @abstractmethod
    def is_running(self) -> bool:
        ...

    def __enter__(self) -> Bridge:
        return self

    def __exit__(self, *exc_info) -> None:
        self.stop()


class NativeBridge(Bridge):
    """The bridge as a plain subprocess. Linux only, fastest inner loop."""

    def __init__(self, config: BridgeConfig, binary: Path, workdir: Path):
        super().__init__(config)
        self._workdir = workdir
        self._log_filepath = workdir / "bridge.log"

        filestore = workdir / "filestore"
        for disc in config.discs:
            (filestore / disc).mkdir(parents=True, exist_ok=True)

        # The rendered config must point at this run's private filestore
        # rather than the in-container path.
        self.config = BridgeConfig(
            fs_net=config.fs_net,
            fs_station=config.fs_station,
            aun_port=config.aun_port,
            peers=config.peers,
            discs=config.discs,
            filestore_path=str(filestore),
        )
        config_filepath = workdir / "econet-hpbridge.cfg"
        config_filepath.write_text(self.config.render() + "\n")

        self._log_file = self._log_filepath.open("w+")
        # -l IP-only (no Econet devices); -s dump the resolved topology;
        # -z -z the debug level at which the startup progress lines this
        # fixture waits on are emitted. Kept identical to the container
        # entrypoint's arguments so the two flavours behave the same.
        self._process = subprocess.Popen(
            [str(binary), "-l", "-c", str(config_filepath), "-s", "-z", "-z"],
            stdout=self._log_file,
            stderr=subprocess.STDOUT,
            cwd=str(workdir),
        )

    def peer_address(self) -> str:
        return "127.0.0.1"

    def host_address_for_bridge(self) -> str:
        return "127.0.0.1"

    def logs(self) -> str:
        try:
            return self._log_filepath.read_text(errors="replace")
        except FileNotFoundError:
            return ""

    def is_running(self) -> bool:
        return self._process.poll() is None

    def stop(self) -> None:
        if self._process.poll() is None:
            self._process.terminate()
            try:
                self._process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self._process.kill()
                self._process.wait(timeout=10)
        self._log_file.close()


class ContainerBridge(Bridge):
    """The bridge in a container. Works anywhere Docker does."""

    def __init__(self, config: BridgeConfig, container_name: str,
                 use_host_network: bool):
        super().__init__(config)
        self._name = container_name
        self._use_host_network = use_host_network
        self._peer_address = "127.0.0.1"
        self._stopped = False

        argv = [
            "docker", "run", "--rm", "--detach",
            "--name", container_name,
            "--env", f"PIEB_CONFIG={config.render()}",
            "--env", f"PIEB_DISCS={' '.join(config.discs)}",
        ]
        if use_host_network:
            argv += ["--network", "host"]
        else:
            argv += ["--publish", f"{config.aun_port}:{config.aun_port}/udp"]
        argv.append(IMAGE_TAG)

        result = subprocess.run(argv, capture_output=True, text=True)
        if result.returncode != 0:
            raise BridgeStartupError(
                f"docker run failed: {result.stderr.strip()}"
            )

    def peer_address(self) -> str:
        return self._peer_address

    def host_address_for_bridge(self) -> str:
        # With host networking the container shares the host's stack, so
        # loopback is genuinely loopback. Otherwise the container reaches the
        # host through Docker's well-known alias.
        return "127.0.0.1" if self._use_host_network else "host.docker.internal"

    def discover_peer_address(self, timeout_seconds: float = 15.0) -> str:
        """Learn the address the bridge's datagrams will appear to come from.

        Under host networking that is loopback and no probe is needed. Under
        published-port networking the container is NAT'd, and neither the
        published address nor anything the container can see about itself is
        the answer -- so ask the network: have the container send one datagram
        to a socket on this host and read the source address off it.

        This matters because ``AunBackend`` discards datagrams from senders
        absent from its peer table, so a wrong answer here presents as inbound
        traffic vanishing.
        """
        if self._use_host_network:
            self._peer_address = "127.0.0.1"
            return self._peer_address

        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as probe:
            probe.bind(("0.0.0.0", 0))
            probe.settimeout(timeout_seconds)
            probe_port = probe.getsockname()[1]

            deadline = time.monotonic() + timeout_seconds
            while time.monotonic() < deadline:
                subprocess.run(
                    ["docker", "exec", self._name, "sh", "-c",
                     f"echo beebium-probe | nc -u -w1 host.docker.internal "
                     f"{probe_port}"],
                    capture_output=True, text=True, timeout=10,
                )
                try:
                    _, (source_address, _) = probe.recvfrom(64)
                except socket.timeout:
                    continue
                self._peer_address = source_address
                return self._peer_address

        raise BridgeStartupError(
            "Could not determine the container's source address. The bridge "
            "would be able to send to Beebium but Beebium would discard the "
            "datagrams as coming from an unknown peer."
        )

    def logs(self) -> str:
        result = subprocess.run(
            ["docker", "logs", self._name],
            capture_output=True, text=True,
        )
        return result.stdout + result.stderr

    def is_running(self) -> bool:
        result = subprocess.run(
            ["docker", "inspect", "-f", "{{.State.Running}}", self._name],
            capture_output=True, text=True,
        )
        return result.stdout.strip() == "true"

    def stop(self) -> None:
        if self._stopped:
            return
        self._stopped = True
        subprocess.run(["docker", "stop", "-t", "5", self._name],
                       capture_output=True, text=True)


# ---- Selection ----


def docker_available() -> bool:
    if shutil.which("docker") is None:
        return False
    result = subprocess.run(
        ["docker", "info", "--format", "{{.OSType}}"],
        capture_output=True, text=True,
    )
    return result.returncode == 0


def build_image() -> None:
    """Build the bridge image. Cheap when Docker's layer cache is warm."""
    result = subprocess.run(
        ["docker", "build", "-t", IMAGE_TAG, str(DOCKER_CONTEXT_DIRPATH)],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        raise BridgeStartupError(
            "Failed to build the PiEconetBridge image:\n"
            + result.stdout[-4000:] + result.stderr[-4000:]
        )


def native_binary() -> Path | None:
    """Locate a natively-built ``econet-hpbridge``, if there is one."""
    if sys.platform != "linux":
        return None
    env = os.environ.get("BEEBIUM_PIEB_BIN")
    if env:
        candidate = Path(env)
        return candidate if candidate.exists() else None
    src = os.environ.get("BEEBIUM_PIEB_SRC")
    if src:
        candidate = Path(src) / "utilities" / "econet-hpbridge"
        return candidate if candidate.exists() else None
    return None


def free_udp_port() -> int:
    """Reserve an ephemeral UDP port by binding and releasing it.

    Inherently racy, but the alternative -- fixed ports -- collides with
    leftover sockets from a previous run and with parallel test sessions,
    which is a worse and more confusing failure.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]
