// Copyright © 2025 Robert Smallshire <robert@smallshire.org.uk>
//
// This file is part of Beebium.
//
// Beebium is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version. Beebium is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with Beebium.
// If not, see <https://www.gnu.org/licenses/>.

import AppKit
import AudioToolbox
import Foundation
import GRPC
import NIO
import os

/// BBC keyboard internal key numbers for modifier keys
private enum BBCModifierKey {
    static let shift: UInt8 = 0x00      // Row 0, Column 0
    static let ctrl: UInt8 = 0x01       // Row 0, Column 1
    static let capsLock: UInt8 = 0x40   // Row 4, Column 0
}

/// Tracks a pressed key. The fact captures everything the modifier-state
/// decision function needs; ikNumber and isBreak handle the actual key
/// press / release on the BBC matrix.
private struct PressedKeyState {
    let ikNumber: UInt8
    let isBreak: Bool
    let fact: PressedKeyFact
}

/// Client for sending keyboard input to beebium-server via gRPC.
///
/// This client uses the keyboard mapping system to resolve host key inputs
/// to BBC keyboard matrix positions, including automatic handling of
/// synthetic Shift and Ctrl keys.
@MainActor
final class KeyboardClient: ObservableObject, Disconnectable {

    private static let log = Logger(subsystem: "com.beebium", category: "keyboard")

    private var channel: GRPCChannel?
    private var client: Beebium_KeyboardServiceClient?

    /// The keyboard mapping manager (provides cache and active mapping)
    weak var mappingManager: KeyboardMappingManager?

    /// Track pressed keys by their keyCode (for proper release matching)
    /// Maps keyCode to the state of the pressed key
    private var pressedKeys: [UInt16: PressedKeyState] = [:]

    /// Last BBC SHIFT / CTRL state we sent. Used to suppress redundant
    /// keyDown / keyUp messages on the wire.
    private var bbcShiftIsDown: Bool = false
    private var bbcCtrlIsDown: Bool = false

    /// True while the gRPC keyboard stub is wired up and ready to send.
    /// Observed by SwiftUI views so they can re-trigger startup-time work
    /// (e.g. Caps Lock sync) once the connection actually becomes usable.
    /// See comment on syncCapsLockState for the race that motivates this.
    @Published private(set) var isConnected: Bool = false

    /// Tail of a chained Task queue. Each gRPC send is enqueued in
    /// submission order and awaits the previous send so the BBC sees
    /// modifier and key events in the order they were generated by the
    /// host. Without this serialisation, a fast press-and-release could
    /// have its keyDown Task re-evaluate state after the keyUp's
    /// synchronous bookkeeping had already run, dropping the modifier
    /// (e.g. typing `'` would arrive at the BBC without SHIFT and
    /// produce `7`).
    private var sendTail: Task<Void, Never>?

    /// Cached SystemSoundID for disabled key sound
    private var disabledKeySoundID: SystemSoundID = 0

    // MARK: - Caps Lock Sync

    /// Rate limiting: minimum interval between sync operations (500ms)
    private let minSyncInterval: TimeInterval = 0.5

    /// Time of last sync operation
    private var lastSyncTime: Date = .distantPast

    /// Connect to the keyboard service using an existing channel
    /// - Parameter channel: The gRPC channel (shared with VideoClient)
    func connect(channel: GRPCChannel) {
        self.channel = channel
        self.client = Beebium_KeyboardServiceClient(channel: channel)
        pressedKeys.removeAll()
        bbcShiftIsDown = false
        bbcCtrlIsDown = false
        sendTail = nil

        // Initialize disabled key sound (Funk)
        if disabledKeySoundID == 0 {
            let soundURL = URL(fileURLWithPath: "/System/Library/Sounds/Funk.aiff")
            AudioServicesCreateSystemSoundID(soundURL as CFURL, &disabledKeySoundID)
        }

        // Publish "ready to send" *after* self.client has been wired up so
        // any observer's re-triggered work sees a usable client.
        isConnected = true

        print("[KeyboardClient] Connected to keyboard service")
    }

    /// Disconnect from the server
    func disconnect() {
        // Drain everything through the same serialised send queue so the
        // wire sees the releases in a coherent order.
        let pressedSnapshot = pressedKeys
        let shiftWasDown = bbcShiftIsDown
        let ctrlWasDown = bbcCtrlIsDown
        enqueueSend { [weak self] in
            guard let self = self else { return }
            for (_, state) in pressedSnapshot {
                if !self.isModifierIK(state.ikNumber) {
                    await self.sendKeyUp(ikNumber: state.ikNumber)
                }
            }
            if shiftWasDown {
                await self.sendKeyUp(ikNumber: BBCModifierKey.shift)
            }
            if ctrlWasDown {
                await self.sendKeyUp(ikNumber: BBCModifierKey.ctrl)
            }
        }

        // Clean up disabled key sound
        if disabledKeySoundID != 0 {
            AudioServicesDisposeSystemSoundID(disabledKeySoundID)
            disabledKeySoundID = 0
        }

        pressedKeys.removeAll()
        bbcShiftIsDown = false
        bbcCtrlIsDown = false
        sendTail = nil
        isConnected = false

        client = nil
        channel = nil
    }

    /// Fetch the keyboard mappings from the core and populate the cache
    func loadKeyMappings() async {
        guard let client = client else {
            print("[KeyboardClient] loadKeyMappings: no client!")
            return
        }

        do {
            let request = Beebium_GetAllKeyMappingsRequest()
            let response = try await client.getAllKeyMappings(request).response.get()
            mappingManager?.loadCache(from: response)
            print("[KeyboardClient] Loaded \(response.mappings.count) key mappings from core")
        } catch {
            print("[KeyboardClient] Failed to load key mappings: \(error)")
        }
    }

    /// Handle a key down event
    /// - Parameter input: The key input event
    func keyDown(input: KeyInput) {
        guard let manager = mappingManager,
              let mapping = manager.activeMapping,
              manager.isCacheLoaded else {
            print("[KeyboardClient] keyDown: mapping not ready")
            return
        }

        // Resolve the input using the active mapping
        guard let resolved = mapping.resolve(input, cache: manager.bbcKeyCache) else {
            // Key not mapped - play system alert (unless it's a host modifier key)
            if !MacKeyCode.isHostModifierKey(input.keyCode) {
                signalUnmappedKey()
            }
            print("[KBD][resolve] keyCode=\(input.keyCode) -> UNMAPPED"
                  + " (mapping=\(mapping.name))")
            return
        }

        print("[KBD][resolve] keyCode=\(input.keyCode)"
              + " -> bbcKeyName=\(resolved.bbcKeyName)"
              + " ik=\(formatIk(resolved.ikNumber))"
              + " bbcShift=\(resolved.bbcShift) bbcCtrl=\(resolved.bbcCtrl)"
              + " fromCharMap=\(resolved.fromCharacterMapping)"
              + " (mapping=\(mapping.name))")

        // Check if key is disabled
        if manager.isKeyDisabled(resolved.bbcKeyName) {
            signalDisabledKey()
            print("[KBD][resolve] -> DISABLED")
            return
        }

        // Check if already pressed (by keyCode)
        if pressedKeys[input.keyCode] != nil {
            print("[KBD][resolve] -> already pressed, ignoring")
            return
        }

        // Synchronous bookkeeping: capture this press, then decide which
        // modifier transitions it triggers. Doing this synchronously (not
        // inside a Task) is what makes the decision race-free against a
        // fast keyUp arriving immediately afterwards. The actual gRPC
        // sends are dispatched onto a serialised task chain so the BBC
        // sees them in submission order.
        let fact = makeFact(for: resolved)
        let state = PressedKeyState(
            ikNumber: resolved.ikNumber,
            isBreak: resolved.isBreak,
            fact: fact
        )
        pressedKeys[input.keyCode] = state

        print("[KBD][fact] ik=\(formatIk(fact.bbcKeyName, ik: resolved.ikNumber))"
              + " needsSyntheticShift=\(fact.needsSyntheticShift)"
              + " forbidsShift=\(fact.forbidsShift)"
              + " needsSyntheticCtrl=\(fact.needsSyntheticCtrl)"
              + " forbidsCtrl=\(fact.forbidsCtrl)")

        let shiftAction = computeShiftAction()
        let ctrlAction = computeCtrlAction()
        let isBreak = resolved.isBreak
        let ikNumber = resolved.ikNumber
        let isModifier = isModifierIK(ikNumber)

        print("[KBD][decide.down] desired shiftAction=\(describe(shiftAction))"
              + " ctrlAction=\(describe(ctrlAction))"
              + " ikToSend=\(isBreak ? "BREAK" : (isModifier ? "(reconciler-owned)" : formatIk(ikNumber)))")

        enqueueSend { [weak self] in
            guard let self = self else { return }
            if isBreak {
                await self.sendBreakDown()
                return
            }
            // Drive BBC SHIFT / CTRL to the new desired state BEFORE the
            // key arrives so the BBC sees the modifier coherently.
            await self.applyModifierAction(shiftAction, ikNumber: BBCModifierKey.shift)
            await self.applyModifierAction(ctrlAction, ikNumber: BBCModifierKey.ctrl)
            if !isModifier {
                await self.sendKeyDown(ikNumber: ikNumber)
            }
        }
    }

    /// Handle a key up event
    /// - Parameter input: The key input event
    func keyUp(input: KeyInput) {
        guard let state = pressedKeys.removeValue(forKey: input.keyCode) else {
            print("[KBD][keyUp] keyCode=\(input.keyCode) was not tracked, ignoring")
            return
        }

        let shiftAction = computeShiftAction()
        let ctrlAction = computeCtrlAction()
        let ikNumber = state.ikNumber
        let isBreak = state.isBreak
        let isModifier = isModifierIK(ikNumber)

        print("[KBD][decide.up] keyCode=\(input.keyCode)"
              + " released ik=\(formatIk(ikNumber))"
              + " desired shiftAction=\(describe(shiftAction))"
              + " ctrlAction=\(describe(ctrlAction))"
              + " ikToSend=\(isBreak ? "BREAK" : (isModifier ? "(reconciler-owned)" : formatIk(ikNumber)))")

        enqueueSend { [weak self] in
            guard let self = self else { return }
            if isBreak {
                await self.sendBreakUp()
                return
            }
            // Release the key, then drive modifiers (so a held forbid-key
            // disappearing causes BBC SHIFT to come back on AFTER the key
            // release, never before). BBC SHIFT and BBC CTRL matrix
            // positions are owned by the modifier action.
            if !isModifier {
                await self.sendKeyUp(ikNumber: ikNumber)
            }
            await self.applyModifierAction(shiftAction, ikNumber: BBCModifierKey.shift)
            await self.applyModifierAction(ctrlAction, ikNumber: BBCModifierKey.ctrl)
        }
    }

    private func isModifierIK(_ ikNumber: UInt8) -> Bool {
        ikNumber == BBCModifierKey.shift || ikNumber == BBCModifierKey.ctrl
    }

    /// Build the PressedKeyFact for a freshly-resolved key, deciding the
    /// synthesis / forbid flags from the current physical modifier state.
    private func makeFact(for resolved: KeyboardMapping.ResolvedKey) -> PressedKeyFact {
        let physicalShiftHeld = pressedKeys.values.contains { st in
            !st.fact.fromCharacterMapping && st.fact.bbcKeyName == "Shift"
        }
        let physicalCtrlHeld = pressedKeys.values.contains { st in
            !st.fact.fromCharacterMapping && st.fact.bbcKeyName == "Ctrl"
        }

        if resolved.fromCharacterMapping {
            let s = BBCModifierState.shiftFlagsForCharacter(
                bbcShiftRequired: resolved.bbcShift,
                physicalShiftHeld: physicalShiftHeld
            )
            let c = BBCModifierState.ctrlFlagsForCharacter(
                bbcCtrlRequired: resolved.bbcCtrl,
                physicalCtrlHeld: physicalCtrlHeld
            )
            return PressedKeyFact(
                bbcKeyName: resolved.bbcKeyName,
                fromCharacterMapping: true,
                needsSyntheticShift: s.needsSynthetic,
                forbidsShift: s.forbids,
                needsSyntheticCtrl: c.needsSynthetic,
                forbidsCtrl: c.forbids
            )
        }

        // Direct mapping. The SHIFT / CTRL keys themselves don't synthesise
        // -- they just register physical presence via bbcKeyName. Other
        // direct mappings honour their explicit bbcWithShift / bbcWithCtrl
        // (e.g. F1 mapped to BBC "!" with synthetic shift).
        let isDirectModifier =
            resolved.bbcKeyName == "Shift" || resolved.bbcKeyName == "Ctrl"
        return PressedKeyFact(
            bbcKeyName: resolved.bbcKeyName,
            fromCharacterMapping: false,
            needsSyntheticShift: !isDirectModifier && resolved.bbcShift,
            forbidsShift: false,
            needsSyntheticCtrl: !isDirectModifier && resolved.bbcCtrl,
            forbidsCtrl: false
        )
    }

    /// Decide what to do with BBC SHIFT in response to the latest
    /// pressedKeys change. Returns nil = no transition, true = press,
    /// false = release. Synchronously updates bbcShiftIsDown so the next
    /// event computes against the freshly-decided state.
    private func computeShiftAction() -> Bool? {
        let facts = pressedKeys.values.map { $0.fact }
        let desired = BBCModifierState.desiredShift(pressedKeys: facts)
        guard desired != bbcShiftIsDown else { return nil }
        bbcShiftIsDown = desired
        return desired
    }

    private func computeCtrlAction() -> Bool? {
        let facts = pressedKeys.values.map { $0.fact }
        let desired = BBCModifierState.desiredCtrl(pressedKeys: facts)
        guard desired != bbcCtrlIsDown else { return nil }
        bbcCtrlIsDown = desired
        return desired
    }

    private func applyModifierAction(_ action: Bool?, ikNumber: UInt8) async {
        guard let action = action else { return }
        print("[KBD][modifier] ik=\(formatIk(ikNumber)) -> \(action ? "DOWN" : "UP")")
        if action {
            await sendKeyDown(ikNumber: ikNumber)
        } else {
            await sendKeyUp(ikNumber: ikNumber)
        }
    }

    /// Append a gRPC-send job to the serialised tail. Each job awaits the
    /// previous one so the wire sees the events in submission order.
    private func enqueueSend(_ work: @escaping @MainActor () async -> Void) {
        let prev = sendTail
        sendTail = Task { @MainActor in
            await prev?.value
            await work()
        }
    }

    // MARK: - Caps Lock Synchronization

    /// Handle user pressing Mac Caps Lock key (from flagsChanged event)
    func handleCapsLockToggle() {
        let enabled = mappingManager?.isCapsLockSyncEnabled == true
        print("[KBD][capsLock.toggle] syncEnabled=\(enabled) connected=\(isConnected)")
        guard enabled else { return }
        guard isConnected else {
            // No client to send to; the per-channel connect() will publish
            // isConnected=true and ContentView re-runs the sync.
            return
        }
        pressCapsLock()
    }

    /// Query the BBC's logical CAPS / SHIFT LOCK latch state.
    ///
    /// Reads the MOS-maintained latch bits directly, so the result is exact at
    /// any emulation speed -- unlike the lock-LED brightness from the indicator
    /// stream, which is duty-cycle filtered for display and only settles to
    /// 0/255 in real time. Returns nil if the client is not connected or the
    /// query fails.
    func getLockState() async -> Beebium_LockKeyState? {
        guard let client = client else { return nil }
        do {
            return try await client.getLockState(Beebium_GetLockStateRequest()).response.get()
        } catch {
            // Log loudly (Console-visible, unlike print to stdout): a failure
            // here disables caps-lock sync, and an UNIMPLEMENTED status means the
            // server is too old for this RPC -- which the protocol-fingerprint
            // check at connect should already have flagged.
            Self.log.error("getLockState failed: \(String(describing: error), privacy: .public)")
            return nil
        }
    }

    /// The BBC's logical CAPS LOCK state, or nil if it could not be read.
    func capsLockIsOn() async -> Bool? {
        await getLockState()?.capsLockOn
    }

    /// Sync BBC Caps Lock state to match macOS state (with rate limiting).
    /// - Parameter macCapsLockIsOn: Current macOS Caps Lock state.
    func syncCapsLockState(macCapsLockIsOn: Bool) {
        let enabled = mappingManager?.isCapsLockSyncEnabled == true
        guard enabled else { return }

        // The keyboard service may not be wired up yet during startup. Calls
        // arriving before connect() (e.g. NSWindow.didBecomeKey firing
        // before the gRPC channel is established) would otherwise
        // pressCapsLock(), have its sendKeyDown dropped with
        // "no client!", but its sendKeyUp later go through after the 50ms
        // sleep -- leaving an orphan KeyUp on the BBC and the sync intent
        // silently lost. Drop the call here; ContentView observes
        // isConnected and re-fires this method when connect() completes.
        guard isConnected else {
            print("[KBD][capsLock.sync] not connected, deferring")
            return
        }

        // Rate limiting to prevent feedback loops. Claimed up front so the
        // async latch query below is issued at most once per window.
        let now = Date()
        guard now.timeIntervalSince(lastSyncTime) >= minSyncInterval else { return }
        lastSyncTime = now

        Task {
            // Read the exact logical caps-lock state from the latch. It is
            // correct at any emulation speed, where the lock-LED brightness
            // this used to infer from never settles to a definitive 0/255.
            guard let bbcCapsLockIsOn = await capsLockIsOn() else { return }
            if macCapsLockIsOn != bbcCapsLockIsOn {
                print("[KBD][capsLock.sync] macOn=\(macCapsLockIsOn)"
                      + " bbcOn=\(bbcCapsLockIsOn) -> tap")
                pressCapsLock()
            }
        }
    }

    /// Send a complete Caps Lock key DOWN/UP cycle to BBC.
    /// The 50ms delay ensures MOS has time to scan keyboard and process the key press.
    private func pressCapsLock() {
        print("[KBD][capsLock.tap] ik=\(formatIk(BBCModifierKey.capsLock)) DOWN/UP")
        Task {
            await sendKeyDown(ikNumber: BBCModifierKey.capsLock)

            // Wait 50ms for MOS keyboard scan (40ms scan interval + 10ms margin)
            try? await Task.sleep(nanoseconds: 50_000_000)

            await sendKeyUp(ikNumber: BBCModifierKey.capsLock)
        }
    }

    // MARK: - Key Tap by Name

    /// Tap a BBC key by its logical name (e.g., "Shift Lock", "Caps Lock").
    /// Performs a complete keydown-keyup press cycle with appropriate delay.
    func tapKeyByName(_ name: String) {
        guard let manager = mappingManager,
              let entry = manager.bbcKeyCache.lookup(name: name) else {
            print("[KeyboardClient] Key not found: \(name)")
            return
        }
        Task {
            await sendKeyDown(ikNumber: entry.ikNumber)
            // Wait 50ms for MOS keyboard scan (same as Caps Lock sync)
            try? await Task.sleep(nanoseconds: 50_000_000)
            await sendKeyUp(ikNumber: entry.ikNumber)
        }
    }

    // MARK: - Typing Text

    /// Type a string on the emulated keyboard, one key at a time.
    ///
    /// The server paces the keystrokes so the MOS reliably scans each one, and
    /// translates host text conventions (line endings, typographic punctuation,
    /// teletext glyphs) into what the BBC keyboard can type. Translation is the
    /// server's default and this client never asks for anything else: pasting
    /// moves characters, not bytes.
    ///
    /// Returns nil on success, or a message describing why the text was
    /// refused. The caller is expected to show that to the user -- a paste
    /// that silently does nothing is worse than one that explains itself.
    @discardableResult
    func typeQuickly(_ text: String) async -> String? {
        guard let client = client else {
            print("[KeyboardClient] typeQuickly: no client!")
            return "Not connected to a machine"
        }

        var request = Beebium_TypeQuicklyRequest()
        request.text = text

        do {
            let response = try await client.typeQuickly(request).response.get()
            if !response.accepted {
                // The server declined the whole string; it names the character
                // at fault when there is one.
                let reason = response.error.isEmpty
                    ? "The machine would not accept the text"
                    : response.error
                print("[KeyboardClient] typeQuickly refused: \(reason)")
                return reason
            }
            return nil
        } catch {
            print("[KeyboardClient] typeQuickly failed: \(error)")
            return "Could not send the text to the machine"
        }
    }

    /// Whether the server has finished typing everything it was given.
    ///
    /// Returns nil if the status could not be read, which the caller must treat
    /// as "unknown" rather than "finished" -- concluding a paste is done when it
    /// is not would restore the emulation speed mid-paste.
    func isTypingComplete() async -> Bool? {
        guard let client = client else { return nil }
        do {
            let response = try await client.getTypingStatus(
                Beebium_GetTypingStatusRequest()).response.get()
            return response.idle
        } catch {
            print("[KeyboardClient] getTypingStatus failed: \(error)")
            return nil
        }
    }

    /// Discard whatever is still queued to be typed, returning the count dropped.
    @discardableResult
    func clearTyping() async -> Int {
        guard let client = client else { return 0 }
        do {
            let response = try await client.clearTyping(
                Beebium_ClearTypingRequest()).response.get()
            return Int(response.charactersCleared)
        } catch {
            print("[KeyboardClient] clearTyping failed: \(error)")
            return 0
        }
    }

    /// Wait until the server reports that everything queued has been typed.
    ///
    /// The server is the only party that knows when the queue drains, so it
    /// says so on a stream rather than the client polling and inferring it.
    /// Any inference would need a timeout, and no timeout is right for every
    /// paste: throughput depends on how fast the host emulates and on the text
    /// itself, since every capital costs an extra SHIFT press.
    ///
    /// Returns when the queue is empty, or when the stream ends for any other
    /// reason -- a cancelled paste, a lost connection, a stopped server. The
    /// caller cannot distinguish those and should not need to: in every case
    /// there is nothing more to wait for.
    func waitUntilTypingComplete() async {
        guard let client = client else { return }

        await withCheckedContinuation { continuation in
            // Resumed exactly once, by whichever comes first: the server
            // reporting an empty queue, or the stream ending.
            let hasResumed = ResumeOnce(continuation)

            let call = client.watchTypingStatus(Beebium_WatchTypingStatusRequest()) { status in
                if status.idle { hasResumed.resume() }
            }

            call.status.whenComplete { _ in
                // Covers a cancelled paste, a dropped connection and a stopped
                // server alike. The caller cannot tell those apart and does not
                // need to: in every case there is nothing left to wait for.
                hasResumed.resume()
            }

            hasResumed.onResume = { call.cancel(promise: nil) }
        }
    }

    // MARK: - Touch Bar Support

    /// Send a key down event directly by ikNumber (bypasses mapping system).
    /// Used by TouchBar to send keys by their BBC internal key number.
    func touchBarKeyDown(ikNumber: UInt8) async {
        await sendKeyDown(ikNumber: ikNumber)
    }

    /// Send a key up event directly by ikNumber (bypasses mapping system).
    /// Used by TouchBar to send keys by their BBC internal key number.
    func touchBarKeyUp(ikNumber: UInt8) async {
        await sendKeyUp(ikNumber: ikNumber)
    }

    /// Send a BREAK key down event (bypasses mapping system).
    /// Used by TouchBar BREAK key.
    func touchBarBreakDown() async {
        await sendBreakDown()
    }

    /// Send a BREAK key up event (bypasses mapping system).
    /// Used by TouchBar BREAK key.
    func touchBarBreakUp() async {
        await sendBreakUp()
    }

    // MARK: - Private gRPC Methods

    private func sendKeyDown(ikNumber: UInt8) async {
        guard let client = client else {
            print("[KeyboardClient] sendKeyDown: no client!")
            return
        }

        print("[KBD][wire.tx] KeyDown ik=\(formatIk(ikNumber))")
        var request = Beebium_KeyRequest()
        request.ikNumber = UInt32(ikNumber)

        do {
            _ = try await client.keyDown(request).response.get()
        } catch {
            print("[KeyboardClient] sendKeyDown gRPC error: \(error)")
        }
    }

    private func sendKeyUp(ikNumber: UInt8) async {
        guard let client = client else {
            print("[KeyboardClient] sendKeyUp: no client!")
            return
        }

        print("[KBD][wire.tx] KeyUp   ik=\(formatIk(ikNumber))")
        var request = Beebium_KeyRequest()
        request.ikNumber = UInt32(ikNumber)

        do {
            _ = try await client.keyUp(request).response.get()
        } catch {
            print("[KeyboardClient] sendKeyUp gRPC error: \(error)")
        }
    }

    // MARK: - Logging helpers

    /// Render an ikNumber as `0xHH(row,col)[name]`. Falls back if no name.
    private func formatIk(_ ikNumber: UInt8) -> String {
        let row = (ikNumber >> 4) & 0x0F
        let col = ikNumber & 0x0F
        let nameSuffix: String
        if ikNumber == BBCModifierKey.shift {
            nameSuffix = "[BBC.Shift]"
        } else if ikNumber == BBCModifierKey.ctrl {
            nameSuffix = "[BBC.Ctrl]"
        } else if ikNumber == BBCModifierKey.capsLock {
            nameSuffix = "[BBC.CapsLock]"
        } else {
            nameSuffix = ""
        }
        return String(format: "0x%02X(%d,%d)%@", ikNumber, row, col, nameSuffix)
    }

    /// Render an ikNumber alongside the BBC key name we resolved it from.
    private func formatIk(_ bbcKeyName: String, ik ikNumber: UInt8) -> String {
        return "\(formatIk(ikNumber))[\(bbcKeyName)]"
    }

    /// Render the optional Bool result of computeShiftAction / computeCtrlAction.
    private func describe(_ action: Bool?) -> String {
        switch action {
        case .none:        return "no-change"
        case .some(true):  return "DOWN"
        case .some(false): return "UP"
        }
    }

    private func sendBreakDown() async {
        guard let client = client else {
            print("[KeyboardClient] sendBreakDown: no client!")
            return
        }

        let request = Beebium_BreakDownRequest()

        do {
            _ = try await client.breakDown(request).response.get()
        } catch {
            print("[KeyboardClient] sendBreakDown gRPC error: \(error)")
        }
    }

    private func sendBreakUp() async {
        guard let client = client else {
            print("[KeyboardClient] sendBreakUp: no client!")
            return
        }

        let request = Beebium_BreakUpRequest()

        do {
            _ = try await client.breakUp(request).response.get()
        } catch {
            print("[KeyboardClient] sendBreakUp gRPC error: \(error)")
        }
    }

    /// Play system alert sound for unmapped keys
    private func signalUnmappedKey() {
        AudioServicesPlaySystemSound(kSystemSoundID_UserPreferredAlert)
    }

    /// Play Funk sound for disabled keys (distinct from unmapped alert)
    private func signalDisabledKey() {
        if disabledKeySoundID != 0 {
            AudioServicesPlaySystemSound(disabledKeySoundID)
        }
    }
}

/// Resumes a continuation exactly once, however many callers race to do it.
///
/// A watched stream can finish two ways at nearly the same moment -- the
/// server reports the queue empty, and the call then completes -- and resuming
/// a continuation twice traps.
private final class ResumeOnce: @unchecked Sendable {
    private let lock = NSLock()
    private var continuation: CheckedContinuation<Void, Never>?
    private var pendingOnResume: (() -> Void)?
    private var alreadyResumed = false

    init(_ continuation: CheckedContinuation<Void, Never>) {
        self.continuation = continuation
    }

    /// Run when the wait ends, whichever way it ends.
    var onResume: (() -> Void)? {
        get { lock.withLock { pendingOnResume } }
        set {
            let runNow: Bool = lock.withLock {
                pendingOnResume = newValue
                return alreadyResumed
            }
            if runNow { newValue?() }
        }
    }

    func resume() {
        let (toResume, cleanup): (CheckedContinuation<Void, Never>?, (() -> Void)?) = lock.withLock {
            guard !alreadyResumed else { return (nil, nil) }
            alreadyResumed = true
            let c = continuation
            continuation = nil
            return (c, pendingOnResume)
        }
        toResume?.resume()
        cleanup?()
    }
}
