// Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
//
// This file is part of Beebium.
//
// Beebium is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version. Beebium is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with Beebium.
// If not, see <https://www.gnu.org/licenses/>.

// Generated by scripts/sync_protocol_fingerprint.py. DO NOT EDIT.
#ifndef BEEBIUM_SERVICE_PROTOCOL_FINGERPRINT_HPP
#define BEEBIUM_SERVICE_PROTOCOL_FINGERPRINT_HPP

#include <string_view>

namespace beebium::service {

inline constexpr std::string_view PROTOCOL_FINGERPRINT = "893025fbae7ea26724f750d7fd0947f23195010df4b502f525c52ab0392de42c";

}  // namespace beebium::service

#endif  // BEEBIUM_SERVICE_PROTOCOL_FINGERPRINT_HPP
