# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _StopReason:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StopReasonEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StopReason.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STOP_REASON_UNKNOWN: _StopReason.ValueType  # 0
    STOP_REASON_BREAKPOINT: _StopReason.ValueType  # 1
    STOP_REASON_MANUAL: _StopReason.ValueType  # 2
    STOP_REASON_ERROR: _StopReason.ValueType  # 3
    STOP_REASON_STEP_COMPLETE: _StopReason.ValueType  # 4
    STOP_REASON_WATCHPOINT: _StopReason.ValueType  # 5
    STOP_REASON_COUNTERPART: _StopReason.ValueType  # 6

class StopReason(_StopReason, metaclass=_StopReasonEnumTypeWrapper): ...

STOP_REASON_UNKNOWN: StopReason.ValueType  # 0
STOP_REASON_BREAKPOINT: StopReason.ValueType  # 1
STOP_REASON_MANUAL: StopReason.ValueType  # 2
STOP_REASON_ERROR: StopReason.ValueType  # 3
STOP_REASON_STEP_COMPLETE: StopReason.ValueType  # 4
STOP_REASON_WATCHPOINT: StopReason.ValueType  # 5
STOP_REASON_COUNTERPART: StopReason.ValueType  # 6
Global___StopReason: _TypeAlias = StopReason  # noqa: Y015

class _WatchpointType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _WatchpointTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_WatchpointType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    WATCHPOINT_READ: _WatchpointType.ValueType  # 0
    WATCHPOINT_WRITE: _WatchpointType.ValueType  # 1
    WATCHPOINT_BOTH: _WatchpointType.ValueType  # 2

class WatchpointType(_WatchpointType, metaclass=_WatchpointTypeEnumTypeWrapper): ...

WATCHPOINT_READ: WatchpointType.ValueType  # 0
WATCHPOINT_WRITE: WatchpointType.ValueType  # 1
WATCHPOINT_BOTH: WatchpointType.ValueType  # 2
Global___WatchpointType: _TypeAlias = WatchpointType  # noqa: Y015

class _RegisterRole:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RegisterRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RegisterRole.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REGISTER_ROLE_NONE: _RegisterRole.ValueType  # 0
    PROGRAM_COUNTER: _RegisterRole.ValueType  # 1
    STACK_POINTER: _RegisterRole.ValueType  # 2
    FLAGS: _RegisterRole.ValueType  # 3

class RegisterRole(_RegisterRole, metaclass=_RegisterRoleEnumTypeWrapper):
    """=== Family-agnostic CPU register model ===

    The coprocessor (and the host's own CPU) describe themselves so the
    protos, the server and the clients need not name a CPU family. The
    descriptor lists the registers in display order and the interrupt
    signals; the state carries values in the same order.
    """

REGISTER_ROLE_NONE: RegisterRole.ValueType  # 0
PROGRAM_COUNTER: RegisterRole.ValueType  # 1
STACK_POINTER: RegisterRole.ValueType  # 2
FLAGS: RegisterRole.ValueType  # 3
Global___RegisterRole: _TypeAlias = RegisterRole  # noqa: Y015

@_typing.final
class Empty(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Empty: _TypeAlias = Empty  # noqa: Y015

@_typing.final
class ExecutionState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IS_RUNNING_FIELD_NUMBER: _builtins.int
    CYCLE_COUNT_FIELD_NUMBER: _builtins.int
    HALT_REASON_FIELD_NUMBER: _builtins.int
    SEQUENCE_FIELD_NUMBER: _builtins.int
    is_running: _builtins.bool
    cycle_count: _builtins.int
    halt_reason: _builtins.str
    sequence: _builtins.int
    def __init__(
        self,
        *,
        is_running: _builtins.bool = ...,
        cycle_count: _builtins.int = ...,
        halt_reason: _builtins.str = ...,
        sequence: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cycle_count", b"cycle_count", "halt_reason", b"halt_reason", "is_running", b"is_running", "sequence", b"sequence"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecutionState: _TypeAlias = ExecutionState  # noqa: Y015

@_typing.final
class RunResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RunResponse: _TypeAlias = RunResponse  # noqa: Y015

@_typing.final
class StopResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    @_builtins.property
    def state(self) -> Global___ExecutionState: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        state: Global___ExecutionState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopResponse: _TypeAlias = StopResponse  # noqa: Y015

@_typing.final
class ResetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResetResponse: _TypeAlias = ResetResponse  # noqa: Y015

@_typing.final
class StepRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StepRequest: _TypeAlias = StepRequest  # noqa: Y015

@_typing.final
class StepResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    INSTRUCTIONS_EXECUTED_FIELD_NUMBER: _builtins.int
    CYCLES_EXECUTED_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    instructions_executed: _builtins.int
    cycles_executed: _builtins.int
    @_builtins.property
    def state(self) -> Global___ExecutionState: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        instructions_executed: _builtins.int = ...,
        cycles_executed: _builtins.int = ...,
        state: Global___ExecutionState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cycles_executed", b"cycles_executed", "error", b"error", "instructions_executed", b"instructions_executed", "state", b"state", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StepResponse: _TypeAlias = StepResponse  # noqa: Y015

@_typing.final
class WatchExecutionStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchExecutionStateRequest: _TypeAlias = WatchExecutionStateRequest  # noqa: Y015

@_typing.final
class ExecutionStateEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    WATCHPOINT_HIT_FIELD_NUMBER: _builtins.int
    reason: Global___StopReason.ValueType
    message: _builtins.str
    @_builtins.property
    def state(self) -> Global___ExecutionState: ...
    @_builtins.property
    def watchpoint_hit(self) -> Global___WatchpointHitInfo: ...
    def __init__(
        self,
        *,
        reason: Global___StopReason.ValueType = ...,
        state: Global___ExecutionState | None = ...,
        message: _builtins.str = ...,
        watchpoint_hit: Global___WatchpointHitInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state", "watchpoint_hit", b"watchpoint_hit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "reason", b"reason", "state", b"state", "watchpoint_hit", b"watchpoint_hit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecutionStateEvent: _TypeAlias = ExecutionStateEvent  # noqa: Y015

@_typing.final
class WatchpointHitInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WATCHPOINT_ID_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    IS_WRITE_FIELD_NUMBER: _builtins.int
    watchpoint_id: _builtins.int
    address: _builtins.int
    value: _builtins.int
    is_write: _builtins.bool
    def __init__(
        self,
        *,
        watchpoint_id: _builtins.int = ...,
        address: _builtins.int = ...,
        value: _builtins.int = ...,
        is_write: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "is_write", b"is_write", "value", b"value", "watchpoint_id", b"watchpoint_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchpointHitInfo: _TypeAlias = WatchpointHitInfo  # noqa: Y015

@_typing.final
class ReadMemoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    SIMULATED_PC_FIELD_NUMBER: _builtins.int
    address: _builtins.int
    length: _builtins.int
    simulated_pc: _builtins.int
    """Simulated PC for B+ shadow RAM routing. When set, memory access is
    routed as if code at this PC were executing. On Model B+ with shadow
    enabled, VDU driver code (0xC000-0xDFFF or paged RAM 0xA000-0xAFFF)
    sees shadow RAM at 0x3000-0x7FFF; other code sees main RAM.
    """
    def __init__(
        self,
        *,
        address: _builtins.int = ...,
        length: _builtins.int = ...,
        simulated_pc: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc", "simulated_pc", b"simulated_pc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc", "address", b"address", "length", b"length", "simulated_pc", b"simulated_pc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__simulated_pc: _TypeAlias = _typing.Literal["simulated_pc"]  # noqa: Y015
    _WhichOneofArgType__simulated_pc: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__simulated_pc) -> _WhichOneofReturnType__simulated_pc | None: ...

Global___ReadMemoryRequest: _TypeAlias = ReadMemoryRequest  # noqa: Y015

@_typing.final
class ReadMemoryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadMemoryResponse: _TypeAlias = ReadMemoryResponse  # noqa: Y015

@_typing.final
class PeekMemoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    SIMULATED_PC_FIELD_NUMBER: _builtins.int
    address: _builtins.int
    length: _builtins.int
    simulated_pc: _builtins.int
    """Simulated PC for B+ shadow RAM routing. See ReadMemoryRequest."""
    def __init__(
        self,
        *,
        address: _builtins.int = ...,
        length: _builtins.int = ...,
        simulated_pc: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc", "simulated_pc", b"simulated_pc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc", "address", b"address", "length", b"length", "simulated_pc", b"simulated_pc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__simulated_pc: _TypeAlias = _typing.Literal["simulated_pc"]  # noqa: Y015
    _WhichOneofArgType__simulated_pc: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__simulated_pc) -> _WhichOneofReturnType__simulated_pc | None: ...

Global___PeekMemoryRequest: _TypeAlias = PeekMemoryRequest  # noqa: Y015

@_typing.final
class PeekMemoryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PeekMemoryResponse: _TypeAlias = PeekMemoryResponse  # noqa: Y015

@_typing.final
class WriteMemoryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    SIMULATED_PC_FIELD_NUMBER: _builtins.int
    address: _builtins.int
    data: _builtins.bytes
    simulated_pc: _builtins.int
    """Simulated PC for B+ shadow RAM routing. See ReadMemoryRequest."""
    def __init__(
        self,
        *,
        address: _builtins.int = ...,
        data: _builtins.bytes = ...,
        simulated_pc: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc", "simulated_pc", b"simulated_pc"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc", "address", b"address", "data", b"data", "simulated_pc", b"simulated_pc"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__simulated_pc: _TypeAlias = _typing.Literal["simulated_pc"]  # noqa: Y015
    _WhichOneofArgType__simulated_pc: _TypeAlias = _typing.Literal["_simulated_pc", b"_simulated_pc"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__simulated_pc) -> _WhichOneofReturnType__simulated_pc | None: ...

Global___WriteMemoryRequest: _TypeAlias = WriteMemoryRequest  # noqa: Y015

@_typing.final
class WriteMemoryResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WriteMemoryResponse: _TypeAlias = WriteMemoryResponse  # noqa: Y015

@_typing.final
class AddBreakpointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    START_ADDRESS_FIELD_NUMBER: _builtins.int
    END_ADDRESS_FIELD_NUMBER: _builtins.int
    STOP_COUNTERPART_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    start_address: _builtins.int
    """start of range (inclusive)"""
    end_address: _builtins.int
    """end of range (exclusive); 0 means start+1 (single address)"""
    stop_counterpart: _builtins.bool
    condition: _builtins.str
    """optional condition expression (use `hits` for hit counts)"""
    enabled: _builtins.bool
    """absent means enabled (default true)"""
    def __init__(
        self,
        *,
        start_address: _builtins.int = ...,
        end_address: _builtins.int = ...,
        stop_counterpart: _builtins.bool = ...,
        condition: _builtins.str = ...,
        enabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "enabled", b"enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "condition", b"condition", "enabled", b"enabled", "end_address", b"end_address", "start_address", b"start_address", "stop_counterpart", b"stop_counterpart"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...

Global___AddBreakpointRequest: _TypeAlias = AddBreakpointRequest  # noqa: Y015

@_typing.final
class AddBreakpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    id: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddBreakpointResponse: _TypeAlias = AddBreakpointResponse  # noqa: Y015

@_typing.final
class RemoveBreakpointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveBreakpointRequest: _TypeAlias = RemoveBreakpointRequest  # noqa: Y015

@_typing.final
class RemoveBreakpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveBreakpointResponse: _TypeAlias = RemoveBreakpointResponse  # noqa: Y015

@_typing.final
class ListBreakpointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BREAKPOINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def breakpoints(self) -> _containers.RepeatedCompositeFieldContainer[Global___Breakpoint]: ...
    def __init__(
        self,
        *,
        breakpoints: _abc.Iterable[Global___Breakpoint] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["breakpoints", b"breakpoints"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListBreakpointsResponse: _TypeAlias = ListBreakpointsResponse  # noqa: Y015

@_typing.final
class Breakpoint(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    START_ADDRESS_FIELD_NUMBER: _builtins.int
    END_ADDRESS_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    STOP_COUNTERPART_FIELD_NUMBER: _builtins.int
    HIT_COUNT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    start_address: _builtins.int
    end_address: _builtins.int
    condition: _builtins.str
    stop_counterpart: _builtins.bool
    hit_count: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        start_address: _builtins.int = ...,
        end_address: _builtins.int = ...,
        condition: _builtins.str = ...,
        stop_counterpart: _builtins.bool = ...,
        hit_count: _builtins.int = ...,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["condition", b"condition", "enabled", b"enabled", "end_address", b"end_address", "hit_count", b"hit_count", "id", b"id", "start_address", b"start_address", "stop_counterpart", b"stop_counterpart"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Breakpoint: _TypeAlias = Breakpoint  # noqa: Y015

@_typing.final
class EnableBreakpointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnableBreakpointRequest: _TypeAlias = EnableBreakpointRequest  # noqa: Y015

@_typing.final
class EnableBreakpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnableBreakpointResponse: _TypeAlias = EnableBreakpointResponse  # noqa: Y015

@_typing.final
class ClearBreakpointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_REMOVED_FIELD_NUMBER: _builtins.int
    count_removed: _builtins.int
    def __init__(
        self,
        *,
        count_removed: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count_removed", b"count_removed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClearBreakpointsResponse: _TypeAlias = ClearBreakpointsResponse  # noqa: Y015

@_typing.final
class AddWatchpointRequest(_message.Message):
    """=== Watchpoints ==="""

    DESCRIPTOR: _descriptor.Descriptor

    START_ADDRESS_FIELD_NUMBER: _builtins.int
    END_ADDRESS_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    STOP_COUNTERPART_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    start_address: _builtins.int
    end_address: _builtins.int
    """exclusive [start, end)"""
    type: Global___WatchpointType.ValueType
    stop_counterpart: _builtins.bool
    condition: _builtins.str
    """optional condition expression (use `hits` for hit counts)"""
    enabled: _builtins.bool
    """absent means enabled (default true)"""
    def __init__(
        self,
        *,
        start_address: _builtins.int = ...,
        end_address: _builtins.int = ...,
        type: Global___WatchpointType.ValueType = ...,
        stop_counterpart: _builtins.bool = ...,
        condition: _builtins.str = ...,
        enabled: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "enabled", b"enabled"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_enabled", b"_enabled", "condition", b"condition", "enabled", b"enabled", "end_address", b"end_address", "start_address", b"start_address", "stop_counterpart", b"stop_counterpart", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__enabled: _TypeAlias = _typing.Literal["enabled"]  # noqa: Y015
    _WhichOneofArgType__enabled: _TypeAlias = _typing.Literal["_enabled", b"_enabled"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__enabled) -> _WhichOneofReturnType__enabled | None: ...

Global___AddWatchpointRequest: _TypeAlias = AddWatchpointRequest  # noqa: Y015

@_typing.final
class AddWatchpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    id: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddWatchpointResponse: _TypeAlias = AddWatchpointResponse  # noqa: Y015

@_typing.final
class RemoveWatchpointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveWatchpointRequest: _TypeAlias = RemoveWatchpointRequest  # noqa: Y015

@_typing.final
class RemoveWatchpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RemoveWatchpointResponse: _TypeAlias = RemoveWatchpointResponse  # noqa: Y015

@_typing.final
class ListWatchpointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WATCHPOINTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def watchpoints(self) -> _containers.RepeatedCompositeFieldContainer[Global___WatchpointInfo]: ...
    def __init__(
        self,
        *,
        watchpoints: _abc.Iterable[Global___WatchpointInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["watchpoints", b"watchpoints"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListWatchpointsResponse: _TypeAlias = ListWatchpointsResponse  # noqa: Y015

@_typing.final
class WatchpointInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    START_ADDRESS_FIELD_NUMBER: _builtins.int
    END_ADDRESS_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    CONDITION_FIELD_NUMBER: _builtins.int
    STOP_COUNTERPART_FIELD_NUMBER: _builtins.int
    HIT_COUNT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    start_address: _builtins.int
    end_address: _builtins.int
    type: Global___WatchpointType.ValueType
    condition: _builtins.str
    stop_counterpart: _builtins.bool
    hit_count: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        start_address: _builtins.int = ...,
        end_address: _builtins.int = ...,
        type: Global___WatchpointType.ValueType = ...,
        condition: _builtins.str = ...,
        stop_counterpart: _builtins.bool = ...,
        hit_count: _builtins.int = ...,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["condition", b"condition", "enabled", b"enabled", "end_address", b"end_address", "hit_count", b"hit_count", "id", b"id", "start_address", b"start_address", "stop_counterpart", b"stop_counterpart", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchpointInfo: _TypeAlias = WatchpointInfo  # noqa: Y015

@_typing.final
class EnableWatchpointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    id: _builtins.int
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        id: _builtins.int = ...,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "id", b"id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnableWatchpointRequest: _TypeAlias = EnableWatchpointRequest  # noqa: Y015

@_typing.final
class EnableWatchpointResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnableWatchpointResponse: _TypeAlias = EnableWatchpointResponse  # noqa: Y015

@_typing.final
class ClearWatchpointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNT_REMOVED_FIELD_NUMBER: _builtins.int
    count_removed: _builtins.int
    def __init__(
        self,
        *,
        count_removed: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count_removed", b"count_removed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ClearWatchpointsResponse: _TypeAlias = ClearWatchpointsResponse  # noqa: Y015

@_typing.final
class RegisterDescriptor(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    WIDTH_BITS_FIELD_NUMBER: _builtins.int
    ROLE_FIELD_NUMBER: _builtins.int
    FLAG_NAMES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """"A", "PC", "HL", "SP", "P" """
    width_bits: _builtins.int
    role: Global___RegisterRole.ValueType
    @_builtins.property
    def flag_names(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """for FLAGS: bit 0 first, "" for unused"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        width_bits: _builtins.int = ...,
        role: Global___RegisterRole.ValueType = ...,
        flag_names: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flag_names", b"flag_names", "name", b"name", "role", b"role", "width_bits", b"width_bits"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterDescriptor: _TypeAlias = RegisterDescriptor  # noqa: Y015

@_typing.final
class CpuDescriptor(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FAMILY_FIELD_NUMBER: _builtins.int
    ADDRESS_BITS_FIELD_NUMBER: _builtins.int
    LITTLE_ENDIAN_FIELD_NUMBER: _builtins.int
    REGISTERS_FIELD_NUMBER: _builtins.int
    SIGNALS_FIELD_NUMBER: _builtins.int
    family: _builtins.str
    """"6502", "z80", "6809", "ns32016", "80186" """
    address_bits: _builtins.int
    """16, 24, 32"""
    little_endian: _builtins.bool
    @_builtins.property
    def registers(self) -> _containers.RepeatedCompositeFieldContainer[Global___RegisterDescriptor]:
        """display order"""

    @_builtins.property
    def signals(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """interrupt line names, e.g. "IRQ", "NMI" """

    def __init__(
        self,
        *,
        family: _builtins.str = ...,
        address_bits: _builtins.int = ...,
        little_endian: _builtins.bool = ...,
        registers: _abc.Iterable[Global___RegisterDescriptor] | None = ...,
        signals: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address_bits", b"address_bits", "family", b"family", "little_endian", b"little_endian", "registers", b"registers", "signals", b"signals"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CpuDescriptor: _TypeAlias = CpuDescriptor  # noqa: Y015

@_typing.final
class RegisterValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    value: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisterValue: _TypeAlias = RegisterValue  # noqa: Y015

@_typing.final
class SignalState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    ASSERTED_FIELD_NUMBER: _builtins.int
    PENDING_FIELD_NUMBER: _builtins.int
    IN_HANDLER_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    asserted: _builtins.bool
    pending: _builtins.bool
    in_handler: _builtins.bool
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        asserted: _builtins.bool = ...,
        pending: _builtins.bool = ...,
        in_handler: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asserted", b"asserted", "in_handler", b"in_handler", "name", b"name", "pending", b"pending"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SignalState: _TypeAlias = SignalState  # noqa: Y015

@_typing.final
class CpuState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTERS_FIELD_NUMBER: _builtins.int
    SIGNALS_FIELD_NUMBER: _builtins.int
    CYCLE_COUNT_FIELD_NUMBER: _builtins.int
    cycle_count: _builtins.int
    @_builtins.property
    def registers(self) -> _containers.RepeatedCompositeFieldContainer[Global___RegisterValue]:
        """descriptor order (subset for SetCpuState)"""

    @_builtins.property
    def signals(self) -> _containers.RepeatedCompositeFieldContainer[Global___SignalState]:
        """descriptor.signals order"""

    def __init__(
        self,
        *,
        registers: _abc.Iterable[Global___RegisterValue] | None = ...,
        signals: _abc.Iterable[Global___SignalState] | None = ...,
        cycle_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cycle_count", b"cycle_count", "registers", b"registers", "signals", b"signals"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CpuState: _TypeAlias = CpuState  # noqa: Y015

@_typing.final
class GetMemoryRegionsRequest(_message.Message):
    """Memory region discovery and access messages"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetMemoryRegionsRequest: _TypeAlias = GetMemoryRegionsRequest  # noqa: Y015

@_typing.final
class MemoryRegionInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    BASE_ADDRESS_FIELD_NUMBER: _builtins.int
    SIZE_FIELD_NUMBER: _builtins.int
    READABLE_FIELD_NUMBER: _builtins.int
    WRITABLE_FIELD_NUMBER: _builtins.int
    HAS_SIDE_EFFECTS_FIELD_NUMBER: _builtins.int
    POPULATED_FIELD_NUMBER: _builtins.int
    ACTIVE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Region identifier (e.g., "main_ram", "bank_0")"""
    base_address: _builtins.int
    """Base address in CPU address space"""
    size: _builtins.int
    """Size in bytes"""
    readable: _builtins.bool
    """Can be read"""
    writable: _builtins.bool
    """Can be written"""
    has_side_effects: _builtins.bool
    """read() may differ from peek()"""
    populated: _builtins.bool
    """Has content (for optional banks)"""
    active: _builtins.bool
    """Currently selected (for banks)"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        base_address: _builtins.int = ...,
        size: _builtins.int = ...,
        readable: _builtins.bool = ...,
        writable: _builtins.bool = ...,
        has_side_effects: _builtins.bool = ...,
        populated: _builtins.bool = ...,
        active: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "base_address", b"base_address", "has_side_effects", b"has_side_effects", "name", b"name", "populated", b"populated", "readable", b"readable", "size", b"size", "writable", b"writable"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MemoryRegionInfo: _TypeAlias = MemoryRegionInfo  # noqa: Y015

@_typing.final
class GetMemoryRegionsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MACHINE_TYPE_FIELD_NUMBER: _builtins.int
    REGIONS_FIELD_NUMBER: _builtins.int
    machine_type: _builtins.str
    """"ModelB", "ModelBPlus", etc."""
    @_builtins.property
    def regions(self) -> _containers.RepeatedCompositeFieldContainer[Global___MemoryRegionInfo]: ...
    def __init__(
        self,
        *,
        machine_type: _builtins.str = ...,
        regions: _abc.Iterable[Global___MemoryRegionInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["machine_type", b"machine_type", "regions", b"regions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetMemoryRegionsResponse: _TypeAlias = GetMemoryRegionsResponse  # noqa: Y015

@_typing.final
class RegionAccessRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGION_NAME_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    LENGTH_FIELD_NUMBER: _builtins.int
    region_name: _builtins.str
    """Region to access"""
    address: _builtins.int
    """Absolute address (must be within region bounds)"""
    length: _builtins.int
    """Number of bytes to read"""
    def __init__(
        self,
        *,
        region_name: _builtins.str = ...,
        address: _builtins.int = ...,
        length: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "length", b"length", "region_name", b"region_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegionAccessRequest: _TypeAlias = RegionAccessRequest  # noqa: Y015

@_typing.final
class RegionAccessResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegionAccessResponse: _TypeAlias = RegionAccessResponse  # noqa: Y015

@_typing.final
class WriteRegionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGION_NAME_FIELD_NUMBER: _builtins.int
    ADDRESS_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    region_name: _builtins.str
    address: _builtins.int
    """Absolute address (must be within region bounds)"""
    data: _builtins.bytes
    def __init__(
        self,
        *,
        region_name: _builtins.str = ...,
        address: _builtins.int = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "data", b"data", "region_name", b"region_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WriteRegionRequest: _TypeAlias = WriteRegionRequest  # noqa: Y015

@_typing.final
class WriteRegionResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WriteRegionResponse: _TypeAlias = WriteRegionResponse  # noqa: Y015

@_typing.final
class GetSystemViaStateRequest(_message.Message):
    """=== VIA 6522 ==="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSystemViaStateRequest: _TypeAlias = GetSystemViaStateRequest  # noqa: Y015

@_typing.final
class GetUserViaStateRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetUserViaStateRequest: _TypeAlias = GetUserViaStateRequest  # noqa: Y015

@_typing.final
class ViaState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ORA_FIELD_NUMBER: _builtins.int
    ORB_FIELD_NUMBER: _builtins.int
    DDRA_FIELD_NUMBER: _builtins.int
    DDRB_FIELD_NUMBER: _builtins.int
    IRA_FIELD_NUMBER: _builtins.int
    IRB_FIELD_NUMBER: _builtins.int
    T1C_FIELD_NUMBER: _builtins.int
    T1L_FIELD_NUMBER: _builtins.int
    T2C_FIELD_NUMBER: _builtins.int
    T2L_FIELD_NUMBER: _builtins.int
    ACR_FIELD_NUMBER: _builtins.int
    PCR_FIELD_NUMBER: _builtins.int
    SR_FIELD_NUMBER: _builtins.int
    IFR_FIELD_NUMBER: _builtins.int
    IER_FIELD_NUMBER: _builtins.int
    T1_PENDING_FIELD_NUMBER: _builtins.int
    T2_PENDING_FIELD_NUMBER: _builtins.int
    T1_PB7_FIELD_NUMBER: _builtins.int
    CA1_FIELD_NUMBER: _builtins.int
    CA2_FIELD_NUMBER: _builtins.int
    CB1_FIELD_NUMBER: _builtins.int
    CB2_FIELD_NUMBER: _builtins.int
    ora: _builtins.int
    """Port state
    Output Register A
    """
    orb: _builtins.int
    """Output Register B"""
    ddra: _builtins.int
    """Data Direction Register A"""
    ddrb: _builtins.int
    """Data Direction Register B"""
    ira: _builtins.int
    """Input Register A (computed: port pins masked by DDR)"""
    irb: _builtins.int
    """Input Register B (computed: port pins masked by DDR)"""
    t1c: _builtins.int
    """Timer 1 (16-bit free-running or one-shot)
    Timer 1 counter (16-bit, effective value)
    """
    t1l: _builtins.int
    """Timer 1 latch (16-bit)"""
    t2c: _builtins.int
    """Timer 2 (16-bit one-shot or pulse counting)
    Timer 2 counter (16-bit, effective value)
    """
    t2l: _builtins.int
    """Timer 2 latch low (8-bit, high byte not latched)"""
    acr: _builtins.int
    """Control registers
    Auxiliary Control Register
    """
    pcr: _builtins.int
    """Peripheral Control Register"""
    sr: _builtins.int
    """Shift Register"""
    ifr: _builtins.int
    """Interrupt registers
    Interrupt Flag Register
    """
    ier: _builtins.int
    """Interrupt Enable Register"""
    t1_pending: _builtins.bool
    """Internal state (not directly memory-mapped)
    Timer 1 active and can generate IRQ
    """
    t2_pending: _builtins.bool
    """Timer 2 active and can generate IRQ"""
    t1_pb7: _builtins.int
    """PB7 output state from Timer 1 (when ACR bit 7 set)"""
    ca1: _builtins.bool
    """Control lines"""
    ca2: _builtins.bool
    cb1: _builtins.bool
    cb2: _builtins.bool
    def __init__(
        self,
        *,
        ora: _builtins.int = ...,
        orb: _builtins.int = ...,
        ddra: _builtins.int = ...,
        ddrb: _builtins.int = ...,
        ira: _builtins.int = ...,
        irb: _builtins.int = ...,
        t1c: _builtins.int = ...,
        t1l: _builtins.int = ...,
        t2c: _builtins.int = ...,
        t2l: _builtins.int = ...,
        acr: _builtins.int = ...,
        pcr: _builtins.int = ...,
        sr: _builtins.int = ...,
        ifr: _builtins.int = ...,
        ier: _builtins.int = ...,
        t1_pending: _builtins.bool = ...,
        t2_pending: _builtins.bool = ...,
        t1_pb7: _builtins.int = ...,
        ca1: _builtins.bool = ...,
        ca2: _builtins.bool = ...,
        cb1: _builtins.bool = ...,
        cb2: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acr", b"acr", "ca1", b"ca1", "ca2", b"ca2", "cb1", b"cb1", "cb2", b"cb2", "ddra", b"ddra", "ddrb", b"ddrb", "ier", b"ier", "ifr", b"ifr", "ira", b"ira", "irb", b"irb", "ora", b"ora", "orb", b"orb", "pcr", b"pcr", "sr", b"sr", "t1_pb7", b"t1_pb7", "t1_pending", b"t1_pending", "t1c", b"t1c", "t1l", b"t1l", "t2_pending", b"t2_pending", "t2c", b"t2c", "t2l", b"t2l"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ViaState: _TypeAlias = ViaState  # noqa: Y015

@_typing.final
class GetCrtcStateRequest(_message.Message):
    """=== CRTC 6845 ==="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetCrtcStateRequest: _TypeAlias = GetCrtcStateRequest  # noqa: Y015

@_typing.final
class CrtcState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTERS_FIELD_NUMBER: _builtins.int
    ADDRESS_REGISTER_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    ROW_FIELD_NUMBER: _builtins.int
    RASTER_FIELD_NUMBER: _builtins.int
    CHAR_ADDR_FIELD_NUMBER: _builtins.int
    SCREEN_START_FIELD_NUMBER: _builtins.int
    CURSOR_POSITION_FIELD_NUMBER: _builtins.int
    IN_HSYNC_FIELD_NUMBER: _builtins.int
    IN_VSYNC_FIELD_NUMBER: _builtins.int
    DISPLAY_ENABLED_FIELD_NUMBER: _builtins.int
    address_register: _builtins.int
    """Currently selected register (address register)"""
    column: _builtins.int
    """Internal timing counters
    Horizontal character position (0 to R0)
    """
    row: _builtins.int
    """Vertical character row (0 to R4)"""
    raster: _builtins.int
    """Scanline within character row (0 to R9)"""
    char_addr: _builtins.int
    """Current character address (MA0-MA13)"""
    screen_start: _builtins.int
    """Computed values (convenience)
    R12/R13: Display start address
    """
    cursor_position: _builtins.int
    """R14/R15: Cursor address"""
    in_hsync: _builtins.bool
    """Sync state"""
    in_vsync: _builtins.bool
    display_enabled: _builtins.bool
    @_builtins.property
    def registers(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """All 18 registers (R0-R17, includes write-only timing registers)"""

    def __init__(
        self,
        *,
        registers: _abc.Iterable[_builtins.int] | None = ...,
        address_register: _builtins.int = ...,
        column: _builtins.int = ...,
        row: _builtins.int = ...,
        raster: _builtins.int = ...,
        char_addr: _builtins.int = ...,
        screen_start: _builtins.int = ...,
        cursor_position: _builtins.int = ...,
        in_hsync: _builtins.bool = ...,
        in_vsync: _builtins.bool = ...,
        display_enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address_register", b"address_register", "char_addr", b"char_addr", "column", b"column", "cursor_position", b"cursor_position", "display_enabled", b"display_enabled", "in_hsync", b"in_hsync", "in_vsync", b"in_vsync", "raster", b"raster", "registers", b"registers", "row", b"row", "screen_start", b"screen_start"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CrtcState: _TypeAlias = CrtcState  # noqa: Y015

@_typing.final
class GetVideoUlaStateRequest(_message.Message):
    """=== Video ULA ==="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetVideoUlaStateRequest: _TypeAlias = GetVideoUlaStateRequest  # noqa: Y015

@_typing.final
class VideoUlaState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONTROL_FIELD_NUMBER: _builtins.int
    PALETTE_FIELD_NUMBER: _builtins.int
    control: _builtins.int
    """Control register (0xFE20)"""
    @_builtins.property
    def palette(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Palette (16 entries, logical colour -> physical colour)
        Written via 0xFE21, not directly readable by CPU
        """

    def __init__(
        self,
        *,
        control: _builtins.int = ...,
        palette: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control", b"control", "palette", b"palette"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VideoUlaState: _TypeAlias = VideoUlaState  # noqa: Y015

@_typing.final
class GetAddressableLatchStateRequest(_message.Message):
    """=== Addressable Latch (IC32 74LS259 on Model B) ==="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAddressableLatchStateRequest: _TypeAlias = GetAddressableLatchStateRequest  # noqa: Y015

@_typing.final
class AddressableLatchState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    SCREEN_BASE_FIELD_NUMBER: _builtins.int
    SOUND_WRITE_ENABLE_FIELD_NUMBER: _builtins.int
    SPEECH_READ_FIELD_NUMBER: _builtins.int
    SPEECH_WRITE_FIELD_NUMBER: _builtins.int
    KEYBOARD_WRITE_FIELD_NUMBER: _builtins.int
    CAPS_LOCK_LED_FIELD_NUMBER: _builtins.int
    SHIFT_LOCK_LED_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    """Raw 8-bit latch value"""
    screen_base: _builtins.int
    """Decoded fields for convenience
    Bits 4-5: Screen memory base address select
    """
    sound_write_enable: _builtins.bool
    """Bit 0: Active low"""
    speech_read: _builtins.bool
    """Bit 1: Active low"""
    speech_write: _builtins.bool
    """Bit 2: Active low"""
    keyboard_write: _builtins.bool
    """Bit 3: Active low"""
    caps_lock_led: _builtins.bool
    """Bit 6: Active low (accent grave on keyboard)"""
    shift_lock_led: _builtins.bool
    """Bit 7: Active low"""
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
        screen_base: _builtins.int = ...,
        sound_write_enable: _builtins.bool = ...,
        speech_read: _builtins.bool = ...,
        speech_write: _builtins.bool = ...,
        keyboard_write: _builtins.bool = ...,
        caps_lock_led: _builtins.bool = ...,
        shift_lock_led: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["caps_lock_led", b"caps_lock_led", "keyboard_write", b"keyboard_write", "screen_base", b"screen_base", "shift_lock_led", b"shift_lock_led", "sound_write_enable", b"sound_write_enable", "speech_read", b"speech_read", "speech_write", b"speech_write", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddressableLatchState: _TypeAlias = AddressableLatchState  # noqa: Y015

@_typing.final
class GetSoundGeneratorStateRequest(_message.Message):
    """=== Sound Generator SN76489 ===

    No parameters - always returns chip-native ordering
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSoundGeneratorStateRequest: _TypeAlias = GetSoundGeneratorStateRequest  # noqa: Y015

@_typing.final
class SoundGeneratorState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNELS_FIELD_NUMBER: _builtins.int
    LATCHED_REGISTER_FIELD_NUMBER: _builtins.int
    latched_register: _builtins.int
    """Currently latched register (0-7)"""
    @_builtins.property
    def channels(self) -> _containers.RepeatedCompositeFieldContainer[Global___SoundChannelState]: ...
    def __init__(
        self,
        *,
        channels: _abc.Iterable[Global___SoundChannelState] | None = ...,
        latched_register: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channels", b"channels", "latched_register", b"latched_register"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SoundGeneratorState: _TypeAlias = SoundGeneratorState  # noqa: Y015

@_typing.final
class SoundChannelState(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHANNEL_ID_FIELD_NUMBER: _builtins.int
    CHANNEL_NAME_FIELD_NUMBER: _builtins.int
    FREQUENCY_DIVIDER_FIELD_NUMBER: _builtins.int
    COUNTER_FIELD_NUMBER: _builtins.int
    OUTPUT_BIT_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    FREQUENCY_HZ_FIELD_NUMBER: _builtins.int
    NOISE_RATE_FIELD_NUMBER: _builtins.int
    WHITE_NOISE_FIELD_NUMBER: _builtins.int
    LFSR_STATE_FIELD_NUMBER: _builtins.int
    channel_id: _builtins.int
    """Channel index (depends on view)"""
    channel_name: _builtins.str
    """"Tone0"/"Noise" (native) or "0"/"1"/"2"/"3" (MOS)"""
    frequency_divider: _builtins.int
    """Tone channel state
    10-bit divider value (0-1023)
    """
    counter: _builtins.int
    """Current countdown value"""
    output_bit: _builtins.bool
    """Square wave polarity"""
    volume: _builtins.int
    """4-bit attenuation (0=max, 15=silent)"""
    frequency_hz: _builtins.float
    """Computed output frequency"""
    noise_rate: _builtins.int
    """Noise channel state (only valid for noise channel)
    2-bit rate select (0-3, where 3=Tone2)
    """
    white_noise: _builtins.bool
    """true=white noise, false=periodic"""
    lfsr_state: _builtins.int
    """15-bit LFSR state"""
    def __init__(
        self,
        *,
        channel_id: _builtins.int = ...,
        channel_name: _builtins.str = ...,
        frequency_divider: _builtins.int = ...,
        counter: _builtins.int = ...,
        output_bit: _builtins.bool = ...,
        volume: _builtins.int = ...,
        frequency_hz: _builtins.float = ...,
        noise_rate: _builtins.int = ...,
        white_noise: _builtins.bool = ...,
        lfsr_state: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["channel_id", b"channel_id", "channel_name", b"channel_name", "counter", b"counter", "frequency_divider", b"frequency_divider", "frequency_hz", b"frequency_hz", "lfsr_state", b"lfsr_state", "noise_rate", b"noise_rate", "output_bit", b"output_bit", "volume", b"volume", "white_noise", b"white_noise"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SoundChannelState: _TypeAlias = SoundChannelState  # noqa: Y015

@_typing.final
class GetTubeStateRequest(_message.Message):
    """=== Tube ULA ==="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTubeStateRequest: _TypeAlias = GetTubeStateRequest  # noqa: Y015

@_typing.final
class TubeState(_message.Message):
    """Complete Tube ULA state, modelling the real hardware's registers, FIFOs,
    latches, control flags, and interrupt outputs.

    The Tube ULA has four register pairs (R1-R4), each with a host-to-parasite
    (H-to-P) and parasite-to-host (P-to-H) direction. Each direction uses
    specific hardware: latches, FIFOs, or 2-byte shift registers.

    Status bits are provided from both host and parasite perspectives, since
    each side sees different views of the same registers.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CONTROL_FLAGS_FIELD_NUMBER: _builtins.int
    R1_H2P_FIELD_NUMBER: _builtins.int
    R1_P2H_FIELD_NUMBER: _builtins.int
    R2_H2P_FIELD_NUMBER: _builtins.int
    R2_P2H_FIELD_NUMBER: _builtins.int
    R3_H2P_FIELD_NUMBER: _builtins.int
    R3_P2H_FIELD_NUMBER: _builtins.int
    R4_H2P_FIELD_NUMBER: _builtins.int
    R4_P2H_FIELD_NUMBER: _builtins.int
    HOST_STATUS_FIELD_NUMBER: _builtins.int
    PARASITE_STATUS_FIELD_NUMBER: _builtins.int
    INTERRUPTS_FIELD_NUMBER: _builtins.int
    HOST_STRETCHED_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    COUNTERS_FIELD_NUMBER: _builtins.int
    TRACE_FIELD_NUMBER: _builtins.int
    TRACE_TOTAL_COUNT_FIELD_NUMBER: _builtins.int
    host_stretched: _builtins.bool
    """Bus stretching state."""
    enabled: _builtins.bool
    """Whether the Tube socket is populated (has a second processor attached)."""
    trace_total_count: _builtins.int
    @_builtins.property
    def control_flags(self) -> Global___TubeControlFlags:
        """Control flags (6 bits, written by host via R1 status register)."""

    @_builtins.property
    def r1_h2p(self) -> Global___TubeLatchState:
        """Register 1: H-to-P is a 1-byte latch; P-to-H is a 24-byte FIFO.
        Host-to-parasite latch
        """

    @_builtins.property
    def r1_p2h(self) -> Global___TubeFifo24State:
        """Parasite-to-host 24-byte FIFO"""

    @_builtins.property
    def r2_h2p(self) -> Global___TubeLatchState:
        """Register 2: 1-byte latch in each direction (no bus stretching)."""

    @_builtins.property
    def r2_p2h(self) -> Global___TubeLatchState: ...
    @_builtins.property
    def r3_h2p(self) -> Global___TubeReg3State:
        """Register 3: 2-byte shift register in each direction.
        Threshold mode (1 or 2 bytes) is selected by the V flag.
        """

    @_builtins.property
    def r3_p2h(self) -> Global___TubeReg3State: ...
    @_builtins.property
    def r4_h2p(self) -> Global___TubeLatchState:
        """Register 4: 1-byte latch in each direction."""

    @_builtins.property
    def r4_p2h(self) -> Global___TubeLatchState: ...
    @_builtins.property
    def host_status(self) -> Global___TubeHostStatus:
        """Status registers (as read by host at offsets 0/2/4/6)."""

    @_builtins.property
    def parasite_status(self) -> Global___TubeParasiteStatus:
        """Status registers (as read by parasite at offsets 0/2/4/6)."""

    @_builtins.property
    def interrupts(self) -> Global___TubeInterrupts:
        """Interrupt outputs."""

    @_builtins.property
    def counters(self) -> Global___TubeTransferCounters:
        """Per-register transfer counters (bytes transferred since reset)."""

    @_builtins.property
    def trace(self) -> _containers.RepeatedCompositeFieldContainer[Global___TubeTraceEntry]:
        """Protocol trace: last N register data events (ring buffer, oldest first).
        Each entry is a tag byte (register/direction/side) and a data byte.
        """

    def __init__(
        self,
        *,
        control_flags: Global___TubeControlFlags | None = ...,
        r1_h2p: Global___TubeLatchState | None = ...,
        r1_p2h: Global___TubeFifo24State | None = ...,
        r2_h2p: Global___TubeLatchState | None = ...,
        r2_p2h: Global___TubeLatchState | None = ...,
        r3_h2p: Global___TubeReg3State | None = ...,
        r3_p2h: Global___TubeReg3State | None = ...,
        r4_h2p: Global___TubeLatchState | None = ...,
        r4_p2h: Global___TubeLatchState | None = ...,
        host_status: Global___TubeHostStatus | None = ...,
        parasite_status: Global___TubeParasiteStatus | None = ...,
        interrupts: Global___TubeInterrupts | None = ...,
        host_stretched: _builtins.bool = ...,
        enabled: _builtins.bool = ...,
        counters: Global___TubeTransferCounters | None = ...,
        trace: _abc.Iterable[Global___TubeTraceEntry] | None = ...,
        trace_total_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["control_flags", b"control_flags", "counters", b"counters", "host_status", b"host_status", "interrupts", b"interrupts", "parasite_status", b"parasite_status", "r1_h2p", b"r1_h2p", "r1_p2h", b"r1_p2h", "r2_h2p", b"r2_h2p", "r2_p2h", b"r2_p2h", "r3_h2p", b"r3_h2p", "r3_p2h", b"r3_p2h", "r4_h2p", b"r4_h2p", "r4_p2h", b"r4_p2h"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_flags", b"control_flags", "counters", b"counters", "enabled", b"enabled", "host_status", b"host_status", "host_stretched", b"host_stretched", "interrupts", b"interrupts", "parasite_status", b"parasite_status", "r1_h2p", b"r1_h2p", "r1_p2h", b"r1_p2h", "r2_h2p", b"r2_h2p", "r2_p2h", b"r2_p2h", "r3_h2p", b"r3_h2p", "r3_p2h", b"r3_p2h", "r4_h2p", b"r4_h2p", "r4_p2h", b"r4_p2h", "trace", b"trace", "trace_total_count", b"trace_total_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeState: _TypeAlias = TubeState  # noqa: Y015

@_typing.final
class TubeTraceEntry(_message.Message):
    """A single entry in the Tube protocol trace ring buffer."""

    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    tag: _builtins.int
    """bits 7-4: register (1-4), bit 3: dir (0=H2P,1=P2H), bit 2: side (0=host,1=parasite)"""
    value: _builtins.int
    """data byte"""
    def __init__(
        self,
        *,
        tag: _builtins.int = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tag", b"tag", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeTraceEntry: _TypeAlias = TubeTraceEntry  # noqa: Y015

@_typing.final
class TubeTransferCounters(_message.Message):
    """Per-register byte transfer counters for Tube diagnostics.
    Each counter records total bytes written or read for a register direction.
    Stored in shared memory so both host and parasite can read all counters.
    """

    DESCRIPTOR: _descriptor.Descriptor

    R1_H2P_WRITES_FIELD_NUMBER: _builtins.int
    R1_H2P_READS_FIELD_NUMBER: _builtins.int
    R2_H2P_WRITES_FIELD_NUMBER: _builtins.int
    R2_H2P_READS_FIELD_NUMBER: _builtins.int
    R3_H2P_WRITES_FIELD_NUMBER: _builtins.int
    R3_H2P_READS_FIELD_NUMBER: _builtins.int
    R4_H2P_WRITES_FIELD_NUMBER: _builtins.int
    R4_H2P_READS_FIELD_NUMBER: _builtins.int
    R1_P2H_WRITES_FIELD_NUMBER: _builtins.int
    R1_P2H_READS_FIELD_NUMBER: _builtins.int
    R2_P2H_WRITES_FIELD_NUMBER: _builtins.int
    R2_P2H_READS_FIELD_NUMBER: _builtins.int
    R3_P2H_WRITES_FIELD_NUMBER: _builtins.int
    R3_P2H_READS_FIELD_NUMBER: _builtins.int
    R4_P2H_WRITES_FIELD_NUMBER: _builtins.int
    R4_P2H_READS_FIELD_NUMBER: _builtins.int
    r1_h2p_writes: _builtins.int
    """Host-to-parasite direction"""
    r1_h2p_reads: _builtins.int
    r2_h2p_writes: _builtins.int
    r2_h2p_reads: _builtins.int
    r3_h2p_writes: _builtins.int
    r3_h2p_reads: _builtins.int
    r4_h2p_writes: _builtins.int
    r4_h2p_reads: _builtins.int
    r1_p2h_writes: _builtins.int
    """Parasite-to-host direction"""
    r1_p2h_reads: _builtins.int
    r2_p2h_writes: _builtins.int
    r2_p2h_reads: _builtins.int
    r3_p2h_writes: _builtins.int
    r3_p2h_reads: _builtins.int
    r4_p2h_writes: _builtins.int
    r4_p2h_reads: _builtins.int
    def __init__(
        self,
        *,
        r1_h2p_writes: _builtins.int = ...,
        r1_h2p_reads: _builtins.int = ...,
        r2_h2p_writes: _builtins.int = ...,
        r2_h2p_reads: _builtins.int = ...,
        r3_h2p_writes: _builtins.int = ...,
        r3_h2p_reads: _builtins.int = ...,
        r4_h2p_writes: _builtins.int = ...,
        r4_h2p_reads: _builtins.int = ...,
        r1_p2h_writes: _builtins.int = ...,
        r1_p2h_reads: _builtins.int = ...,
        r2_p2h_writes: _builtins.int = ...,
        r2_p2h_reads: _builtins.int = ...,
        r3_p2h_writes: _builtins.int = ...,
        r3_p2h_reads: _builtins.int = ...,
        r4_p2h_writes: _builtins.int = ...,
        r4_p2h_reads: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["r1_h2p_reads", b"r1_h2p_reads", "r1_h2p_writes", b"r1_h2p_writes", "r1_p2h_reads", b"r1_p2h_reads", "r1_p2h_writes", b"r1_p2h_writes", "r2_h2p_reads", b"r2_h2p_reads", "r2_h2p_writes", b"r2_h2p_writes", "r2_p2h_reads", b"r2_p2h_reads", "r2_p2h_writes", b"r2_p2h_writes", "r3_h2p_reads", b"r3_h2p_reads", "r3_h2p_writes", b"r3_h2p_writes", "r3_p2h_reads", b"r3_p2h_reads", "r3_p2h_writes", b"r3_p2h_writes", "r4_h2p_reads", b"r4_h2p_reads", "r4_h2p_writes", b"r4_h2p_writes", "r4_p2h_reads", b"r4_p2h_reads", "r4_p2h_writes", b"r4_p2h_writes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeTransferCounters: _TypeAlias = TubeTransferCounters  # noqa: Y015

@_typing.final
class TubeControlFlags(_message.Message):
    """Tube ULA control flags (bits 0-5 of the control register)."""

    DESCRIPTOR: _descriptor.Descriptor

    Q_FIELD_NUMBER: _builtins.int
    I_FIELD_NUMBER: _builtins.int
    J_FIELD_NUMBER: _builtins.int
    M_FIELD_NUMBER: _builtins.int
    V_FIELD_NUMBER: _builtins.int
    P_FIELD_NUMBER: _builtins.int
    q: _builtins.bool
    """Bit 0: Enable HIRQ from R4"""
    i: _builtins.bool
    """Bit 1: Enable PIRQ from R1"""
    j: _builtins.bool
    """Bit 2: Enable PIRQ from R4"""
    m: _builtins.bool
    """Bit 3: Enable PNMI from R3"""
    v: _builtins.bool
    """Bit 4: Two-byte mode for R3"""
    p: _builtins.bool
    """Bit 5: Parasite reset"""
    def __init__(
        self,
        *,
        q: _builtins.bool = ...,
        i: _builtins.bool = ...,
        j: _builtins.bool = ...,
        m: _builtins.bool = ...,
        v: _builtins.bool = ...,
        p: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["i", b"i", "j", b"j", "m", b"m", "p", b"p", "q", b"q", "v", b"v"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeControlFlags: _TypeAlias = TubeControlFlags  # noqa: Y015

@_typing.final
class TubeLatchState(_message.Message):
    """Single-byte latch state (R1 H-to-P, R2 both directions, R4 both directions)."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUE_FIELD_NUMBER: _builtins.int
    DATA_AVAILABLE_FIELD_NUMBER: _builtins.int
    value: _builtins.int
    """Current data byte in the latch"""
    data_available: _builtins.bool
    """Latch contains unread data"""
    def __init__(
        self,
        *,
        value: _builtins.int = ...,
        data_available: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data_available", b"data_available", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeLatchState: _TypeAlias = TubeLatchState  # noqa: Y015

@_typing.final
class TubeFifo24State(_message.Message):
    """24-byte FIFO state (R1 P-to-H only)."""

    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    DATA_AVAILABLE_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    """Number of bytes currently in the FIFO (0-24)"""
    data: _builtins.bytes
    """FIFO contents in read order (head to tail)"""
    data_available: _builtins.bool
    """count > 0"""
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
        data: _builtins.bytes = ...,
        data_available: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "data", b"data", "data_available", b"data_available"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeFifo24State: _TypeAlias = TubeFifo24State  # noqa: Y015

@_typing.final
class TubeReg3State(_message.Message):
    """2-byte shift register state (R3 in each direction)."""

    DESCRIPTOR: _descriptor.Descriptor

    COUNT_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    PENDING_FIELD_NUMBER: _builtins.int
    THRESHOLD_FIELD_NUMBER: _builtins.int
    count: _builtins.int
    """Number of bytes in the register (0-2)"""
    data: _builtins.bytes
    """Register contents in read order (up to 2 bytes)"""
    pending: _builtins.bool
    """Complete transfer awaiting consumption"""
    threshold: _builtins.int
    """Current threshold (1 or 2, from V flag)"""
    def __init__(
        self,
        *,
        count: _builtins.int = ...,
        data: _builtins.bytes = ...,
        pending: _builtins.bool = ...,
        threshold: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["count", b"count", "data", b"data", "pending", b"pending", "threshold", b"threshold"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeReg3State: _TypeAlias = TubeReg3State  # noqa: Y015

@_typing.final
class TubeHostStatus(_message.Message):
    """Host-perspective status registers (what the host reads at offsets 0/2/4/6)."""

    DESCRIPTOR: _descriptor.Descriptor

    R1_STATUS_FIELD_NUMBER: _builtins.int
    R2_STATUS_FIELD_NUMBER: _builtins.int
    R3_STATUS_FIELD_NUMBER: _builtins.int
    R4_STATUS_FIELD_NUMBER: _builtins.int
    r1_status: _builtins.int
    """Offset 0: control flags + R1 status bits"""
    r2_status: _builtins.int
    """Offset 2: R2 status bits (bits 7:6 + 0x3F)"""
    r3_status: _builtins.int
    """Offset 4: R3 status bits"""
    r4_status: _builtins.int
    """Offset 6: R4 status bits"""
    def __init__(
        self,
        *,
        r1_status: _builtins.int = ...,
        r2_status: _builtins.int = ...,
        r3_status: _builtins.int = ...,
        r4_status: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["r1_status", b"r1_status", "r2_status", b"r2_status", "r3_status", b"r3_status", "r4_status", b"r4_status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeHostStatus: _TypeAlias = TubeHostStatus  # noqa: Y015

@_typing.final
class TubeParasiteStatus(_message.Message):
    """Parasite-perspective status registers (what the parasite reads at offsets 0/2/4/6)."""

    DESCRIPTOR: _descriptor.Descriptor

    R1_STATUS_FIELD_NUMBER: _builtins.int
    R2_STATUS_FIELD_NUMBER: _builtins.int
    R3_STATUS_FIELD_NUMBER: _builtins.int
    R4_STATUS_FIELD_NUMBER: _builtins.int
    r1_status: _builtins.int
    """Offset 0: control flags + R1 status bits"""
    r2_status: _builtins.int
    """Offset 2: R2 status bits"""
    r3_status: _builtins.int
    """Offset 4: R3 status bits (N F3 1 1 1 1 1 1; N at bit 7)"""
    r4_status: _builtins.int
    """Offset 6: R4 status bits"""
    def __init__(
        self,
        *,
        r1_status: _builtins.int = ...,
        r2_status: _builtins.int = ...,
        r3_status: _builtins.int = ...,
        r4_status: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["r1_status", b"r1_status", "r2_status", b"r2_status", "r3_status", b"r3_status", "r4_status", b"r4_status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeParasiteStatus: _TypeAlias = TubeParasiteStatus  # noqa: Y015

@_typing.final
class TubeInterrupts(_message.Message):
    """Tube interrupt output state."""

    DESCRIPTOR: _descriptor.Descriptor

    HIRQ_FIELD_NUMBER: _builtins.int
    PIRQ_FIELD_NUMBER: _builtins.int
    PNMI_LEVEL_FIELD_NUMBER: _builtins.int
    PNMI_EDGE_FIELD_NUMBER: _builtins.int
    hirq: _builtins.bool
    """Host IRQ: Q=1 AND R4 P-to-H has data"""
    pirq: _builtins.bool
    """Parasite IRQ: (I=1 AND R1 H-to-P has data) OR (J=1 AND R4 H-to-P has data)"""
    pnmi_level: _builtins.bool
    """PNMI level (combinational, before edge detection)"""
    pnmi_edge: _builtins.bool
    """PNMI latched rising edge"""
    def __init__(
        self,
        *,
        hirq: _builtins.bool = ...,
        pirq: _builtins.bool = ...,
        pnmi_level: _builtins.bool = ...,
        pnmi_edge: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hirq", b"hirq", "pirq", b"pirq", "pnmi_edge", b"pnmi_edge", "pnmi_level", b"pnmi_level"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TubeInterrupts: _TypeAlias = TubeInterrupts  # noqa: Y015