# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import disc_pb2 as _disc_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class DiscServiceStub:
    """Floppy disc drive management service.

    Provides insert/eject operations with safe eject support,
    drive status queries, and event streaming for multiple clients.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> DiscServiceAsyncStub: ...
    InsertDisc: _grpc.UnaryUnaryMultiCallable[_disc_pb2.InsertDiscRequest, _disc_pb2.InsertDiscResponse]
    """Insert a disc image from URL (file: scheme for local files).
    Fails if the drive already holds a disc: removing one is a separate,
    deliberate EjectDisc, so that it goes through the safe eject path.
    """
    EjectDisc: _grpc.UnaryUnaryMultiCallable[_disc_pb2.EjectDiscRequest, _disc_pb2.EjectDiscResponse]
    """Request disc ejection (non-blocking, safe eject by default).
    A safe eject waits as long as it takes for the drive to fall quiet;
    the server never gives up on its own. Giving up is the caller's
    decision, made by ejecting again with immediate set, or abandoned
    with CancelEject.
    """
    CancelEject: _grpc.UnaryUnaryMultiCallable[_disc_pb2.CancelEjectRequest, _disc_pb2.CancelEjectResponse]
    """Abandon a pending safe eject, leaving the disc in the drive"""
    GetDriveStatus: _grpc.UnaryUnaryMultiCallable[_disc_pb2.GetDriveStatusRequest, _disc_pb2.GetDriveStatusResponse]
    """Query status of all drives"""
    SubscribeDiscEvents: _grpc.UnaryStreamMultiCallable[_disc_pb2.SubscribeDiscEventsRequest, _disc_pb2.DiscEvent]
    """Stream drive events (insert, eject, motor changes)"""
    SetSpinUpDelay: _grpc.UnaryUnaryMultiCallable[_disc_pb2.SetSpinUpDelayRequest, _disc_pb2.SetSpinUpDelayResponse]
    """Configure motor spin-up delay (for automation scenarios)"""
    GetSpinUpDelay: _grpc.UnaryUnaryMultiCallable[_disc_pb2.GetSpinUpDelayRequest, _disc_pb2.GetSpinUpDelayResponse]
    """Query spin-up delay configuration"""
    ListAvailableControllers: _grpc.UnaryUnaryMultiCallable[_disc_pb2.ListAvailableControllersRequest, _disc_pb2.ListAvailableControllersResponse]
    """List available disc controller types (for machines with sockets)"""
    InstallDiscController: _grpc.UnaryUnaryMultiCallable[_disc_pb2.InstallDiscControllerRequest, _disc_pb2.InstallDiscControllerResponse]
    """Install a disc controller into the socket (machines with sockets only)"""

@_typing.type_check_only
class DiscServiceAsyncStub(DiscServiceStub):
    """Floppy disc drive management service.

    Provides insert/eject operations with safe eject support,
    drive status queries, and event streaming for multiple clients.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    InsertDisc: _aio.UnaryUnaryMultiCallable[_disc_pb2.InsertDiscRequest, _disc_pb2.InsertDiscResponse]  # type: ignore[assignment]
    """Insert a disc image from URL (file: scheme for local files).
    Fails if the drive already holds a disc: removing one is a separate,
    deliberate EjectDisc, so that it goes through the safe eject path.
    """
    EjectDisc: _aio.UnaryUnaryMultiCallable[_disc_pb2.EjectDiscRequest, _disc_pb2.EjectDiscResponse]  # type: ignore[assignment]
    """Request disc ejection (non-blocking, safe eject by default).
    A safe eject waits as long as it takes for the drive to fall quiet;
    the server never gives up on its own. Giving up is the caller's
    decision, made by ejecting again with immediate set, or abandoned
    with CancelEject.
    """
    CancelEject: _aio.UnaryUnaryMultiCallable[_disc_pb2.CancelEjectRequest, _disc_pb2.CancelEjectResponse]  # type: ignore[assignment]
    """Abandon a pending safe eject, leaving the disc in the drive"""
    GetDriveStatus: _aio.UnaryUnaryMultiCallable[_disc_pb2.GetDriveStatusRequest, _disc_pb2.GetDriveStatusResponse]  # type: ignore[assignment]
    """Query status of all drives"""
    SubscribeDiscEvents: _aio.UnaryStreamMultiCallable[_disc_pb2.SubscribeDiscEventsRequest, _disc_pb2.DiscEvent]  # type: ignore[assignment]
    """Stream drive events (insert, eject, motor changes)"""
    SetSpinUpDelay: _aio.UnaryUnaryMultiCallable[_disc_pb2.SetSpinUpDelayRequest, _disc_pb2.SetSpinUpDelayResponse]  # type: ignore[assignment]
    """Configure motor spin-up delay (for automation scenarios)"""
    GetSpinUpDelay: _aio.UnaryUnaryMultiCallable[_disc_pb2.GetSpinUpDelayRequest, _disc_pb2.GetSpinUpDelayResponse]  # type: ignore[assignment]
    """Query spin-up delay configuration"""
    ListAvailableControllers: _aio.UnaryUnaryMultiCallable[_disc_pb2.ListAvailableControllersRequest, _disc_pb2.ListAvailableControllersResponse]  # type: ignore[assignment]
    """List available disc controller types (for machines with sockets)"""
    InstallDiscController: _aio.UnaryUnaryMultiCallable[_disc_pb2.InstallDiscControllerRequest, _disc_pb2.InstallDiscControllerResponse]  # type: ignore[assignment]
    """Install a disc controller into the socket (machines with sockets only)"""

class DiscServiceServicer(metaclass=_abc_1.ABCMeta):
    """Floppy disc drive management service.

    Provides insert/eject operations with safe eject support,
    drive status queries, and event streaming for multiple clients.
    """

    @_abc_1.abstractmethod
    def InsertDisc(
        self,
        request: _disc_pb2.InsertDiscRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.InsertDiscResponse, _abc.Awaitable[_disc_pb2.InsertDiscResponse]]:
        """Insert a disc image from URL (file: scheme for local files).
        Fails if the drive already holds a disc: removing one is a separate,
        deliberate EjectDisc, so that it goes through the safe eject path.
        """

    @_abc_1.abstractmethod
    def EjectDisc(
        self,
        request: _disc_pb2.EjectDiscRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.EjectDiscResponse, _abc.Awaitable[_disc_pb2.EjectDiscResponse]]:
        """Request disc ejection (non-blocking, safe eject by default).
        A safe eject waits as long as it takes for the drive to fall quiet;
        the server never gives up on its own. Giving up is the caller's
        decision, made by ejecting again with immediate set, or abandoned
        with CancelEject.
        """

    @_abc_1.abstractmethod
    def CancelEject(
        self,
        request: _disc_pb2.CancelEjectRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.CancelEjectResponse, _abc.Awaitable[_disc_pb2.CancelEjectResponse]]:
        """Abandon a pending safe eject, leaving the disc in the drive"""

    @_abc_1.abstractmethod
    def GetDriveStatus(
        self,
        request: _disc_pb2.GetDriveStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.GetDriveStatusResponse, _abc.Awaitable[_disc_pb2.GetDriveStatusResponse]]:
        """Query status of all drives"""

    @_abc_1.abstractmethod
    def SubscribeDiscEvents(
        self,
        request: _disc_pb2.SubscribeDiscEventsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_disc_pb2.DiscEvent], _abc.AsyncIterator[_disc_pb2.DiscEvent]]:
        """Stream drive events (insert, eject, motor changes)"""

    @_abc_1.abstractmethod
    def SetSpinUpDelay(
        self,
        request: _disc_pb2.SetSpinUpDelayRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.SetSpinUpDelayResponse, _abc.Awaitable[_disc_pb2.SetSpinUpDelayResponse]]:
        """Configure motor spin-up delay (for automation scenarios)"""

    @_abc_1.abstractmethod
    def GetSpinUpDelay(
        self,
        request: _disc_pb2.GetSpinUpDelayRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.GetSpinUpDelayResponse, _abc.Awaitable[_disc_pb2.GetSpinUpDelayResponse]]:
        """Query spin-up delay configuration"""

    @_abc_1.abstractmethod
    def ListAvailableControllers(
        self,
        request: _disc_pb2.ListAvailableControllersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.ListAvailableControllersResponse, _abc.Awaitable[_disc_pb2.ListAvailableControllersResponse]]:
        """List available disc controller types (for machines with sockets)"""

    @_abc_1.abstractmethod
    def InstallDiscController(
        self,
        request: _disc_pb2.InstallDiscControllerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_disc_pb2.InstallDiscControllerResponse, _abc.Awaitable[_disc_pb2.InstallDiscControllerResponse]]:
        """Install a disc controller into the socket (machines with sockets only)"""

def add_DiscServiceServicer_to_server(servicer: DiscServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...