# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import econet_transport_pb2 as _econet_transport_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class EconetTransportServiceStub:
    """Transport-agnostic discovery service: tells clients which Econet
    transport extension is loaded on this server, and the instance id that
    addresses it. Lets a client decide whether to use AunService,
    PiconetService, or some future transport-specific service without having
    to probe via trial-and-error or read transport-specific fields off other
    RPCs.

    Modelled on PeripheralExtensionService.ListExtensions for
    peripheral extensions; this is the equivalent for econet
    transports.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> EconetTransportServiceAsyncStub: ...
    ListTransports: _grpc.UnaryUnaryMultiCallable[_econet_transport_pb2.ListTransportsRequest, _econet_transport_pb2.ListTransportsResponse]
    """List the econet transports loaded on this server, each with an
    "active" flag. For BBC Micro / Master / Master Compact machines at
    most one transport can be loaded (the server refuses more), and it is
    always reported active; future multi-ADLC machine types (e.g. Acorn
    Econet Bridge) may have several.
    """
    GetActiveTransport: _grpc.UnaryUnaryMultiCallable[_econet_transport_pb2.GetActiveTransportRequest, _econet_transport_pb2.GetActiveTransportResponse]
    """Convenience: return the single active transport, or an empty
    response if no transport is configured. Equivalent to filtering
    ListTransports for active=true and assuming at most one result.
    """

@_typing.type_check_only
class EconetTransportServiceAsyncStub(EconetTransportServiceStub):
    """Transport-agnostic discovery service: tells clients which Econet
    transport extension is loaded on this server, and the instance id that
    addresses it. Lets a client decide whether to use AunService,
    PiconetService, or some future transport-specific service without having
    to probe via trial-and-error or read transport-specific fields off other
    RPCs.

    Modelled on PeripheralExtensionService.ListExtensions for
    peripheral extensions; this is the equivalent for econet
    transports.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    ListTransports: _aio.UnaryUnaryMultiCallable[_econet_transport_pb2.ListTransportsRequest, _econet_transport_pb2.ListTransportsResponse]  # type: ignore[assignment]
    """List the econet transports loaded on this server, each with an
    "active" flag. For BBC Micro / Master / Master Compact machines at
    most one transport can be loaded (the server refuses more), and it is
    always reported active; future multi-ADLC machine types (e.g. Acorn
    Econet Bridge) may have several.
    """
    GetActiveTransport: _aio.UnaryUnaryMultiCallable[_econet_transport_pb2.GetActiveTransportRequest, _econet_transport_pb2.GetActiveTransportResponse]  # type: ignore[assignment]
    """Convenience: return the single active transport, or an empty
    response if no transport is configured. Equivalent to filtering
    ListTransports for active=true and assuming at most one result.
    """

class EconetTransportServiceServicer(metaclass=_abc_1.ABCMeta):
    """Transport-agnostic discovery service: tells clients which Econet
    transport extension is loaded on this server, and the instance id that
    addresses it. Lets a client decide whether to use AunService,
    PiconetService, or some future transport-specific service without having
    to probe via trial-and-error or read transport-specific fields off other
    RPCs.

    Modelled on PeripheralExtensionService.ListExtensions for
    peripheral extensions; this is the equivalent for econet
    transports.
    """

    @_abc_1.abstractmethod
    def ListTransports(
        self,
        request: _econet_transport_pb2.ListTransportsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_econet_transport_pb2.ListTransportsResponse, _abc.Awaitable[_econet_transport_pb2.ListTransportsResponse]]:
        """List the econet transports loaded on this server, each with an
        "active" flag. For BBC Micro / Master / Master Compact machines at
        most one transport can be loaded (the server refuses more), and it is
        always reported active; future multi-ADLC machine types (e.g. Acorn
        Econet Bridge) may have several.
        """

    @_abc_1.abstractmethod
    def GetActiveTransport(
        self,
        request: _econet_transport_pb2.GetActiveTransportRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_econet_transport_pb2.GetActiveTransportResponse, _abc.Awaitable[_econet_transport_pb2.GetActiveTransportResponse]]:
        """Convenience: return the single active transport, or an empty
        response if no transport is configured. Equivalent to filtering
        ListTransports for active=true and assuming at most one result.
        """

def add_EconetTransportServiceServicer_to_server(servicer: EconetTransportServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...