# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _EconetEventType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EconetEventTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EconetEventType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ECONET_EVENT_UNKNOWN: _EconetEventType.ValueType  # 0
    ECONET_EVENT_FRAME_SENT: _EconetEventType.ValueType  # 1
    ECONET_EVENT_FRAME_RECEIVED: _EconetEventType.ValueType  # 2
    ECONET_EVENT_HANDSHAKE_CHANGE: _EconetEventType.ValueType  # 3
    ECONET_EVENT_CONNECTION_CHANGE: _EconetEventType.ValueType  # 4

class EconetEventType(_EconetEventType, metaclass=_EconetEventTypeEnumTypeWrapper): ...

ECONET_EVENT_UNKNOWN: EconetEventType.ValueType  # 0
ECONET_EVENT_FRAME_SENT: EconetEventType.ValueType  # 1
ECONET_EVENT_FRAME_RECEIVED: EconetEventType.ValueType  # 2
ECONET_EVENT_HANDSHAKE_CHANGE: EconetEventType.ValueType  # 3
ECONET_EVENT_CONNECTION_CHANGE: EconetEventType.ValueType  # 4
Global___EconetEventType: _TypeAlias = EconetEventType  # noqa: Y015

@_typing.final
class GetEconetStatusRequest(_message.Message):
    """--- Status ---

    Empty - returns full status.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetEconetStatusRequest: _TypeAlias = GetEconetStatusRequest  # noqa: Y015

@_typing.final
class GetEconetStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HAS_ECONET_SOCKET_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    STATION_ID_FIELD_NUMBER: _builtins.int
    AUN_MODE_FIELD_NUMBER: _builtins.int
    CONNECTED_FIELD_NUMBER: _builtins.int
    ADLC_FIELD_NUMBER: _builtins.int
    HANDSHAKE_FIELD_NUMBER: _builtins.int
    TICK_COUNT_FIELD_NUMBER: _builtins.int
    CR1_0X82_WRITE_COUNT_FIELD_NUMBER: _builtins.int
    RX_FRAMES_RECEIVED_COUNT_FIELD_NUMBER: _builtins.int
    RX_BLOCKED_BY_RESET_COUNT_FIELD_NUMBER: _builtins.int
    SCOUT_ACK_GENERATED_COUNT_FIELD_NUMBER: _builtins.int
    TX_FRAMES_FROM_BEEB_COUNT_FIELD_NUMBER: _builtins.int
    UNEXPECTED_TX_RESET_COUNT_FIELD_NUMBER: _builtins.int
    TX_FROM_IDLE_COUNT_FIELD_NUMBER: _builtins.int
    MAX_HANDSHAKE_TIMER_SEEN_FIELD_NUMBER: _builtins.int
    WATCHDOG_TIMEOUT_COUNT_FIELD_NUMBER: _builtins.int
    SEND_STAGE_LOG_FIELD_NUMBER: _builtins.int
    TICKS_WITH_TIMER_ACTIVE_FIELD_NUMBER: _builtins.int
    READ_STRETCH_PARASITE_TICKS_FIELD_NUMBER: _builtins.int
    REQUIRES_REAL_TIME_FIELD_NUMBER: _builtins.int
    GATED_BY_SPEED_FIELD_NUMBER: _builtins.int
    has_econet_socket: _builtins.bool
    """True if this machine variant has an Econet socket (compile-time)."""
    enabled: _builtins.bool
    """True if Econet hardware is currently fitted (runtime)."""
    station_id: _builtins.int
    """Station number (1-254, 0 if disabled)."""
    aun_mode: _builtins.bool
    """True if AUN mode is active (FourWayHandshake present)."""
    connected: _builtins.bool
    """True if network link is active (e.g. UDP socket bound + cable
    not "unplugged" via AunService.SetConnected for AUN, or USB
    device responsive for Piconet). Set from the backend's generic
    is_connected().
    """
    tick_count: _builtins.int
    """Diagnostic: total tick_rising() calls since boot."""
    cr1_0x82_write_count: _builtins.int
    """Diagnostic: count of CR1=&82 writes (nmi_tx_complete indicator)."""
    rx_frames_received_count: _builtins.int
    """Diagnostic: count of frames received by ADLC from backend."""
    rx_blocked_by_reset_count: _builtins.int
    """Diagnostic: count of rx_process_byte calls blocked by RX_RESET."""
    scout_ack_generated_count: _builtins.int
    """Diagnostic: FourWayHandshake counters"""
    tx_frames_from_beeb_count: _builtins.int
    unexpected_tx_reset_count: _builtins.int
    tx_from_idle_count: _builtins.int
    max_handshake_timer_seen: _builtins.int
    watchdog_timeout_count: _builtins.int
    send_stage_log: _builtins.str
    ticks_with_timer_active: _builtins.int
    read_stretch_parasite_ticks: _builtins.int
    requires_real_time: _builtins.bool
    """Emulation-speed gating. requires_real_time is true when the active
    transport must run at real time (1x) -- it bridges to a real Econet line
    (Piconet). gated_by_speed is true when that transport is currently severed
    because the emulation speed is not 1x; the guest sees a dead carrier until
    the speed returns to 1x. See docs/networking.md ("Emulation speed and
    real-time peers").
    """
    gated_by_speed: _builtins.bool
    @_builtins.property
    def adlc(self) -> Global___AdlcStatus:
        """MC6854 ADLC register state (populated when enabled)."""

    @_builtins.property
    def handshake(self) -> Global___HandshakeStatus:
        """Four-way handshake state (populated when AUN mode active)."""

    def __init__(
        self,
        *,
        has_econet_socket: _builtins.bool = ...,
        enabled: _builtins.bool = ...,
        station_id: _builtins.int = ...,
        aun_mode: _builtins.bool = ...,
        connected: _builtins.bool = ...,
        adlc: Global___AdlcStatus | None = ...,
        handshake: Global___HandshakeStatus | None = ...,
        tick_count: _builtins.int = ...,
        cr1_0x82_write_count: _builtins.int = ...,
        rx_frames_received_count: _builtins.int = ...,
        rx_blocked_by_reset_count: _builtins.int = ...,
        scout_ack_generated_count: _builtins.int = ...,
        tx_frames_from_beeb_count: _builtins.int = ...,
        unexpected_tx_reset_count: _builtins.int = ...,
        tx_from_idle_count: _builtins.int = ...,
        max_handshake_timer_seen: _builtins.int = ...,
        watchdog_timeout_count: _builtins.int = ...,
        send_stage_log: _builtins.str = ...,
        ticks_with_timer_active: _builtins.int = ...,
        read_stretch_parasite_ticks: _builtins.int = ...,
        requires_real_time: _builtins.bool = ...,
        gated_by_speed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["adlc", b"adlc", "handshake", b"handshake"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["adlc", b"adlc", "aun_mode", b"aun_mode", "connected", b"connected", "cr1_0x82_write_count", b"cr1_0x82_write_count", "enabled", b"enabled", "gated_by_speed", b"gated_by_speed", "handshake", b"handshake", "has_econet_socket", b"has_econet_socket", "max_handshake_timer_seen", b"max_handshake_timer_seen", "read_stretch_parasite_ticks", b"read_stretch_parasite_ticks", "requires_real_time", b"requires_real_time", "rx_blocked_by_reset_count", b"rx_blocked_by_reset_count", "rx_frames_received_count", b"rx_frames_received_count", "scout_ack_generated_count", b"scout_ack_generated_count", "send_stage_log", b"send_stage_log", "station_id", b"station_id", "tick_count", b"tick_count", "ticks_with_timer_active", b"ticks_with_timer_active", "tx_frames_from_beeb_count", b"tx_frames_from_beeb_count", "tx_from_idle_count", b"tx_from_idle_count", "unexpected_tx_reset_count", b"unexpected_tx_reset_count", "watchdog_timeout_count", b"watchdog_timeout_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetEconetStatusResponse: _TypeAlias = GetEconetStatusResponse  # noqa: Y015

@_typing.final
class AdlcStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CR1_FIELD_NUMBER: _builtins.int
    CR2_FIELD_NUMBER: _builtins.int
    CR3_FIELD_NUMBER: _builtins.int
    CR4_FIELD_NUMBER: _builtins.int
    SR1_FIELD_NUMBER: _builtins.int
    SR2_FIELD_NUMBER: _builtins.int
    IRQ_OUTPUT_FIELD_NUMBER: _builtins.int
    TX_FIFO_EMPTY_FIELD_NUMBER: _builtins.int
    TX_FIFO_FULL_FIELD_NUMBER: _builtins.int
    RX_FIFO_EMPTY_FIELD_NUMBER: _builtins.int
    RX_FIFO_FULL_FIELD_NUMBER: _builtins.int
    TX_FRAME_FIELD_FIELD_NUMBER: _builtins.int
    RX_FRAME_FIELD_FIELD_NUMBER: _builtins.int
    PSE_LEVEL_FIELD_NUMBER: _builtins.int
    CTS_INPUT_FIELD_NUMBER: _builtins.int
    cr1: _builtins.int
    cr2: _builtins.int
    cr3: _builtins.int
    cr4: _builtins.int
    sr1: _builtins.int
    sr2: _builtins.int
    irq_output: _builtins.bool
    tx_fifo_empty: _builtins.bool
    tx_fifo_full: _builtins.bool
    rx_fifo_empty: _builtins.bool
    rx_fifo_full: _builtins.bool
    tx_frame_field: _builtins.str
    rx_frame_field: _builtins.str
    pse_level: _builtins.int
    cts_input: _builtins.bool
    def __init__(
        self,
        *,
        cr1: _builtins.int = ...,
        cr2: _builtins.int = ...,
        cr3: _builtins.int = ...,
        cr4: _builtins.int = ...,
        sr1: _builtins.int = ...,
        sr2: _builtins.int = ...,
        irq_output: _builtins.bool = ...,
        tx_fifo_empty: _builtins.bool = ...,
        tx_fifo_full: _builtins.bool = ...,
        rx_fifo_empty: _builtins.bool = ...,
        rx_fifo_full: _builtins.bool = ...,
        tx_frame_field: _builtins.str = ...,
        rx_frame_field: _builtins.str = ...,
        pse_level: _builtins.int = ...,
        cts_input: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cr1", b"cr1", "cr2", b"cr2", "cr3", b"cr3", "cr4", b"cr4", "cts_input", b"cts_input", "irq_output", b"irq_output", "pse_level", b"pse_level", "rx_fifo_empty", b"rx_fifo_empty", "rx_fifo_full", b"rx_fifo_full", "rx_frame_field", b"rx_frame_field", "sr1", b"sr1", "sr2", b"sr2", "tx_fifo_empty", b"tx_fifo_empty", "tx_fifo_full", b"tx_fifo_full", "tx_frame_field", b"tx_frame_field"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AdlcStatus: _TypeAlias = AdlcStatus  # noqa: Y015

@_typing.final
class HandshakeStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STAGE_FIELD_NUMBER: _builtins.int
    FLAG_FILL_ACTIVE_FIELD_NUMBER: _builtins.int
    FRAMES_HELD_FIELD_NUMBER: _builtins.int
    FRAMES_REDELIVERED_FIELD_NUMBER: _builtins.int
    FRAMES_EXPIRED_FIELD_NUMBER: _builtins.int
    FRAMES_DROPPED_FIELD_NUMBER: _builtins.int
    stage: _builtins.str
    flag_fill_active: _builtins.bool
    frames_held: _builtins.int
    """Inbound holding queue. Packets that arrive while the handshake is in a
    stage that cannot use them are held and re-offered rather than dropped;
    these counters make that visible, so a test or a diagnostic can assert
    on the mechanism rather than only on the outcome.

    frames_held      -- currently waiting for a stage that can accept them
    frames_redelivered -- held and later successfully delivered
    frames_expired   -- discarded after waiting too long
    frames_dropped   -- discarded because the queue was full; non-zero
                        means a peer is offering traffic faster than the
                        handshake can consume it
    """
    frames_redelivered: _builtins.int
    frames_expired: _builtins.int
    frames_dropped: _builtins.int
    def __init__(
        self,
        *,
        stage: _builtins.str = ...,
        flag_fill_active: _builtins.bool = ...,
        frames_held: _builtins.int = ...,
        frames_redelivered: _builtins.int = ...,
        frames_expired: _builtins.int = ...,
        frames_dropped: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["flag_fill_active", b"flag_fill_active", "frames_dropped", b"frames_dropped", "frames_expired", b"frames_expired", "frames_held", b"frames_held", "frames_redelivered", b"frames_redelivered", "stage", b"stage"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HandshakeStatus: _TypeAlias = HandshakeStatus  # noqa: Y015

@_typing.final
class EnableEconetRequest(_message.Message):
    """--- Enable/Disable ---"""

    DESCRIPTOR: _descriptor.Descriptor

    STATION_ID_FIELD_NUMBER: _builtins.int
    AUN_PORT_FIELD_NUMBER: _builtins.int
    NO_NETWORK_FIELD_NUMBER: _builtins.int
    station_id: _builtins.int
    """Station number (1-254)."""
    aun_port: _builtins.int
    """UDP port to bind for AUN networking.
    0 = use default (32768).
    Ignored when no_network is true.
    """
    no_network: _builtins.bool
    """If true, fit hardware with no network connection.
    Station ID is readable and ADLC is present, but DCD is high (no carrier).
    """
    def __init__(
        self,
        *,
        station_id: _builtins.int = ...,
        aun_port: _builtins.int = ...,
        no_network: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aun_port", b"aun_port", "no_network", b"no_network", "station_id", b"station_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnableEconetRequest: _TypeAlias = EnableEconetRequest  # noqa: Y015

@_typing.final
class EnableEconetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    ACTUAL_AUN_PORT_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    actual_aun_port: _builtins.int
    """Actual port bound (useful when 0/default was requested)."""
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        actual_aun_port: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actual_aun_port", b"actual_aun_port", "error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EnableEconetResponse: _TypeAlias = EnableEconetResponse  # noqa: Y015

@_typing.final
class DisableEconetRequest(_message.Message):
    """Empty."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DisableEconetRequest: _TypeAlias = DisableEconetRequest  # noqa: Y015

@_typing.final
class DisableEconetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DisableEconetResponse: _TypeAlias = DisableEconetResponse  # noqa: Y015

@_typing.final
class SetStationIdRequest(_message.Message):
    """--- Station ID ---"""

    DESCRIPTOR: _descriptor.Descriptor

    STATION_ID_FIELD_NUMBER: _builtins.int
    station_id: _builtins.int
    """Station number (1-254)."""
    def __init__(
        self,
        *,
        station_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["station_id", b"station_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetStationIdRequest: _TypeAlias = SetStationIdRequest  # noqa: Y015

@_typing.final
class SetStationIdResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetStationIdResponse: _TypeAlias = SetStationIdResponse  # noqa: Y015

@_typing.final
class WatchEconetStatusRequest(_message.Message):
    """--- Status Streaming ---"""

    DESCRIPTOR: _descriptor.Descriptor

    MIN_INTERVAL_MS_FIELD_NUMBER: _builtins.int
    min_interval_ms: _builtins.int
    """Minimum interval between status pushes in milliseconds (optional).
    Defaults to 50ms server-side. The server only pushes when status
    actually changes, so this caps the update rate rather than forcing
    periodic traffic.
    """
    def __init__(
        self,
        *,
        min_interval_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["min_interval_ms", b"min_interval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchEconetStatusRequest: _TypeAlias = WatchEconetStatusRequest  # noqa: Y015

@_typing.final
class SubscribeEconetEventsRequest(_message.Message):
    """--- Event Streaming ---

    Frames as they cross the transport, which is the view the guest's screen
    cannot give: what actually went out and what actually came back. Recorded
    just above the wire, so these are typed frames after the four-way handshake
    has done its translation.
    """

    DESCRIPTOR: _descriptor.Descriptor

    MAX_BATCH_FIELD_NUMBER: _builtins.int
    MIN_INTERVAL_MS_FIELD_NUMBER: _builtins.int
    max_batch: _builtins.int
    """Maximum events per message. Defaults to 64 server-side."""
    min_interval_ms: _builtins.int
    """Minimum interval between pushes in milliseconds. Defaults to 20ms.
    Caps the rate rather than forcing periodic traffic: a quiet network
    produces nothing.
    """
    def __init__(
        self,
        *,
        max_batch: _builtins.int = ...,
        min_interval_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_batch", b"max_batch", "min_interval_ms", b"min_interval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeEconetEventsRequest: _TypeAlias = SubscribeEconetEventsRequest  # noqa: Y015

@_typing.final
class EconetFrameInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FRAME_TYPE_FIELD_NUMBER: _builtins.int
    DEST_NET_FIELD_NUMBER: _builtins.int
    DEST_STN_FIELD_NUMBER: _builtins.int
    SRC_NET_FIELD_NUMBER: _builtins.int
    SRC_STN_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    CONTROL_BYTE_FIELD_NUMBER: _builtins.int
    DATA_LENGTH_FIELD_NUMBER: _builtins.int
    HANDLE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    frame_type: _builtins.str
    """"raw", "broadcast", "unicast", "ack", "nack", "immediate", "imm_reply"."""
    dest_net: _builtins.int
    dest_stn: _builtins.int
    src_net: _builtins.int
    src_stn: _builtins.int
    port: _builtins.int
    control_byte: _builtins.int
    data_length: _builtins.int
    """The payload's true size, which may exceed what `data` carries."""
    handle: _builtins.int
    """The AUN transaction handle. A peer retransmitting an unacknowledged
    frame reuses its handle, so two frames with the same handle are the
    same transmission rather than two transactions carrying like bytes.
    Zero for transports with no such concept, and on the send path.
    """
    data: _builtins.bytes
    """The leading bytes of the payload, truncated to keep the event stream
    from becoming a packet capture. Compare with data_length to tell
    whether anything was dropped.
    """
    def __init__(
        self,
        *,
        frame_type: _builtins.str = ...,
        dest_net: _builtins.int = ...,
        dest_stn: _builtins.int = ...,
        src_net: _builtins.int = ...,
        src_stn: _builtins.int = ...,
        port: _builtins.int = ...,
        control_byte: _builtins.int = ...,
        data_length: _builtins.int = ...,
        handle: _builtins.int = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_byte", b"control_byte", "data", b"data", "data_length", b"data_length", "dest_net", b"dest_net", "dest_stn", b"dest_stn", "frame_type", b"frame_type", "handle", b"handle", "port", b"port", "src_net", b"src_net", "src_stn", b"src_stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EconetFrameInfo: _TypeAlias = EconetFrameInfo  # noqa: Y015

@_typing.final
class EconetEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    SEQUENCE_FIELD_NUMBER: _builtins.int
    FRAME_FIELD_NUMBER: _builtins.int
    CONNECTED_FIELD_NUMBER: _builtins.int
    type: Global___EconetEventType.ValueType
    sequence: _builtins.int
    """Monotonic, assigned when the event was recorded. Gaps mean a subscriber
    fell further behind than the server's ring buffer reaches, and events
    were lost -- reported rather than hidden, so a diagnosis is never built
    on a stream with silent holes in it.
    """
    connected: _builtins.bool
    """Set for CONNECTION_CHANGE."""
    @_builtins.property
    def frame(self) -> Global___EconetFrameInfo:
        """Set for FRAME_SENT and FRAME_RECEIVED."""

    def __init__(
        self,
        *,
        type: Global___EconetEventType.ValueType = ...,
        sequence: _builtins.int = ...,
        frame: Global___EconetFrameInfo | None = ...,
        connected: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["frame", b"frame"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connected", b"connected", "frame", b"frame", "sequence", b"sequence", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EconetEvent: _TypeAlias = EconetEvent  # noqa: Y015