# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SubscribeViewRequest(_message.Message):
    """--- View envelope ---"""

    DESCRIPTOR: _descriptor.Descriptor

    EXTENSION_ID_FIELD_NUMBER: _builtins.int
    extension_id: _builtins.str
    """Opaque, server-assigned extension instance id (matches
    PeripheralExtensionService's ExtensionInfo.id and
    EconetTransportService.EconetTransport.id). It is typically a
    UUID; do not assume any relationship to the manifest name.
    Clients must discover it via the relevant listing RPC
    (ListExtensions / ListTransports) rather than hardcoding names,
    so new extensions surface in frontends with no client changes.
    """
    def __init__(
        self,
        *,
        extension_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extension_id", b"extension_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeViewRequest: _TypeAlias = SubscribeViewRequest  # noqa: Y015

@_typing.final
class View(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXTENSION_ID_FIELD_NUMBER: _builtins.int
    VIEW_REVISION_FIELD_NUMBER: _builtins.int
    ROOT_FIELD_NUMBER: _builtins.int
    extension_id: _builtins.str
    """Echoed back so clients can route updates by extension if they
    multiplex several streams onto one handler.
    """
    view_revision: _builtins.int
    """Monotonic per-extension counter, bumped before each push. Clients
    must echo this in DispatchRequest so the server can reject stale
    events that target a control the server has already replaced.
    """
    @_builtins.property
    def root(self) -> Global___Control:
        """Root of the control tree. By convention this is a Group, but any
        single Control is valid (e.g. a single Label for an extension that
        has nothing interactive to expose).
        """

    def __init__(
        self,
        *,
        extension_id: _builtins.str = ...,
        view_revision: _builtins.int = ...,
        root: Global___Control | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["root", b"root"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extension_id", b"extension_id", "root", b"root", "view_revision", b"view_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___View: _TypeAlias = View  # noqa: Y015

@_typing.final
class Control(_message.Message):
    """--- Controls ---

    Eleven primitives, deliberately small. Together with nested Groups and
    ModalEditors they cover the panels we have today (Piconet, AUN) and
    are expected to cover ~90% of any future extension. Stretching the
    alphabet should hurt slightly each time -- that's the forcing function
    for keeping it small. The newest two, EditableList and FileReference,
    each earn their place by replacing a dozen lower-level controls that
    built the #142 AUN panel: see docs/discussion/extension-ui-architecture.md
    "Vocabulary extension (2026-10-01)".
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TOOLTIP_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    INDICATOR_FIELD_NUMBER: _builtins.int
    TOGGLE_FIELD_NUMBER: _builtins.int
    BUTTON_FIELD_NUMBER: _builtins.int
    CHOICE_FIELD_NUMBER: _builtins.int
    TEXT_INPUT_FIELD_NUMBER: _builtins.int
    GROUP_FIELD_NUMBER: _builtins.int
    MODAL_EDITOR_FIELD_NUMBER: _builtins.int
    EDITABLE_CHOICE_FIELD_NUMBER: _builtins.int
    EDITABLE_LIST_FIELD_NUMBER: _builtins.int
    FILE_REFERENCE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """Stable id assigned by the extension. Used by Dispatch to address
    the control and by clients to patch widgets in place across pushes
    (instead of rebuilding the panel each time).
    """
    tooltip: _builtins.str
    """Optional hover text. The platform-specific surfacing varies
    (macOS uses the SwiftUI .help() modifier, web maps to the
    `title` attribute, others may use a tooltip helper from their
    toolkit). Use it for verbose / diagnostic detail that would
    clutter the panel if rendered inline -- e.g. a disc geometry
    breakdown on a Capacity Label, a memory-mapped address range
    on an adapter's name Label. Empty / absent means no tooltip.
    """
    @_builtins.property
    def label(self) -> Global___Label: ...
    @_builtins.property
    def indicator(self) -> Global___Indicator: ...
    @_builtins.property
    def toggle(self) -> Global___Toggle: ...
    @_builtins.property
    def button(self) -> Global___Button: ...
    @_builtins.property
    def choice(self) -> Global___Choice: ...
    @_builtins.property
    def text_input(self) -> Global___TextInput: ...
    @_builtins.property
    def group(self) -> Global___Group: ...
    @_builtins.property
    def modal_editor(self) -> Global___ModalEditor: ...
    @_builtins.property
    def editable_choice(self) -> Global___EditableChoice: ...
    @_builtins.property
    def editable_list(self) -> Global___EditableList: ...
    @_builtins.property
    def file_reference(self) -> Global___FileReference: ...
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        tooltip: _builtins.str = ...,
        label: Global___Label | None = ...,
        indicator: Global___Indicator | None = ...,
        toggle: Global___Toggle | None = ...,
        button: Global___Button | None = ...,
        choice: Global___Choice | None = ...,
        text_input: Global___TextInput | None = ...,
        group: Global___Group | None = ...,
        modal_editor: Global___ModalEditor | None = ...,
        editable_choice: Global___EditableChoice | None = ...,
        editable_list: Global___EditableList | None = ...,
        file_reference: Global___FileReference | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["button", b"button", "choice", b"choice", "control", b"control", "editable_choice", b"editable_choice", "editable_list", b"editable_list", "file_reference", b"file_reference", "group", b"group", "indicator", b"indicator", "label", b"label", "modal_editor", b"modal_editor", "text_input", b"text_input", "toggle", b"toggle"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["button", b"button", "choice", b"choice", "control", b"control", "editable_choice", b"editable_choice", "editable_list", b"editable_list", "file_reference", b"file_reference", "group", b"group", "id", b"id", "indicator", b"indicator", "label", b"label", "modal_editor", b"modal_editor", "text_input", b"text_input", "toggle", b"toggle", "tooltip", b"tooltip"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_control: _TypeAlias = _typing.Literal["label", "indicator", "toggle", "button", "choice", "text_input", "group", "modal_editor", "editable_choice", "editable_list", "file_reference"]  # noqa: Y015
    _WhichOneofArgType_control: _TypeAlias = _typing.Literal["control", b"control"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_control) -> _WhichOneofReturnType_control | None: ...

Global___Control: _TypeAlias = Control  # noqa: Y015

@_typing.final
class Label(_message.Message):
    """Read-only text. Frontends render as a static label.

    secondary_text is a renderer hint for a short, lower-emphasis
    caption shown alongside the primary text -- typically right-
    aligned or in a muted style. Use it for provenance / status / size
    metadata that's logically attached to the primary line but should
    not be confused with it. Empty / absent means "no secondary
    caption", which is the default. Frontends that don't have a
    natural muted-text style fall back to rendering the two strings
    joined with whitespace.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    SECONDARY_TEXT_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    secondary_text: _builtins.str
    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        secondary_text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["secondary_text", b"secondary_text", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Label: _TypeAlias = Label  # noqa: Y015

@_typing.final
class Indicator(_message.Message):
    """Read-only state badge. The 'state' field is semantic -- the frontend
    chooses how to render it (colour, icon, accessibility hint) per its
    platform conventions. The 'text' field is a short caption shown next
    to the indicator.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _State:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _StateEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[Indicator._State.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: Indicator._State.ValueType  # 0
        OK: Indicator._State.ValueType  # 1
        WARN: Indicator._State.ValueType  # 2
        ERROR: Indicator._State.ValueType  # 3

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    UNKNOWN: Indicator.State.ValueType  # 0
    OK: Indicator.State.ValueType  # 1
    WARN: Indicator.State.ValueType  # 2
    ERROR: Indicator.State.ValueType  # 3

    STATE_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    state: Global___Indicator.State.ValueType
    text: _builtins.str
    def __init__(
        self,
        *,
        state: Global___Indicator.State.ValueType = ...,
        text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Indicator: _TypeAlias = Indicator  # noqa: Y015

@_typing.final
class Toggle(_message.Message):
    """Bool. Dispatch payload: bool_value."""

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    value: _builtins.bool
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        value: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Toggle: _TypeAlias = Toggle  # noqa: Y015

@_typing.final
class Button(_message.Message):
    """Fire-only command. Dispatch payload: none (oneof unset)."""

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    enabled: _builtins.bool
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Button: _TypeAlias = Button  # noqa: Y015

@_typing.final
class Choice(_message.Message):
    """Enum with a fixed set of options. Dispatch payload: index_value
    (zero-based index into 'options').
    """

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    SELECTED_INDEX_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    selected_index: _builtins.int
    @_builtins.property
    def options(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        options: _abc.Iterable[_builtins.str] | None = ...,
        selected_index: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "options", b"options", "selected_index", b"selected_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Choice: _TypeAlias = Choice  # noqa: Y015

@_typing.final
class TextInput(_message.Message):
    """Free-form string. Dispatch payload: string_value. Frontends decide
    dispatch timing (per-keystroke vs on-blur); the protocol does not
    constrain that.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    PLACEHOLDER_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    value: _builtins.str
    placeholder: _builtins.str
    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        value: _builtins.str = ...,
        placeholder: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "placeholder", b"placeholder", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TextInput: _TypeAlias = TextInput  # noqa: Y015

@_typing.final
class EditableChoice(_message.Message):
    """Open-ended choice: pick from a fixed list of options OR type a custom
    value. The semantic mirror of Choice (closed: must be one of the
    options); EditableChoice is open. Renderers map this to the platform's
    idiomatic combobox widget -- macOS NSComboBox, GTK GtkComboBox with
    has_entry, HTML <input list="..."> with a <datalist>, etc.

    Dispatch payload: string_value. The string is whatever the user
    committed -- whether they typed it freely or picked it from the
    dropdown is not visible on the wire, and shouldn't matter to the
    extension.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    PLACEHOLDER_FIELD_NUMBER: _builtins.int
    OPTIONS_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    value: _builtins.str
    """current text content"""
    placeholder: _builtins.str
    @_builtins.property
    def options(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """dropdown content; may be empty"""

    def __init__(
        self,
        *,
        label: _builtins.str = ...,
        value: _builtins.str = ...,
        placeholder: _builtins.str = ...,
        options: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "options", b"options", "placeholder", b"placeholder", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditableChoice: _TypeAlias = EditableChoice  # noqa: Y015

@_typing.final
class Group(_message.Message):
    """Structural primitive: an ordered sequence of child Controls with an
    optional label. Renderers display children in their toolkit's natural
    vertical flow; nested Groups produce nested sections.
    """

    DESCRIPTOR: _descriptor.Descriptor

    LABEL_FIELD_NUMBER: _builtins.int
    CONTROLS_FIELD_NUMBER: _builtins.int
    label: _builtins.str
    """Absent (oneof not set) means an unlabelled group; renderers should
    not render a heading. Present-but-empty means an empty heading,
    which is usually a mistake -- prefer to omit the field entirely.
    """
    @_builtins.property
    def controls(self) -> _containers.RepeatedCompositeFieldContainer[Global___Control]: ...
    def __init__(
        self,
        *,
        label: _builtins.str | None = ...,
        controls: _abc.Iterable[Global___Control] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_label", b"_label", "label", b"label"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_label", b"_label", "controls", b"controls", "label", b"label"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__label: _TypeAlias = _typing.Literal["label"]  # noqa: Y015
    _WhichOneofArgType__label: _TypeAlias = _typing.Literal["_label", b"_label"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__label) -> _WhichOneofReturnType__label | None: ...

Global___Group: _TypeAlias = Group  # noqa: Y015

@_typing.final
class ModalEditor(_message.Message):
    """Structural primitive for deferred, atomic editing: an always-visible
    anchor (typically a Label showing the current value) plus an editor
    tree that is revealed on user activation, with a single atomic commit
    event delivered when the user confirms. "Modal" here names the
    interaction model -- a separate scope with deferred commit -- not the
    HIG-strict input-blocking sense; a macOS popover, a Win32 flyout, a
    TUI sub-panel, and an HTML <dialog> all satisfy this model.

    Commit semantics are client-buffered: while the editor tree is open,
    its sub-controls hold local frontend state and do NOT dispatch per-
    keystroke / per-selection events. On confirm the frontend bundles all
    sub-control values into a single EditorCommit payload. Cancel is a
    pure client-side discard -- the server never hears about it, because
    it has no state to roll back.

    The server gates editability via the 'editable' bool: when false,
    frontends render the anchor as a plain read-only display with no edit
    affordance. Symmetric to Button.enabled.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _CommitRole:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CommitRoleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ModalEditor._CommitRole.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        SAVE: ModalEditor._CommitRole.ValueType  # 0
        """default: committing edits to an existing value"""
        ADD: ModalEditor._CommitRole.ValueType  # 1
        """creating a new entity (Add peer, Add disc, etc.)"""

    class CommitRole(_CommitRole, metaclass=_CommitRoleEnumTypeWrapper):
        """Semantic role of the commit action. Frontends pick platform-
        idiomatic wording and styling: macOS "Save"/"Add", iOS "Done"/
        "Add", Windows "OK"/"Add", GNOME "Apply"/"Add". Keeping this
        semantic rather than a string lets every frontend localise and
        match its own conventions; string labels would leak one
        platform's wording into the vocabulary.
        """

    SAVE: ModalEditor.CommitRole.ValueType  # 0
    """default: committing edits to an existing value"""
    ADD: ModalEditor.CommitRole.ValueType  # 1
    """creating a new entity (Add peer, Add disc, etc.)"""

    ANCHOR_FIELD_NUMBER: _builtins.int
    EDITOR_FIELD_NUMBER: _builtins.int
    EDITABLE_FIELD_NUMBER: _builtins.int
    COMMIT_ROLE_FIELD_NUMBER: _builtins.int
    SHOW_CANCEL_FIELD_NUMBER: _builtins.int
    editable: _builtins.bool
    """False means "display only": the anchor renders as a read-only
    widget with no affordance to open the editor. True means the
    frontend attaches an edit affordance appropriate to its platform
    (pencil button, click-to-edit, etc.).
    """
    commit_role: Global___ModalEditor.CommitRole.ValueType
    show_cancel: _builtins.bool
    """When true, the renderer includes an explicit Cancel affordance
    in addition to any platform-default dismiss (escape / click-
    outside). macOS popovers dismiss natively, so explicit Cancel
    is optional; full-window dialogs on other platforms may want it
    regardless and can synthesise one. Default false means "trust
    the frontend's default dismiss".
    """
    @_builtins.property
    def anchor(self) -> Global___Control:
        """Always-visible display of the current value. Typically a Label;
        any leaf Control type is valid if you want a richer anchor
        (e.g. an Indicator showing status alongside a value).
        """

    @_builtins.property
    def editor(self) -> Global___Control:
        """The editor tree revealed on activation. By convention this is a
        Group whose children are TextInput / Choice / Toggle leaves, but
        any Control is accepted. Nested ModalEditors inside the editor
        tree are discouraged (reason about the interaction first).
        """

    def __init__(
        self,
        *,
        anchor: Global___Control | None = ...,
        editor: Global___Control | None = ...,
        editable: _builtins.bool = ...,
        commit_role: Global___ModalEditor.CommitRole.ValueType = ...,
        show_cancel: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["anchor", b"anchor", "editor", b"editor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["anchor", b"anchor", "commit_role", b"commit_role", "editable", b"editable", "editor", b"editor", "show_cancel", b"show_cancel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ModalEditor: _TypeAlias = ModalEditor  # noqa: Y015

@_typing.final
class EditableList(_message.Message):
    """Collection primitive: a titled list of records with the platform's
    standard add / remove / edit affordances, replacing the Label + Button +
    ModalEditor-per-row shape the first collection panel (#142 AUN) was built
    from. Each item carries its own prefilled editor and its own per-item
    actions, so one EditableList expresses a whole editable table. All user
    actions on the list arrive through one dispatch payload,
    EditableListEvent, keyed by the item's stable id.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TITLE_FIELD_NUMBER: _builtins.int
    ITEMS_FIELD_NUMBER: _builtins.int
    CAN_ADD_FIELD_NUMBER: _builtins.int
    ADD_EDITOR_FIELD_NUMBER: _builtins.int
    EMPTY_TEXT_FIELD_NUMBER: _builtins.int
    title: _builtins.str
    """"Peers", "Subnet rules" """
    can_add: _builtins.bool
    """shows the platform's "+" affordance"""
    empty_text: _builtins.str
    """shown when items is empty: "No peers" """
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___EditableListItem]: ...
    @_builtins.property
    def add_editor(self) -> Global___Control:
        """The editor Control for a NEW item (fields only; the renderer supplies
        the commit UI). By convention a Group of TextInput / Choice leaves,
        mirroring a ModalEditor's editor tree. Committed as an ADD event.
        """

    def __init__(
        self,
        *,
        title: _builtins.str = ...,
        items: _abc.Iterable[Global___EditableListItem] | None = ...,
        can_add: _builtins.bool = ...,
        add_editor: Global___Control | None = ...,
        empty_text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["add_editor", b"add_editor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["add_editor", b"add_editor", "can_add", b"can_add", "empty_text", b"empty_text", "items", b"items", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditableList: _TypeAlias = EditableList  # noqa: Y015

@_typing.final
class EditableListItem(_message.Message):
    """One row of an EditableList."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    PRIMARY_FIELD_NUMBER: _builtins.int
    SECONDARY_FIELD_NUMBER: _builtins.int
    SUBTITLE_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    EDITABLE_FIELD_NUMBER: _builtins.int
    REMOVABLE_FIELD_NUMBER: _builtins.int
    EDITOR_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    """stable; echoed back in dispatches"""
    primary: _builtins.str
    """"0.254  192.168.1.10:32768" """
    secondary: _builtins.str
    """right-aligned caption: "map file", "mDNS" """
    subtitle: _builtins.str
    """beneath, muted: the label "PiEconetBridge FS" """
    state: Global___Indicator.State.ValueType
    """Small state badge for the row. UNKNOWN means no indicator; WARN marks,
    e.g., an unreachable peer. Reuses Indicator.State so the renderer shares
    one badge style across controls.
    """
    editable: _builtins.bool
    """edit affordance; `editor` below is prefilled"""
    removable: _builtins.bool
    """"-" affordance"""
    note: _builtins.str
    """short warning shown with the item, optional"""
    @_builtins.property
    def editor(self) -> Global___Control:
        """prefilled editor for THIS item, when editable"""

    @_builtins.property
    def actions(self) -> _containers.RepeatedCompositeFieldContainer[Global___EditableListAction]:
        """per-item commands, context menu"""

    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        primary: _builtins.str = ...,
        secondary: _builtins.str = ...,
        subtitle: _builtins.str = ...,
        state: Global___Indicator.State.ValueType = ...,
        editable: _builtins.bool = ...,
        removable: _builtins.bool = ...,
        editor: Global___Control | None = ...,
        actions: _abc.Iterable[Global___EditableListAction] | None = ...,
        note: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["editor", b"editor"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actions", b"actions", "editable", b"editable", "editor", b"editor", "id", b"id", "note", b"note", "primary", b"primary", "removable", b"removable", "secondary", b"secondary", "state", b"state", "subtitle", b"subtitle"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditableListItem: _TypeAlias = EditableListItem  # noqa: Y015

@_typing.final
class EditableListAction(_message.Message):
    """A named per-item command surfaced in the row's context menu. `warning`,
    when set, is the confirmation text the renderer must show before
    dispatching the ACTION; empty means no confirmation.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    WARNING_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    title: _builtins.str
    warning: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str = ...,
        warning: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "title", b"title", "warning", b"warning"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditableListAction: _TypeAlias = EditableListAction  # noqa: Y015

@_typing.final
class FileReference(_message.Message):
    """Reference primitive: a file on the server's host, shown as a small
    document icon plus display name, with the path as a tooltip, a state
    badge, and a pull-down of the server's actions. The renderer adds its
    own client-side actions (Reveal in Finder, gated on the host fingerprint;
    Copy Path, always). Server actions dispatch as `file_action_id`.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PATH_FIELD_NUMBER: _builtins.int
    DISPLAY_NAME_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    STATE_TEXT_FIELD_NUMBER: _builtins.int
    ACTIONS_FIELD_NUMBER: _builtins.int
    path: _builtins.str
    """absolute, on the server's host"""
    display_name: _builtins.str
    """"aun-map.json"; defaults to the path's file name"""
    state: Global___Indicator.State.ValueType
    """OK = loaded; WARN = missing; ERROR = load error. Reuses Indicator.State."""
    state_text: _builtins.str
    """"12 peers, 1 subnet" or the load error"""
    @_builtins.property
    def actions(self) -> _containers.RepeatedCompositeFieldContainer[Global___FileReferenceAction]:
        """server actions: "Reload" """

    def __init__(
        self,
        *,
        path: _builtins.str = ...,
        display_name: _builtins.str = ...,
        state: Global___Indicator.State.ValueType = ...,
        state_text: _builtins.str = ...,
        actions: _abc.Iterable[Global___FileReferenceAction] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["actions", b"actions", "display_name", b"display_name", "path", b"path", "state", b"state", "state_text", b"state_text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileReference: _TypeAlias = FileReference  # noqa: Y015

@_typing.final
class FileReferenceAction(_message.Message):
    """A named server-side action on a FileReference, surfaced in its pull-down."""

    DESCRIPTOR: _descriptor.Descriptor

    ID_FIELD_NUMBER: _builtins.int
    TITLE_FIELD_NUMBER: _builtins.int
    id: _builtins.str
    title: _builtins.str
    def __init__(
        self,
        *,
        id: _builtins.str = ...,
        title: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["id", b"id", "title", b"title"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FileReferenceAction: _TypeAlias = FileReferenceAction  # noqa: Y015

@_typing.final
class DispatchRequest(_message.Message):
    """--- Dispatch ---"""

    DESCRIPTOR: _descriptor.Descriptor

    EXTENSION_ID_FIELD_NUMBER: _builtins.int
    CONTROL_ID_FIELD_NUMBER: _builtins.int
    VIEW_REVISION_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    INDEX_VALUE_FIELD_NUMBER: _builtins.int
    EDITOR_COMMIT_FIELD_NUMBER: _builtins.int
    EDITABLE_LIST_EVENT_FIELD_NUMBER: _builtins.int
    FILE_ACTION_ID_FIELD_NUMBER: _builtins.int
    extension_id: _builtins.str
    """Which extension instance the event targets (matches View.extension_id)."""
    control_id: _builtins.str
    """Which control inside that extension's view (matches Control.id)."""
    view_revision: _builtins.int
    """The view_revision the client was looking at when it generated the
    event. The server rejects events with a stale revision so that a
    client cannot act on a control that the server has already
    replaced in the next pushed View.
    """
    bool_value: _builtins.bool
    string_value: _builtins.str
    index_value: _builtins.int
    file_action_id: _builtins.str
    @_builtins.property
    def editor_commit(self) -> Global___EditorCommit: ...
    @_builtins.property
    def editable_list_event(self) -> Global___EditableListEvent: ...
    def __init__(
        self,
        *,
        extension_id: _builtins.str = ...,
        control_id: _builtins.str = ...,
        view_revision: _builtins.int = ...,
        bool_value: _builtins.bool = ...,
        string_value: _builtins.str = ...,
        index_value: _builtins.int = ...,
        editor_commit: Global___EditorCommit | None = ...,
        editable_list_event: Global___EditableListEvent | None = ...,
        file_action_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "editable_list_event", b"editable_list_event", "editor_commit", b"editor_commit", "file_action_id", b"file_action_id", "index_value", b"index_value", "payload", b"payload", "string_value", b"string_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "control_id", b"control_id", "editable_list_event", b"editable_list_event", "editor_commit", b"editor_commit", "extension_id", b"extension_id", "file_action_id", b"file_action_id", "index_value", b"index_value", "payload", b"payload", "string_value", b"string_value", "view_revision", b"view_revision"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["bool_value", "string_value", "index_value", "editor_commit", "editable_list_event", "file_action_id"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___DispatchRequest: _TypeAlias = DispatchRequest  # noqa: Y015

@_typing.final
class EditableListEvent(_message.Message):
    """The user's action on one EditableList item. ADD carries no item_id and an
    `commit` built from the list's add_editor; EDIT carries the item_id and an
    `commit` from that item's editor; REMOVE carries just the item_id; ACTION
    carries the item_id and the chosen action_id (and no commit). The server
    validates item_id / action_id against the current view like any other
    dispatch, and applies an ADD / EDIT commit with the same no-partial rule as
    EditorCommit.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Kind:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _KindEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[EditableListEvent._Kind.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        ADD: EditableListEvent._Kind.ValueType  # 0
        EDIT: EditableListEvent._Kind.ValueType  # 1
        REMOVE: EditableListEvent._Kind.ValueType  # 2
        ACTION: EditableListEvent._Kind.ValueType  # 3

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    ADD: EditableListEvent.Kind.ValueType  # 0
    EDIT: EditableListEvent.Kind.ValueType  # 1
    REMOVE: EditableListEvent.Kind.ValueType  # 2
    ACTION: EditableListEvent.Kind.ValueType  # 3

    KIND_FIELD_NUMBER: _builtins.int
    ITEM_ID_FIELD_NUMBER: _builtins.int
    ACTION_ID_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    kind: Global___EditableListEvent.Kind.ValueType
    item_id: _builtins.str
    """empty for ADD"""
    action_id: _builtins.str
    """for ACTION"""
    @_builtins.property
    def commit(self) -> Global___EditorCommit:
        """for ADD and EDIT: the editor field values"""

    def __init__(
        self,
        *,
        kind: Global___EditableListEvent.Kind.ValueType = ...,
        item_id: _builtins.str = ...,
        action_id: _builtins.str = ...,
        commit: Global___EditorCommit | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["commit", b"commit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_id", b"action_id", "commit", b"commit", "item_id", b"item_id", "kind", b"kind"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditableListEvent: _TypeAlias = EditableListEvent  # noqa: Y015

@_typing.final
class EditorFieldValue(_message.Message):
    """One field's value inside an EditorCommit. The 'field_id' names a
    sub-control inside the ModalEditor's editor tree (matches the
    Control.id of that leaf). The payload variant must match the
    addressed sub-control's type (see EditorCommit validation below).
    """

    DESCRIPTOR: _descriptor.Descriptor

    FIELD_ID_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    INDEX_VALUE_FIELD_NUMBER: _builtins.int
    field_id: _builtins.str
    bool_value: _builtins.bool
    string_value: _builtins.str
    index_value: _builtins.int
    def __init__(
        self,
        *,
        field_id: _builtins.str = ...,
        bool_value: _builtins.bool = ...,
        string_value: _builtins.str = ...,
        index_value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "index_value", b"index_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "field_id", b"field_id", "index_value", b"index_value", "string_value", b"string_value", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["bool_value", "string_value", "index_value"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___EditorFieldValue: _TypeAlias = EditorFieldValue  # noqa: Y015

@_typing.final
class EditorCommit(_message.Message):
    """Atomic commit of a ModalEditor's editor tree. Sent as the payload of
    a DispatchRequest targeting a ModalEditor control.

    Clients bundle the final value of each sub-control whose value the
    user changed (or all sub-controls -- either is accepted). The server
    validates that every field_id names a sub-control actually present in
    the editor tree and that each value variant matches the sub-control's
    type; any violation rejects the whole commit (no partial applies).
    """

    DESCRIPTOR: _descriptor.Descriptor

    FIELDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def fields(self) -> _containers.RepeatedCompositeFieldContainer[Global___EditorFieldValue]: ...
    def __init__(
        self,
        *,
        fields: _abc.Iterable[Global___EditorFieldValue] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fields", b"fields"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EditorCommit: _TypeAlias = EditorCommit  # noqa: Y015

@_typing.final
class DispatchResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    """True if the event was accepted and handle_event ran. False means
    the request was rejected by the validation gauntlet -- 'error'
    describes why (stale event, unknown control, payload-type
    mismatch, unknown extension).
    """
    error: _builtins.str
    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted", "error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DispatchResponse: _TypeAlias = DispatchResponse  # noqa: Y015