"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>

This file is part of Beebium.

Beebium is free software: you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version. Beebium is distributed in the hope that it will
be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Beebium.
If not, see <https://www.gnu.org/licenses/>.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class InvokeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetadataEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    EXTENSION_ID_FIELD_NUMBER: _builtins.int
    SERVICE_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    extension_id: _builtins.str
    """Target instance id: a peripheral extension's id (from
    PeripheralExtensionService) or an Econet transport's id (from
    EconetTransportService). May be empty when exactly one loaded instance
    offers `service`, in which case the core routes by service name; when
    more than one does, an empty id is FAILED_PRECONDITION and the status
    message lists the candidate ids.
    """
    service: _builtins.str
    """Logical service within the extension, e.g. "RpcSerial"."""
    method: _builtins.str
    """Method within the service, e.g. "Send"."""
    payload: _builtins.bytes
    """Serialized request message, opaque to the core."""
    @_builtins.property
    def metadata(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """Request headers (auth, trace ids, ...)."""

    def __init__(
        self,
        *,
        extension_id: _builtins.str = ...,
        service: _builtins.str = ...,
        method: _builtins.str = ...,
        payload: _builtins.bytes = ...,
        metadata: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extension_id", b"extension_id", "metadata", b"metadata", "method", b"method", "payload", b"payload", "service", b"service"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InvokeRequest: _TypeAlias = InvokeRequest  # noqa: Y015

@_typing.final
class InvokeResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAYLOAD_FIELD_NUMBER: _builtins.int
    payload: _builtins.bytes
    """Serialized response message, opaque to the core. On a non-OK call the
    gRPC status (code + message) carries the error -- exactly as a native
    gRPC method would -- and this payload is empty.
    """
    def __init__(
        self,
        *,
        payload: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InvokeResponse: _TypeAlias = InvokeResponse  # noqa: Y015
