# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sideways_pb2 as sideways__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sideways_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SidewaysServiceStub(object):
    """Sideways ROM/RAM management service.

    Provides query and configuration of sideways ROM/RAM slots.
    Supports both aliased (Model B with 4 sockets) and non-aliased
    (ROM/RAM board with 16 independent slots) configurations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSlotStatus = channel.unary_unary(
                '/beebium.SidewaysService/GetSlotStatus',
                request_serializer=sideways__pb2.GetSlotStatusRequest.SerializeToString,
                response_deserializer=sideways__pb2.GetSlotStatusResponse.FromString,
                _registered_method=True)
        self.ConfigureSlot = channel.unary_unary(
                '/beebium.SidewaysService/ConfigureSlot',
                request_serializer=sideways__pb2.ConfigureSlotRequest.SerializeToString,
                response_deserializer=sideways__pb2.ConfigureSlotResponse.FromString,
                _registered_method=True)
        self.SetSlotWriteProtect = channel.unary_unary(
                '/beebium.SidewaysService/SetSlotWriteProtect',
                request_serializer=sideways__pb2.SetSlotWriteProtectRequest.SerializeToString,
                response_deserializer=sideways__pb2.SetSlotWriteProtectResponse.FromString,
                _registered_method=True)
        self.ReadSlotData = channel.unary_unary(
                '/beebium.SidewaysService/ReadSlotData',
                request_serializer=sideways__pb2.ReadSlotDataRequest.SerializeToString,
                response_deserializer=sideways__pb2.ReadSlotDataResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/beebium.SidewaysService/SubscribeEvents',
                request_serializer=sideways__pb2.SubscribeEventsRequest.SerializeToString,
                response_deserializer=sideways__pb2.SidewaysEvent.FromString,
                _registered_method=True)


class SidewaysServiceServicer(object):
    """Sideways ROM/RAM management service.

    Provides query and configuration of sideways ROM/RAM slots.
    Supports both aliased (Model B with 4 sockets) and non-aliased
    (ROM/RAM board with 16 independent slots) configurations.
    """

    def GetSlotStatus(self, request, context):
        """Query slot/socket configuration and current state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureSlot(self, request, context):
        """Configure a slot (empty/rom/ram) with optional image data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSlotWriteProtect(self, request, context):
        """Set or clear the write-protect switch on a RAM slot. Models a board's
        write-protect link/switch (e.g. the ATPL Sidewise S6 link). Rejected for
        slots that are not currently RAM.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSlotData(self, request, context):
        """Read slot contents (for debugging/inspection)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Subscribe to slot/bank selection events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidewaysServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSlotStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSlotStatus,
                    request_deserializer=sideways__pb2.GetSlotStatusRequest.FromString,
                    response_serializer=sideways__pb2.GetSlotStatusResponse.SerializeToString,
            ),
            'ConfigureSlot': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureSlot,
                    request_deserializer=sideways__pb2.ConfigureSlotRequest.FromString,
                    response_serializer=sideways__pb2.ConfigureSlotResponse.SerializeToString,
            ),
            'SetSlotWriteProtect': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSlotWriteProtect,
                    request_deserializer=sideways__pb2.SetSlotWriteProtectRequest.FromString,
                    response_serializer=sideways__pb2.SetSlotWriteProtectResponse.SerializeToString,
            ),
            'ReadSlotData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSlotData,
                    request_deserializer=sideways__pb2.ReadSlotDataRequest.FromString,
                    response_serializer=sideways__pb2.ReadSlotDataResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=sideways__pb2.SubscribeEventsRequest.FromString,
                    response_serializer=sideways__pb2.SidewaysEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'beebium.SidewaysService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('beebium.SidewaysService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidewaysService(object):
    """Sideways ROM/RAM management service.

    Provides query and configuration of sideways ROM/RAM slots.
    Supports both aliased (Model B with 4 sockets) and non-aliased
    (ROM/RAM board with 16 independent slots) configurations.
    """

    @staticmethod
    def GetSlotStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SidewaysService/GetSlotStatus',
            sideways__pb2.GetSlotStatusRequest.SerializeToString,
            sideways__pb2.GetSlotStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureSlot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SidewaysService/ConfigureSlot',
            sideways__pb2.ConfigureSlotRequest.SerializeToString,
            sideways__pb2.ConfigureSlotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSlotWriteProtect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SidewaysService/SetSlotWriteProtect',
            sideways__pb2.SetSlotWriteProtectRequest.SerializeToString,
            sideways__pb2.SetSlotWriteProtectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSlotData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/beebium.SidewaysService/ReadSlotData',
            sideways__pb2.ReadSlotDataRequest.SerializeToString,
            sideways__pb2.ReadSlotDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/beebium.SidewaysService/SubscribeEvents',
            sideways__pb2.SubscribeEventsRequest.SerializeToString,
            sideways__pb2.SidewaysEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)