# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ShutdownMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ShutdownModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ShutdownMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SHUTDOWN_GRACEFUL: _ShutdownMode.ValueType  # 0
    """Normal shutdown: notify clients, wait for subsystems, then terminate"""
    SHUTDOWN_IMMEDIATE: _ShutdownMode.ValueType  # 1
    """Immediate shutdown: terminate as soon as possible, skip coordination"""

class ShutdownMode(_ShutdownMode, metaclass=_ShutdownModeEnumTypeWrapper):
    """=== Shutdown RPC ===

    Shutdown mode determines how the server terminates
    """

SHUTDOWN_GRACEFUL: ShutdownMode.ValueType  # 0
"""Normal shutdown: notify clients, wait for subsystems, then terminate"""
SHUTDOWN_IMMEDIATE: ShutdownMode.ValueType  # 1
"""Immediate shutdown: terminate as soon as possible, skip coordination"""
Global___ShutdownMode: _TypeAlias = ShutdownMode  # noqa: Y015

class _ServerStatusType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ServerStatusTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ServerStatusType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SERVER_STATUS_READY: _ServerStatusType.ValueType  # 0
    """Server is ready and running normally
    Sent immediately when client subscribes
    """
    SERVER_STATUS_SHUTTING_DOWN: _ServerStatusType.ValueType  # 1
    """Server is beginning shutdown sequence
    Clients should finish pending operations and disconnect
    """
    SERVER_STATUS_IDENTITY_CHANGED: _ServerStatusType.ValueType  # 2
    """Machine identity has changed (e.g., name was updated)
    The identity field contains the new identity
    """
    SERVER_STATUS_SHUTDOWN_PROGRESS: _ServerStatusType.ValueType  # 3
    """Shutdown is in progress, showing subsystem coordination status
    The shutdown_conditions field contains status of each subsystem
    """
    SERVER_STATUS_HEARTBEAT: _ServerStatusType.ValueType  # 4
    """Periodic liveness tick, emitted on an otherwise-idle stream every few
    seconds. Carries no payload; its job is to keep the stream producing
    traffic so a client can detect a silently-unreachable server (network
    partition or a frozen process) by the *absence* of heartbeats. A healthy
    connection delivers these at a steady cadence.
    """

class ServerStatusType(_ServerStatusType, metaclass=_ServerStatusTypeEnumTypeWrapper):
    """Server status types"""

SERVER_STATUS_READY: ServerStatusType.ValueType  # 0
"""Server is ready and running normally
Sent immediately when client subscribes
"""
SERVER_STATUS_SHUTTING_DOWN: ServerStatusType.ValueType  # 1
"""Server is beginning shutdown sequence
Clients should finish pending operations and disconnect
"""
SERVER_STATUS_IDENTITY_CHANGED: ServerStatusType.ValueType  # 2
"""Machine identity has changed (e.g., name was updated)
The identity field contains the new identity
"""
SERVER_STATUS_SHUTDOWN_PROGRESS: ServerStatusType.ValueType  # 3
"""Shutdown is in progress, showing subsystem coordination status
The shutdown_conditions field contains status of each subsystem
"""
SERVER_STATUS_HEARTBEAT: ServerStatusType.ValueType  # 4
"""Periodic liveness tick, emitted on an otherwise-idle stream every few
seconds. Carries no payload; its job is to keep the stream producing
traffic so a client can detect a silently-unreachable server (network
partition or a frozen process) by the *absence* of heartbeats. A healthy
connection delivers these at a steady cadence.
"""
Global___ServerStatusType: _TypeAlias = ServerStatusType  # noqa: Y015

@_typing.final
class GetSystemInfoRequest(_message.Message):
    """Future: request specific fields, version info, etc."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSystemInfoRequest: _TypeAlias = GetSystemInfoRequest  # noqa: Y015

@_typing.final
class LaunchProvenance(_message.Message):
    """Launch provenance information
    Identifies who/what launched the emulator core and when
    """

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    INSTANCE_UUID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    """Freeform type string identifying the launching client
    Examples: "macos-gui", "python-client", "terminal", "vscode-extension"
    """
    instance_uuid: _builtins.str
    """Per-instance UUID (RFC 4122) generated at launch time"""
    version: _builtins.str
    """Optional version string of the launching client"""
    timestamp: _builtins.int
    """Unix timestamp when the core was launched (seconds since epoch)"""
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        instance_uuid: _builtins.str = ...,
        version: _builtins.str = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["instance_uuid", b"instance_uuid", "timestamp", b"timestamp", "type", b"type", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LaunchProvenance: _TypeAlias = LaunchProvenance  # noqa: Y015

@_typing.final
class MachineIdentity(_message.Message):
    """Machine identity information
    Stable UUID and mutable name for identification and labeling
    """

    DESCRIPTOR: _descriptor.Descriptor

    UUID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    MODEL_TYPE_FIELD_NUMBER: _builtins.int
    MODEL_NAME_FIELD_NUMBER: _builtins.int
    uuid: _builtins.str
    """RFC 4122 v4 UUID, stable for machine lifetime"""
    name: _builtins.str
    """User-assignable label, mutable via SetMachineName"""
    model_type: _builtins.str
    """Machine model type identifier (e.g., "ModelB", "ModelBPlus")
    Immutable, set at creation
    """
    model_name: _builtins.str
    """Human-readable model name (e.g., "BBC Model B 32K")
    Immutable, set at creation
    """
    def __init__(
        self,
        *,
        uuid: _builtins.str = ...,
        name: _builtins.str = ...,
        model_type: _builtins.str = ...,
        model_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["model_name", b"model_name", "model_type", b"model_type", "name", b"name", "uuid", b"uuid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MachineIdentity: _TypeAlias = MachineIdentity  # noqa: Y015

@_typing.final
class ConnectionInfo(_message.Message):
    """Connection tracking information
    Tracks the number of active client connections (WatchServerStatus streams)
    """

    DESCRIPTOR: _descriptor.Descriptor

    CLIENT_COUNT_FIELD_NUMBER: _builtins.int
    client_count: _builtins.int
    """Number of clients with active WatchServerStatus streams"""
    def __init__(
        self,
        *,
        client_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["client_count", b"client_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConnectionInfo: _TypeAlias = ConnectionInfo  # noqa: Y015

@_typing.final
class SystemInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROVENANCE_FIELD_NUMBER: _builtins.int
    IDENTITY_FIELD_NUMBER: _builtins.int
    CONNECTIONS_FIELD_NUMBER: _builtins.int
    CLOCK_SPEED_HZ_FIELD_NUMBER: _builtins.int
    PROTOCOL_FINGERPRINT_FIELD_NUMBER: _builtins.int
    EXECUTABLE_PATH_FIELD_NUMBER: _builtins.int
    clock_speed_hz: _builtins.int
    """Nominal CPU clock frequency in Hz (e.g. 2000000 for 2 MHz)."""
    protocol_fingerprint: _builtins.str
    """Fingerprint of the wire protocol the server was built against (a hash of
    the normalised proto contract). Clients compare this to their own
    compiled-in fingerprint at connect and refuse to proceed on a mismatch.
    """
    executable_path: _builtins.str
    """Filesystem path of the running server executable, as resolved from the
    OS rather than argv[0], so a PATH symlink reports its real target.

    This exists to make a protocol_fingerprint mismatch diagnosable. The
    question a mismatch raises is "which binary am I actually talking to?",
    and comparing two hashes cannot answer it: a stale server left running,
    a system-wide install shadowing a development build, or one variant of
    a multi-server bundle rebuilt while its siblings were not all look
    identical from the client. The path answers it directly.

    Empty if the path cannot be determined.
    """
    @_builtins.property
    def provenance(self) -> Global___LaunchProvenance:
        """Launch provenance (who started this core and when)"""

    @_builtins.property
    def identity(self) -> Global___MachineIdentity:
        """Machine identity (UUID and name)"""

    @_builtins.property
    def connections(self) -> Global___ConnectionInfo:
        """Connection tracking (active client count)"""

    def __init__(
        self,
        *,
        provenance: Global___LaunchProvenance | None = ...,
        identity: Global___MachineIdentity | None = ...,
        connections: Global___ConnectionInfo | None = ...,
        clock_speed_hz: _builtins.int = ...,
        protocol_fingerprint: _builtins.str = ...,
        executable_path: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["connections", b"connections", "identity", b"identity", "provenance", b"provenance"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clock_speed_hz", b"clock_speed_hz", "connections", b"connections", "executable_path", b"executable_path", "identity", b"identity", "protocol_fingerprint", b"protocol_fingerprint", "provenance", b"provenance"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SystemInfo: _TypeAlias = SystemInfo  # noqa: Y015

@_typing.final
class SetMachineNameRequest(_message.Message):
    """=== SetMachineName RPC ==="""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """New name for the machine (must not be empty)"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetMachineNameRequest: _TypeAlias = SetMachineNameRequest  # noqa: Y015

@_typing.final
class SetMachineNameResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    IDENTITY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def identity(self) -> Global___MachineIdentity:
        """Updated identity with new name"""

    def __init__(
        self,
        *,
        identity: Global___MachineIdentity | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetMachineNameResponse: _TypeAlias = SetMachineNameResponse  # noqa: Y015

@_typing.final
class ShutdownRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MODE_FIELD_NUMBER: _builtins.int
    GRACE_PERIOD_MS_FIELD_NUMBER: _builtins.int
    mode: Global___ShutdownMode.ValueType
    """How to shut down"""
    grace_period_ms: _builtins.int
    """Grace period in milliseconds before forced termination
    0 = use server default (5000ms)
    Only meaningful for SHUTDOWN_GRACEFUL
    """
    def __init__(
        self,
        *,
        mode: Global___ShutdownMode.ValueType = ...,
        grace_period_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["grace_period_ms", b"grace_period_ms", "mode", b"mode"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ShutdownRequest: _TypeAlias = ShutdownRequest  # noqa: Y015

@_typing.final
class ShutdownResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACCEPTED_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    accepted: _builtins.bool
    """Whether the shutdown request was accepted"""
    message: _builtins.str
    """Human-readable explanation
    On success: "Shutdown initiated"
    On failure: "Shutdown refused: multiple clients connected"
    """
    def __init__(
        self,
        *,
        accepted: _builtins.bool = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["accepted", b"accepted", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ShutdownResponse: _TypeAlias = ShutdownResponse  # noqa: Y015

@_typing.final
class ShutdownConditionStatus(_message.Message):
    """Status of a shutdown condition (subsystem preparing for shutdown)"""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    READY_FIELD_NUMBER: _builtins.int
    ELAPSED_MS_FIELD_NUMBER: _builtins.int
    TIMEOUT_MS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Name of the subsystem (e.g., "Disc controller", "Audio output")"""
    ready: _builtins.bool
    """True if this subsystem is ready for shutdown"""
    elapsed_ms: _builtins.int
    """Milliseconds elapsed since shutdown was initiated"""
    timeout_ms: _builtins.int
    """Timeout in milliseconds for this condition"""
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        ready: _builtins.bool = ...,
        elapsed_ms: _builtins.int = ...,
        timeout_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["elapsed_ms", b"elapsed_ms", "name", b"name", "ready", b"ready", "timeout_ms", b"timeout_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ShutdownConditionStatus: _TypeAlias = ShutdownConditionStatus  # noqa: Y015

@_typing.final
class WatchServerStatusRequest(_message.Message):
    """=== Server Status Streaming ===

    Future: filter for specific event types
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchServerStatusRequest: _TypeAlias = WatchServerStatusRequest  # noqa: Y015

@_typing.final
class ServerStatusEvent(_message.Message):
    """Server status event sent to subscribers"""

    DESCRIPTOR: _descriptor.Descriptor

    STATUS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    SHUTDOWN_GRACE_MS_FIELD_NUMBER: _builtins.int
    IDENTITY_FIELD_NUMBER: _builtins.int
    SHUTDOWN_CONDITIONS_FIELD_NUMBER: _builtins.int
    status: Global___ServerStatusType.ValueType
    """Type of status event"""
    message: _builtins.str
    """Optional human-readable message"""
    shutdown_grace_ms: _builtins.int
    """For SHUTTING_DOWN: grace period in milliseconds before forced termination
    Clients should disconnect within this time
    """
    @_builtins.property
    def identity(self) -> Global___MachineIdentity:
        """For IDENTITY_CHANGED: the updated identity"""

    @_builtins.property
    def shutdown_conditions(self) -> _containers.RepeatedCompositeFieldContainer[Global___ShutdownConditionStatus]:
        """For SHUTDOWN_PROGRESS: status of each subsystem condition"""

    def __init__(
        self,
        *,
        status: Global___ServerStatusType.ValueType = ...,
        message: _builtins.str = ...,
        shutdown_grace_ms: _builtins.int = ...,
        identity: Global___MachineIdentity | None = ...,
        shutdown_conditions: _abc.Iterable[Global___ShutdownConditionStatus] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["identity", b"identity", "message", b"message", "shutdown_conditions", b"shutdown_conditions", "shutdown_grace_ms", b"shutdown_grace_ms", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerStatusEvent: _TypeAlias = ServerStatusEvent  # noqa: Y015

@_typing.final
class AdvertisementState(_message.Message):
    """=== Advertisement RPC ===

    Current state of mDNS service advertisement
    """

    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIELD_NUMBER: _builtins.int
    ADVERTISED_NAME_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    """True if advertisement is currently enabled and active"""
    available: _builtins.bool
    """True if platform has mDNS support (Bonjour/Avahi/Windows mDNS)
    If false, advertisement cannot be enabled
    """
    advertised_name: _builtins.str
    """The actual name being advertised (may differ from identity.name
    if DNS-SD resolved a name collision, e.g., "Machine" -> "Machine (2)")
    Empty if not currently advertising
    """
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
        available: _builtins.bool = ...,
        advertised_name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["advertised_name", b"advertised_name", "available", b"available", "enabled", b"enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AdvertisementState: _TypeAlias = AdvertisementState  # noqa: Y015

@_typing.final
class GetAdvertisementStateRequest(_message.Message):
    """No parameters needed"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAdvertisementStateRequest: _TypeAlias = GetAdvertisementStateRequest  # noqa: Y015

@_typing.final
class GetAdvertisementStateResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___AdvertisementState: ...
    def __init__(
        self,
        *,
        state: Global___AdvertisementState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAdvertisementStateResponse: _TypeAlias = GetAdvertisementStateResponse  # noqa: Y015

@_typing.final
class SetAdvertisementRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLED_FIELD_NUMBER: _builtins.int
    enabled: _builtins.bool
    """True to enable advertisement, false to disable"""
    def __init__(
        self,
        *,
        enabled: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetAdvertisementRequest: _TypeAlias = SetAdvertisementRequest  # noqa: Y015

@_typing.final
class SetAdvertisementResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STATE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def state(self) -> Global___AdvertisementState:
        """The resulting state after the operation
        Note: enabled may be false even if requested true, if mDNS is unavailable
        """

    def __init__(
        self,
        *,
        state: Global___AdvertisementState | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["state", b"state"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetAdvertisementResponse: _TypeAlias = SetAdvertisementResponse  # noqa: Y015

@_typing.final
class GetPacingStatsRequest(_message.Message):
    """=== Pacing Stats RPC ==="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPacingStatsRequest: _TypeAlias = GetPacingStatsRequest  # noqa: Y015

@_typing.final
class WatchPacingStatsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INTERVAL_MS_FIELD_NUMBER: _builtins.int
    interval_ms: _builtins.int
    """Minimum interval between updates in milliseconds (default: 1000)."""
    def __init__(
        self,
        *,
        interval_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["interval_ms", b"interval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchPacingStatsRequest: _TypeAlias = WatchPacingStatsRequest  # noqa: Y015

@_typing.final
class SetSpeedMultiplierRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPEED_MULTIPLIER_FIELD_NUMBER: _builtins.int
    speed_multiplier: _builtins.float
    """0.0 = unlimited, 1.0 = real-time, 2.0 = double-speed."""
    def __init__(
        self,
        *,
        speed_multiplier: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["speed_multiplier", b"speed_multiplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetSpeedMultiplierRequest: _TypeAlias = SetSpeedMultiplierRequest  # noqa: Y015

@_typing.final
class SetSpeedMultiplierResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SPEED_MULTIPLIER_FIELD_NUMBER: _builtins.int
    speed_multiplier: _builtins.float
    """Echoed back resulting runtime speed multiplier."""
    def __init__(
        self,
        *,
        speed_multiplier: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["speed_multiplier", b"speed_multiplier"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SetSpeedMultiplierResponse: _TypeAlias = SetSpeedMultiplierResponse  # noqa: Y015

@_typing.final
class PacingStats(_message.Message):
    """Pacing statistics snapshot.
    Available from both host and parasite SystemService instances.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TICKS_EXECUTED_FIELD_NUMBER: _builtins.int
    TICKS_SKIPPED_FIELD_NUMBER: _builtins.int
    TICKS_IO_SKIPPED_FIELD_NUMBER: _builtins.int
    AVG_OVERSHOOT_US_FIELD_NUMBER: _builtins.int
    MAX_RECENT_OVERSHOOT_US_FIELD_NUMBER: _builtins.int
    SAFETY_MARGIN_US_FIELD_NUMBER: _builtins.int
    CONTROLLER_DRIFT_FIELD_NUMBER: _builtins.int
    CONTROLLER_INTEGRAL_FIELD_NUMBER: _builtins.int
    SPEED_MULTIPLIER_FIELD_NUMBER: _builtins.int
    ACHIEVED_SPEED_MULTIPLIER_FIELD_NUMBER: _builtins.int
    ESTIMATED_MAX_SPEED_MULTIPLIER_FIELD_NUMBER: _builtins.int
    ticks_executed: _builtins.int
    """Emulation timing
    Total ticks executed since start
    """
    ticks_skipped: _builtins.int
    """Ticks skipped (falling behind)"""
    ticks_io_skipped: _builtins.int
    """Ticks where sleep was skipped for I/O"""
    avg_overshoot_us: _builtins.float
    """Adaptive sleep margin
    Average OS sleep overshoot (microseconds)
    """
    max_recent_overshoot_us: _builtins.float
    """Recent maximum overshoot"""
    safety_margin_us: _builtins.float
    """Current adaptive safety margin"""
    controller_drift: _builtins.float
    """PI controller state
    Current drift in cycles (+ = ahead)
    """
    controller_integral: _builtins.float
    """Accumulated drift (time debt)"""
    speed_multiplier: _builtins.float
    """Speed control and headroom, sampled over the pacing window (~5s).
    Configured multiplier (0.0 = unlimited)
    """
    achieved_speed_multiplier: _builtins.float
    """Actual emulated rate / base clock over the window"""
    estimated_max_speed_multiplier: _builtins.float
    """Estimated ceiling at current host load; 0.0 = no estimate yet (idle/paused or not yet sampled)"""
    def __init__(
        self,
        *,
        ticks_executed: _builtins.int = ...,
        ticks_skipped: _builtins.int = ...,
        ticks_io_skipped: _builtins.int = ...,
        avg_overshoot_us: _builtins.float = ...,
        max_recent_overshoot_us: _builtins.float = ...,
        safety_margin_us: _builtins.float = ...,
        controller_drift: _builtins.float = ...,
        controller_integral: _builtins.float = ...,
        speed_multiplier: _builtins.float = ...,
        achieved_speed_multiplier: _builtins.float = ...,
        estimated_max_speed_multiplier: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["achieved_speed_multiplier", b"achieved_speed_multiplier", "avg_overshoot_us", b"avg_overshoot_us", "controller_drift", b"controller_drift", "controller_integral", b"controller_integral", "estimated_max_speed_multiplier", b"estimated_max_speed_multiplier", "max_recent_overshoot_us", b"max_recent_overshoot_us", "safety_margin_us", b"safety_margin_us", "speed_multiplier", b"speed_multiplier", "ticks_executed", b"ticks_executed", "ticks_io_skipped", b"ticks_io_skipped", "ticks_skipped", b"ticks_skipped"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PacingStats: _TypeAlias = PacingStats  # noqa: Y015