# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing
from . import video_pb2 as _video_pb2

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class VideoServiceStub:
    """Video frame streaming service"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> VideoServiceAsyncStub: ...
    SubscribeFrames: _grpc.UnaryStreamMultiCallable[_video_pb2.SubscribeFramesRequest, _video_pb2.Frame]
    """Stream frames as they complete (at VSYNC)"""
    GetConfig: _grpc.UnaryUnaryMultiCallable[_video_pb2.GetConfigRequest, _video_pb2.VideoConfig]
    """Get current video configuration"""
    GetTeletextScreen: _grpc.UnaryUnaryMultiCallable[_video_pb2.GetTeletextScreenRequest, _video_pb2.TeletextScreen]
    """Read the MODE 7 screen as characters rather than pixels.

    A snapshot rather than a stream: a caller wants one screen when it asks
    -- a copy command, or a script reading the display -- and pushing 8 KB
    of cell data per frame to every client on the chance that someone might
    copy would be absurd. A future vector renderer needs every frame aligned
    with the pixels it replaces, and that is a separate transport from the
    same capture; see docs/discussion/teletext-cell-capture.md.
    """

@_typing.type_check_only
class VideoServiceAsyncStub(VideoServiceStub):
    """Video frame streaming service"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    SubscribeFrames: _aio.UnaryStreamMultiCallable[_video_pb2.SubscribeFramesRequest, _video_pb2.Frame]  # type: ignore[assignment]
    """Stream frames as they complete (at VSYNC)"""
    GetConfig: _aio.UnaryUnaryMultiCallable[_video_pb2.GetConfigRequest, _video_pb2.VideoConfig]  # type: ignore[assignment]
    """Get current video configuration"""
    GetTeletextScreen: _aio.UnaryUnaryMultiCallable[_video_pb2.GetTeletextScreenRequest, _video_pb2.TeletextScreen]  # type: ignore[assignment]
    """Read the MODE 7 screen as characters rather than pixels.

    A snapshot rather than a stream: a caller wants one screen when it asks
    -- a copy command, or a script reading the display -- and pushing 8 KB
    of cell data per frame to every client on the chance that someone might
    copy would be absurd. A future vector renderer needs every frame aligned
    with the pixels it replaces, and that is a separate transport from the
    same capture; see docs/discussion/teletext-cell-capture.md.
    """

class VideoServiceServicer(metaclass=_abc_1.ABCMeta):
    """Video frame streaming service"""

    @_abc_1.abstractmethod
    def SubscribeFrames(
        self,
        request: _video_pb2.SubscribeFramesRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_video_pb2.Frame], _abc.AsyncIterator[_video_pb2.Frame]]:
        """Stream frames as they complete (at VSYNC)"""

    @_abc_1.abstractmethod
    def GetConfig(
        self,
        request: _video_pb2.GetConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.VideoConfig, _abc.Awaitable[_video_pb2.VideoConfig]]:
        """Get current video configuration"""

    @_abc_1.abstractmethod
    def GetTeletextScreen(
        self,
        request: _video_pb2.GetTeletextScreenRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_video_pb2.TeletextScreen, _abc.Awaitable[_video_pb2.TeletextScreen]]:
        """Read the MODE 7 screen as characters rather than pixels.

        A snapshot rather than a stream: a caller wants one screen when it asks
        -- a copy command, or a script reading the display -- and pushing 8 KB
        of cell data per frame to every client on the chance that someone might
        copy would be absurd. A future vector renderer needs every frame aligned
        with the pixels it replaces, and that is a separate transport from the
        same capture; see docs/discussion/teletext-cell-capture.md.
        """

def add_VideoServiceServicer_to_server(servicer: VideoServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...