# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _FieldOrder:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FieldOrderEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FieldOrder.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PROGRESSIVE: _FieldOrder.ValueType  # 0
    """Non-interlaced, single pass"""
    EVEN_FIRST: _FieldOrder.ValueType  # 1
    """Even lines (0,2,4...) rendered first temporally"""
    ODD_FIRST: _FieldOrder.ValueType  # 2
    """Odd lines (1,3,5...) rendered first temporally"""

class FieldOrder(_FieldOrder, metaclass=_FieldOrderEnumTypeWrapper):
    """Field ordering for interlaced frames.
    Clients can split composited frames into fields for authentic 50Hz display.
    """

PROGRESSIVE: FieldOrder.ValueType  # 0
"""Non-interlaced, single pass"""
EVEN_FIRST: FieldOrder.ValueType  # 1
"""Even lines (0,2,4...) rendered first temporally"""
ODD_FIRST: FieldOrder.ValueType  # 2
"""Odd lines (1,3,5...) rendered first temporally"""
Global___FieldOrder: _TypeAlias = FieldOrder  # noqa: Y015

class _TeletextCharacterSet:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TeletextCharacterSetEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TeletextCharacterSet.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TELETEXT_ALPHA: _TeletextCharacterSet.ValueType  # 0
    TELETEXT_CONTIGUOUS_GRAPHICS: _TeletextCharacterSet.ValueType  # 1
    TELETEXT_SEPARATED_GRAPHICS: _TeletextCharacterSet.ValueType  # 2

class TeletextCharacterSet(_TeletextCharacterSet, metaclass=_TeletextCharacterSetEnumTypeWrapper):
    """============================================================================
    MODE 7 screen as characters
    ============================================================================

    Which character set a cell was displayed with.
    """

TELETEXT_ALPHA: TeletextCharacterSet.ValueType  # 0
TELETEXT_CONTIGUOUS_GRAPHICS: TeletextCharacterSet.ValueType  # 1
TELETEXT_SEPARATED_GRAPHICS: TeletextCharacterSet.ValueType  # 2
Global___TeletextCharacterSet: _TypeAlias = TeletextCharacterSet  # noqa: Y015

class _TeletextTextLayout:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TeletextTextLayoutEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TeletextTextLayout.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TELETEXT_LAYOUT_ROWS: _TeletextTextLayout.ValueType  # 0
    """Each row of the region is its own line, preserving the shape of the
    selection. The default, and what a column of figures wants.
    """
    TELETEXT_LAYOUT_FLOWED: _TeletextTextLayout.ValueType  # 1
    """A row filled to the region's right edge wrapped, so it continues into
    the next without a break. What a sentence spanning rows wants.
    """

class TeletextTextLayout(_TeletextTextLayout, metaclass=_TeletextTextLayoutEnumTypeWrapper):
    """How a region of cells becomes a run of text."""

TELETEXT_LAYOUT_ROWS: TeletextTextLayout.ValueType  # 0
"""Each row of the region is its own line, preserving the shape of the
selection. The default, and what a column of figures wants.
"""
TELETEXT_LAYOUT_FLOWED: TeletextTextLayout.ValueType  # 1
"""A row filled to the region's right edge wrapped, so it continues into
the next without a break. What a sentence spanning rows wants.
"""
Global___TeletextTextLayout: _TypeAlias = TeletextTextLayout  # noqa: Y015

class _ScreenTextSearch:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScreenTextSearchEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ScreenTextSearch.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCREEN_TEXT_SEARCH_ANYWHERE: _ScreenTextSearch.ValueType  # 0
    """Read all the text, wherever it sits: on the character grid and placed
    freely with VDU 5. The default -- a caller that does not restrict gets
    everything. This is not a merge the caller performs: the server reads the
    grid and the off-grid text in disjoint passes and returns them together,
    so ANYWHERE is a strict superset of ALIGNED, not a second thing to
    reconcile against it.
    """
    SCREEN_TEXT_SEARCH_ALIGNED: _ScreenTextSearch.ValueType  # 1
    """Read only text aligned to the character grid: exact, cheaper, and what a
    drag snapped to the grid wants. A caller chooses this or ANYWHERE up
    front; there is never a reason to ask for both and combine them.
    """

class ScreenTextSearch(_ScreenTextSearch, metaclass=_ScreenTextSearchEnumTypeWrapper):
    """Which of the two searches a strategy should run.

    Honoured by strategies that recognise glyphs in pixels; the teletext
    strategy reads the character grid and is unaffected by it.
    """

SCREEN_TEXT_SEARCH_ANYWHERE: ScreenTextSearch.ValueType  # 0
"""Read all the text, wherever it sits: on the character grid and placed
freely with VDU 5. The default -- a caller that does not restrict gets
everything. This is not a merge the caller performs: the server reads the
grid and the off-grid text in disjoint passes and returns them together,
so ANYWHERE is a strict superset of ALIGNED, not a second thing to
reconcile against it.
"""
SCREEN_TEXT_SEARCH_ALIGNED: ScreenTextSearch.ValueType  # 1
"""Read only text aligned to the character grid: exact, cheaper, and what a
drag snapped to the grid wants. A caller chooses this or ANYWHERE up
front; there is never a reason to ask for both and combine them.
"""
Global___ScreenTextSearch: _TypeAlias = ScreenTextSearch  # noqa: Y015

class _ScreenTextLayout:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScreenTextLayoutEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ScreenTextLayout.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCREEN_TEXT_LAYOUT_ROWS: _ScreenTextLayout.ValueType  # 0
    """Each grid row is its own line, preserving the shape of the selection."""
    SCREEN_TEXT_LAYOUT_FLOWED: _ScreenTextLayout.ValueType  # 1
    """A row filled to the region's right edge wrapped, so it continues into
    the next without a break.
    """

class ScreenTextLayout(_ScreenTextLayout, metaclass=_ScreenTextLayoutEnumTypeWrapper):
    """How the runs are joined into `text`."""

SCREEN_TEXT_LAYOUT_ROWS: ScreenTextLayout.ValueType  # 0
"""Each grid row is its own line, preserving the shape of the selection."""
SCREEN_TEXT_LAYOUT_FLOWED: ScreenTextLayout.ValueType  # 1
"""A row filled to the region's right edge wrapped, so it continues into
the next without a break.
"""
Global___ScreenTextLayout: _TypeAlias = ScreenTextLayout  # noqa: Y015

class _ScreenTextCharacters:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScreenTextCharactersEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ScreenTextCharacters.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCREEN_TEXT_CHARACTERS_CODES: _ScreenTextCharacters.ValueType  # 0
    """What the byte is: `[`, `]`, `^`, `~` and the rest at face value. The
    default, because MODE 7 is the BBC's default screen mode and a copied
    BASIC listing is both the commonest capture and the worst to corrupt --
    `[` and `]` delimit assembler blocks and `^` is exponentiation.
    """
    SCREEN_TEXT_CHARACTERS_DISPLAYED: _ScreenTextCharacters.ValueType  # 1
    """What the screen showed: the SAA5050's own glyphs, as Unicode. For
    capturing teletext as it looked.
    """

class ScreenTextCharacters(_ScreenTextCharacters, metaclass=_ScreenTextCharactersEnumTypeWrapper):
    """Which meaning a MODE 7 byte is read with.

    The SAA5050 draws eleven codes as characters ASCII puts elsewhere: it puts a
    left arrow where ASCII has `[`, an up arrow where ASCII has `^`, a division
    sign where ASCII has `~`, and so on. A teletext screen can therefore be read
    two ways, and only the person reading it knows which they meant -- is this a
    picture of text, or a listing of code? So the transformation lives here, on
    the server, where the SAA5050's repertoire is known once, and the choice
    rides on the request, where the caller can make it.

    Honoured by the teletext strategy; a band read by recognising glyphs in
    pixels is unaffected, as its font is the MOS's and already ASCII.
    """

SCREEN_TEXT_CHARACTERS_CODES: ScreenTextCharacters.ValueType  # 0
"""What the byte is: `[`, `]`, `^`, `~` and the rest at face value. The
default, because MODE 7 is the BBC's default screen mode and a copied
BASIC listing is both the commonest capture and the worst to corrupt --
`[` and `]` delimit assembler blocks and `^` is exponentiation.
"""
SCREEN_TEXT_CHARACTERS_DISPLAYED: ScreenTextCharacters.ValueType  # 1
"""What the screen showed: the SAA5050's own glyphs, as Unicode. For
capturing teletext as it looked.
"""
Global___ScreenTextCharacters: _TypeAlias = ScreenTextCharacters  # noqa: Y015

@_typing.final
class SubscribeFramesRequest(_message.Message):
    """Future: format preferences, scaling options"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeFramesRequest: _TypeAlias = SubscribeFramesRequest  # noqa: Y015

@_typing.final
class Frame(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FRAME_NUMBER_FIELD_NUMBER: _builtins.int
    CYCLE_COUNT_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    PIXELS_FIELD_NUMBER: _builtins.int
    FIELD_ORDER_FIELD_NUMBER: _builtins.int
    LEFT_BORDER_FIELD_NUMBER: _builtins.int
    RIGHT_BORDER_FIELD_NUMBER: _builtins.int
    TOP_BORDER_FIELD_NUMBER: _builtins.int
    BOTTOM_BORDER_FIELD_NUMBER: _builtins.int
    DISPLAY_WIDTH_FIELD_NUMBER: _builtins.int
    DISPLAY_HEIGHT_FIELD_NUMBER: _builtins.int
    REGIONS_FIELD_NUMBER: _builtins.int
    frame_number: _builtins.int
    cycle_count: _builtins.int
    width: _builtins.int
    """Logical width in pixels (varies by mode)"""
    height: _builtins.int
    """Logical height in scanlines"""
    pixels: _builtins.bytes
    """BGRA32 pixel data, width * height * 4 bytes"""
    field_order: Global___FieldOrder.ValueType
    """For interlaced modes (e.g., MODE 7)"""
    left_border: _builtins.int
    """Border dimensions (pixels/scanlines of blanking around active area)
    Clients can use these for authentic CRT-style display with borders.
    Add left_border + width + right_border for total horizontal extent.
    Pixels from left edge to active area
    """
    right_border: _builtins.int
    """Pixels from active area to right edge"""
    top_border: _builtins.int
    """Scanlines from top edge to active area"""
    bottom_border: _builtins.int
    """Scanlines from active area to bottom edge"""
    display_width: _builtins.int
    """Target display resolution for scaling.
    BBC Micro displays all modes at the same physical CRT size.
    Clients should scale: width -> display_width, height -> display_height
    Examples:
      MODE 0: 640x256 logical = 640x256 display (1:1)
      MODE 1: 320x256 logical = 640x256 display (2:1 horizontal)
      MODE 2: 160x256 logical = 640x256 display (4:1 horizontal)
    Target display width (typically 640)
    """
    display_height: _builtins.int
    """Target display height (typically 256)"""
    @_builtins.property
    def regions(self) -> _containers.RepeatedCompositeFieldContainer[Global___DisplayRegion]:
        """Per-region display geometry for split-screen modes.
        Always populated with at least one region.
        """

    def __init__(
        self,
        *,
        frame_number: _builtins.int = ...,
        cycle_count: _builtins.int = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        pixels: _builtins.bytes = ...,
        field_order: Global___FieldOrder.ValueType = ...,
        left_border: _builtins.int = ...,
        right_border: _builtins.int = ...,
        top_border: _builtins.int = ...,
        bottom_border: _builtins.int = ...,
        display_width: _builtins.int = ...,
        display_height: _builtins.int = ...,
        regions: _abc.Iterable[Global___DisplayRegion] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bottom_border", b"bottom_border", "cycle_count", b"cycle_count", "display_height", b"display_height", "display_width", b"display_width", "field_order", b"field_order", "frame_number", b"frame_number", "height", b"height", "left_border", b"left_border", "pixels", b"pixels", "regions", b"regions", "right_border", b"right_border", "top_border", b"top_border", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Frame: _TypeAlias = Frame  # noqa: Y015

@_typing.final
class DisplayRegion(_message.Message):
    """A horizontal region of scanlines sharing the same logical pixel width.
    Used for split-screen modes where the CRTC is reprogrammed mid-frame
    (e.g., Elite uses MODE 4 upper / MODE 5 lower).
    """

    DESCRIPTOR: _descriptor.Descriptor

    START_LINE_FIELD_NUMBER: _builtins.int
    END_LINE_FIELD_NUMBER: _builtins.int
    PIXEL_WIDTH_FIELD_NUMBER: _builtins.int
    start_line: _builtins.int
    """First scanline (inclusive, 0-based)"""
    end_line: _builtins.int
    """Last scanline (exclusive)"""
    pixel_width: _builtins.int
    """Logical pixel width for scanlines in this region"""
    def __init__(
        self,
        *,
        start_line: _builtins.int = ...,
        end_line: _builtins.int = ...,
        pixel_width: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["end_line", b"end_line", "pixel_width", b"pixel_width", "start_line", b"start_line"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DisplayRegion: _TypeAlias = DisplayRegion  # noqa: Y015

@_typing.final
class GetConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetConfigRequest: _TypeAlias = GetConfigRequest  # noqa: Y015

@_typing.final
class VideoConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    FRAMERATE_HZ_FIELD_NUMBER: _builtins.int
    width: _builtins.int
    """640 for Mode 0-6, 480 for Mode 7"""
    height: _builtins.int
    """256 typical"""
    framerate_hz: _builtins.int
    """50Hz PAL"""
    def __init__(
        self,
        *,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        framerate_hz: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["framerate_hz", b"framerate_hz", "height", b"height", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VideoConfig: _TypeAlias = VideoConfig  # noqa: Y015

@_typing.final
class TeletextScreenRegion(_message.Message):
    """A rectangle of cells, in grid coordinates. Absent means the whole screen."""

    DESCRIPTOR: _descriptor.Descriptor

    ROW_FIELD_NUMBER: _builtins.int
    COLUMN_FIELD_NUMBER: _builtins.int
    ROWS_FIELD_NUMBER: _builtins.int
    COLUMNS_FIELD_NUMBER: _builtins.int
    row: _builtins.int
    column: _builtins.int
    rows: _builtins.int
    columns: _builtins.int
    def __init__(
        self,
        *,
        row: _builtins.int = ...,
        column: _builtins.int = ...,
        rows: _builtins.int = ...,
        columns: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["column", b"column", "columns", b"columns", "row", b"row", "rows", b"rows"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TeletextScreenRegion: _TypeAlias = TeletextScreenRegion  # noqa: Y015

@_typing.final
class GetTeletextScreenRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGION_FIELD_NUMBER: _builtins.int
    LAYOUT_FIELD_NUMBER: _builtins.int
    layout: Global___TeletextTextLayout.ValueType
    """How to join the region's rows into `text`."""
    @_builtins.property
    def region(self) -> Global___TeletextScreenRegion:
        """The part of the screen to read. Whole screen when unset."""

    def __init__(
        self,
        *,
        region: Global___TeletextScreenRegion | None = ...,
        layout: Global___TeletextTextLayout.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_region", b"_region", "region", b"region"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_region", b"_region", "layout", b"layout", "region", b"region"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__region: _TypeAlias = _typing.Literal["region"]  # noqa: Y015
    _WhichOneofArgType__region: _TypeAlias = _typing.Literal["_region", b"_region"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__region) -> _WhichOneofReturnType__region | None: ...

Global___GetTeletextScreenRequest: _TypeAlias = GetTeletextScreenRequest  # noqa: Y015

@_typing.final
class TeletextScreenCell(_message.Message):
    """One character cell, as it was displayed: the attributes here are the ones in
    effect at this cell after control codes were resolved, not something the
    caller has to re-derive.
    """

    DESCRIPTOR: _descriptor.Descriptor

    CHARACTER_FIELD_NUMBER: _builtins.int
    FG_FIELD_NUMBER: _builtins.int
    BG_FIELD_NUMBER: _builtins.int
    CHARSET_FIELD_NUMBER: _builtins.int
    DOUBLE_HEIGHT_TOP_FIELD_NUMBER: _builtins.int
    DOUBLE_HEIGHT_BOTTOM_FIELD_NUMBER: _builtins.int
    CONCEALED_FIELD_NUMBER: _builtins.int
    FLASHING_FIELD_NUMBER: _builtins.int
    CURSOR_FIELD_NUMBER: _builtins.int
    IS_CONTROL_CODE_FIELD_NUMBER: _builtins.int
    character: _builtins.int
    """7-bit SAA5050 code"""
    fg: _builtins.int
    """Colour index 0-7"""
    bg: _builtins.int
    """Colour index 0-7"""
    charset: Global___TeletextCharacterSet.ValueType
    double_height_top: _builtins.bool
    double_height_bottom: _builtins.bool
    concealed: _builtins.bool
    flashing: _builtins.bool
    cursor: _builtins.bool
    is_control_code: _builtins.bool
    def __init__(
        self,
        *,
        character: _builtins.int = ...,
        fg: _builtins.int = ...,
        bg: _builtins.int = ...,
        charset: Global___TeletextCharacterSet.ValueType = ...,
        double_height_top: _builtins.bool = ...,
        double_height_bottom: _builtins.bool = ...,
        concealed: _builtins.bool = ...,
        flashing: _builtins.bool = ...,
        cursor: _builtins.bool = ...,
        is_control_code: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bg", b"bg", "character", b"character", "charset", b"charset", "concealed", b"concealed", "cursor", b"cursor", "double_height_bottom", b"double_height_bottom", "double_height_top", b"double_height_top", "fg", b"fg", "flashing", b"flashing", "is_control_code", b"is_control_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TeletextScreenCell: _TypeAlias = TeletextScreenCell  # noqa: Y015

@_typing.final
class TeletextScreen(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ACTIVE_FIELD_NUMBER: _builtins.int
    ROWS_FIELD_NUMBER: _builtins.int
    COLUMNS_FIELD_NUMBER: _builtins.int
    CELLS_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    FRAME_NUMBER_FIELD_NUMBER: _builtins.int
    active: _builtins.bool
    """False when the display is not MODE 7. The cells then describe whatever
    was last shown in MODE 7 rather than anything current, so a caller must
    check this before using them.
    """
    rows: _builtins.int
    """Dimensions of the returned region, not of the screen."""
    columns: _builtins.int
    text: _builtins.str
    """The region as text, converted server-side so every client agrees on what
    graphics, control codes, concealed cells and double-height rows copy as.
    Lines are joined with LF; converting to a platform-native ending is the
    client's business, since the server cannot know the client's platform.
    """
    frame_number: _builtins.int
    """Increments once per captured frame."""
    @_builtins.property
    def cells(self) -> _containers.RepeatedCompositeFieldContainer[Global___TeletextScreenCell]:
        """Row-major, rows * columns entries."""

    def __init__(
        self,
        *,
        active: _builtins.bool = ...,
        rows: _builtins.int = ...,
        columns: _builtins.int = ...,
        cells: _abc.Iterable[Global___TeletextScreenCell] | None = ...,
        text: _builtins.str = ...,
        frame_number: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active", b"active", "cells", b"cells", "columns", b"columns", "frame_number", b"frame_number", "rows", b"rows", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TeletextScreen: _TypeAlias = TeletextScreen  # noqa: Y015

@_typing.final
class PixelRegion(_message.Message):
    """============================================================================
    Screen text
    ============================================================================

    A rectangle in frame pixel coordinates, the origin being the top-left of the
    active area rather than of the bordered display.
    """

    DESCRIPTOR: _descriptor.Descriptor

    X_FIELD_NUMBER: _builtins.int
    Y_FIELD_NUMBER: _builtins.int
    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    x: _builtins.int
    y: _builtins.int
    width: _builtins.int
    height: _builtins.int
    def __init__(
        self,
        *,
        x: _builtins.int = ...,
        y: _builtins.int = ...,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "width", b"width", "x", b"x", "y", b"y"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PixelRegion: _TypeAlias = PixelRegion  # noqa: Y015

@_typing.final
class GetScreenTextRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGION_FIELD_NUMBER: _builtins.int
    SEARCH_FIELD_NUMBER: _builtins.int
    LAYOUT_FIELD_NUMBER: _builtins.int
    CHARACTERS_FIELD_NUMBER: _builtins.int
    HOLD_ID_FIELD_NUMBER: _builtins.int
    search: Global___ScreenTextSearch.ValueType
    layout: Global___ScreenTextLayout.ValueType
    characters: Global___ScreenTextCharacters.ValueType
    hold_id: _builtins.int
    """Read the screen held under this id rather than the live one, so what
    comes back describes the still the caller is looking at. NOT_FOUND when
    the hold is unknown or has expired -- silently reading the live screen
    instead would be the very confusion holding exists to prevent.
    """
    @_builtins.property
    def region(self) -> Global___PixelRegion:
        """The part of the display to read. Whole display when unset. Independent of
        `search`: what part of the screen to read and how hard to look for text
        in it are separate choices.
        """

    def __init__(
        self,
        *,
        region: Global___PixelRegion | None = ...,
        search: Global___ScreenTextSearch.ValueType = ...,
        layout: Global___ScreenTextLayout.ValueType = ...,
        characters: Global___ScreenTextCharacters.ValueType = ...,
        hold_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_hold_id", b"_hold_id", "_region", b"_region", "hold_id", b"hold_id", "region", b"region"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_hold_id", b"_hold_id", "_region", b"_region", "characters", b"characters", "hold_id", b"hold_id", "layout", b"layout", "region", b"region", "search", b"search"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__hold_id: _TypeAlias = _typing.Literal["hold_id"]  # noqa: Y015
    _WhichOneofArgType__hold_id: _TypeAlias = _typing.Literal["_hold_id", b"_hold_id"]  # noqa: Y015
    _WhichOneofReturnType__region: _TypeAlias = _typing.Literal["region"]  # noqa: Y015
    _WhichOneofArgType__region: _TypeAlias = _typing.Literal["_region", b"_region"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hold_id) -> _WhichOneofReturnType__hold_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__region) -> _WhichOneofReturnType__region | None: ...

Global___GetScreenTextRequest: _TypeAlias = GetScreenTextRequest  # noqa: Y015

@_typing.final
class ScreenTextCell(_message.Message):
    """One character cell of a run: where it sits, and whether a glyph was
    recognised there. A genuine space is a match (it is a real character); an
    unmatched cell had ink the font could not identify and copies as a space.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BOUNDS_FIELD_NUMBER: _builtins.int
    MATCHED_FIELD_NUMBER: _builtins.int
    matched: _builtins.bool
    """True when a glyph was recognised here, false when the cell had ink that
    matched nothing. So a client can highlight only what was read: painting
    an unmatched cell would dress a failed read up as a success, even though
    the text still carries a space for it to keep columns aligned.
    """
    @_builtins.property
    def bounds(self) -> Global___PixelRegion: ...
    def __init__(
        self,
        *,
        bounds: Global___PixelRegion | None = ...,
        matched: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bounds", b"bounds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bounds", b"bounds", "matched", b"matched"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenTextCell: _TypeAlias = ScreenTextCell  # noqa: Y015

@_typing.final
class ScreenTextRun(_message.Message):
    """A contiguous piece of text and where it was found, so a client can highlight
    exactly what it captured.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TEXT_FIELD_NUMBER: _builtins.int
    BOUNDS_FIELD_NUMBER: _builtins.int
    CELL_WIDTH_FIELD_NUMBER: _builtins.int
    CELL_HEIGHT_FIELD_NUMBER: _builtins.int
    CELLS_FIELD_NUMBER: _builtins.int
    text: _builtins.str
    cell_width: _builtins.int
    """The character cell geometry this run was read with, so a selection can
    snap to it. Zero when the run is not cell-aligned, as text written at
    the graphics cursor is.
    """
    cell_height: _builtins.int
    @_builtins.property
    def bounds(self) -> Global___PixelRegion: ...
    @_builtins.property
    def cells(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScreenTextCell]:
        """The run's cells in reading order, from the glyph-recognising strategy, so
        a client highlights only the cells it read rather than the whole run --
        which spans unmatched cells too. Empty from the teletext strategy, whose
        cells are exact characters and are all matched: a client then highlights
        the whole run's bounds.
        """

    def __init__(
        self,
        *,
        text: _builtins.str = ...,
        bounds: Global___PixelRegion | None = ...,
        cell_width: _builtins.int = ...,
        cell_height: _builtins.int = ...,
        cells: _abc.Iterable[Global___ScreenTextCell] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bounds", b"bounds"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bounds", b"bounds", "cell_height", b"cell_height", "cell_width", b"cell_width", "cells", b"cells", "text", b"text"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenTextRun: _TypeAlias = ScreenTextRun  # noqa: Y015

@_typing.final
class ScreenText(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUPPORTED_FIELD_NUMBER: _builtins.int
    RUNS_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    UNREADABLE_CELLS_FIELD_NUMBER: _builtins.int
    AMBIGUOUS_CELLS_FIELD_NUMBER: _builtins.int
    FRAME_NUMBER_FIELD_NUMBER: _builtins.int
    supported: _builtins.bool
    """True when at least one band in the requested region had a strategy that
    could read it.

    Distinct from readable-but-empty: a graphics screen that was read and
    found to contain no text is supported with no runs, whereas a display
    this build has no strategy for is unsupported. Which displays fall in
    the second group narrows as strategies are added.
    """
    text: _builtins.str
    """The runs joined into text by `layout`, for a client that wants a string
    and not structure. Lines are joined with LF; converting to a
    platform-native ending is the client's business, since the server cannot
    know the client's platform.
    """
    unreadable_cells: _builtins.int
    """Cells a strategy tried to read and could not identify at all. Zero for
    the teletext strategy, whose cells are exact character codes.
    """
    ambiguous_cells: _builtins.int
    """Cells a strategy read but could not pin to a single character, because
    the font in use draws two characters identically. Also zero for
    teletext.
    """
    frame_number: _builtins.int
    @_builtins.property
    def runs(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScreenTextRun]:
        """In reading order: bands top to bottom, and within a band by baseline
        then x.
        """

    def __init__(
        self,
        *,
        supported: _builtins.bool = ...,
        runs: _abc.Iterable[Global___ScreenTextRun] | None = ...,
        text: _builtins.str = ...,
        unreadable_cells: _builtins.int = ...,
        ambiguous_cells: _builtins.int = ...,
        frame_number: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ambiguous_cells", b"ambiguous_cells", "frame_number", b"frame_number", "runs", b"runs", "supported", b"supported", "text", b"text", "unreadable_cells", b"unreadable_cells"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenText: _TypeAlias = ScreenText  # noqa: Y015

@_typing.final
class GetScreenGeometryRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOLD_ID_FIELD_NUMBER: _builtins.int
    hold_id: _builtins.int
    """The grid of a held screen rather than the live one. NOT_FOUND when the
    hold is unknown or has expired.
    """
    def __init__(
        self,
        *,
        hold_id: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_hold_id", b"_hold_id", "hold_id", b"hold_id"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_hold_id", b"_hold_id", "hold_id", b"hold_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__hold_id: _TypeAlias = _typing.Literal["hold_id"]  # noqa: Y015
    _WhichOneofArgType__hold_id: _TypeAlias = _typing.Literal["_hold_id", b"_hold_id"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__hold_id) -> _WhichOneofReturnType__hold_id | None: ...

Global___GetScreenGeometryRequest: _TypeAlias = GetScreenGeometryRequest  # noqa: Y015

@_typing.final
class HoldScreenRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INCLUDE_FRAME_FIELD_NUMBER: _builtins.int
    include_frame: _builtins.bool
    """Return the held still as well, so a client can display exactly the frame
    its reads will be made against. Without it the client shows whatever
    frame it last drew, which may be a frame or two earlier than the capture
    -- close, but not the same picture.
    """
    def __init__(
        self,
        *,
        include_frame: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["include_frame", b"include_frame"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HoldScreenRequest: _TypeAlias = HoldScreenRequest  # noqa: Y015

@_typing.final
class ScreenHold(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOLD_ID_FIELD_NUMBER: _builtins.int
    GEOMETRY_FIELD_NUMBER: _builtins.int
    FRAME_FIELD_NUMBER: _builtins.int
    hold_id: _builtins.int
    """Names this hold in later GetScreenText and GetScreenGeometry calls."""
    @_builtins.property
    def geometry(self) -> Global___ScreenGeometry:
        """The grid the held screen implies. Returned here so a drag can snap
        without a second call, and so the geometry can never drift from the
        pixels it describes.
        """

    @_builtins.property
    def frame(self) -> Global___Frame:
        """The held still, when `include_frame` was set, in the same shape the frame
        stream carries so a client can display it through the code it already
        has.
        """

    def __init__(
        self,
        *,
        hold_id: _builtins.int = ...,
        geometry: Global___ScreenGeometry | None = ...,
        frame: Global___Frame | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_frame", b"_frame", "frame", b"frame", "geometry", b"geometry"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_frame", b"_frame", "frame", b"frame", "geometry", b"geometry", "hold_id", b"hold_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__frame: _TypeAlias = _typing.Literal["frame"]  # noqa: Y015
    _WhichOneofArgType__frame: _TypeAlias = _typing.Literal["_frame", b"_frame"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__frame) -> _WhichOneofReturnType__frame | None: ...

Global___ScreenHold: _TypeAlias = ScreenHold  # noqa: Y015

@_typing.final
class ReleaseScreenRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HOLD_ID_FIELD_NUMBER: _builtins.int
    hold_id: _builtins.int
    def __init__(
        self,
        *,
        hold_id: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hold_id", b"hold_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseScreenRequest: _TypeAlias = ReleaseScreenRequest  # noqa: Y015

@_typing.final
class ReleaseScreenResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReleaseScreenResponse: _TypeAlias = ReleaseScreenResponse  # noqa: Y015

@_typing.final
class ScreenBandGeometry(_message.Message):
    """The character grid for one band of scanlines, in frame pixel coordinates.

    Reported for every band whether or not text can be read from it: where the
    cells are and what is in them are separate questions, and snapping needs
    only the first.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TOP_FIELD_NUMBER: _builtins.int
    BOTTOM_FIELD_NUMBER: _builtins.int
    CELL_WIDTH_FIELD_NUMBER: _builtins.int
    CELL_HEIGHT_FIELD_NUMBER: _builtins.int
    COLUMN_PITCH_FIELD_NUMBER: _builtins.int
    ROW_PITCH_FIELD_NUMBER: _builtins.int
    ORIGIN_X_FIELD_NUMBER: _builtins.int
    ORIGIN_Y_FIELD_NUMBER: _builtins.int
    top: _builtins.int
    """First scanline, inclusive"""
    bottom: _builtins.int
    """One past the last"""
    cell_width: _builtins.int
    cell_height: _builtins.int
    column_pitch: _builtins.int
    """Cell-to-cell step. Equal to the cell size except where a mode leaves
    blank scanlines between rows, as MODE 3 and MODE 6 do: an eight-scanline
    glyph on a ten-scanline pitch.
    """
    row_pitch: _builtins.int
    origin_x: _builtins.int
    """Where the grid starts within the band"""
    origin_y: _builtins.int
    def __init__(
        self,
        *,
        top: _builtins.int = ...,
        bottom: _builtins.int = ...,
        cell_width: _builtins.int = ...,
        cell_height: _builtins.int = ...,
        column_pitch: _builtins.int = ...,
        row_pitch: _builtins.int = ...,
        origin_x: _builtins.int = ...,
        origin_y: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bottom", b"bottom", "cell_height", b"cell_height", "cell_width", b"cell_width", "column_pitch", b"column_pitch", "origin_x", b"origin_x", "origin_y", b"origin_y", "row_pitch", b"row_pitch", "top", b"top"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenBandGeometry: _TypeAlias = ScreenBandGeometry  # noqa: Y015

@_typing.final
class ScreenGeometry(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BANDS_FIELD_NUMBER: _builtins.int
    FRAME_NUMBER_FIELD_NUMBER: _builtins.int
    frame_number: _builtins.int
    @_builtins.property
    def bands(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScreenBandGeometry]: ...
    def __init__(
        self,
        *,
        bands: _abc.Iterable[Global___ScreenBandGeometry] | None = ...,
        frame_number: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bands", b"bands", "frame_number", b"frame_number"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScreenGeometry: _TypeAlias = ScreenGeometry  # noqa: Y015