# Beebium peripheral and transport extensions

add_subdirectory(test-scratch-ram)
add_subdirectory(acorn-scsi)
add_subdirectory(scsi-hard-disc)
add_subdirectory(acorn-rtc)
add_subdirectory(acorn-65c02-coprocessor)
add_subdirectory(acorn-65c102-coprocessor)
add_subdirectory(aun)
add_subdirectory(host-serial)
add_subdirectory(loopback-serial)
add_subdirectory(rpc-serial)
add_subdirectory(ip232-serial)
add_subdirectory(rfc2217-common)
add_subdirectory(rfc2217-client-serial)
add_subdirectory(rfc2217-server-serial)
add_subdirectory(piconet)
