# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import aun_pb2 as _aun_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AunServiceStub:
    """AUN-specific service. Lives alongside the AunEconetTransportExtension
    in src/extensions/aun/ and is served via that extension's AunDispatcher
    over the core's ExtensionRpc channel (no gRPC stub is compiled from this
    service block). It is reachable whenever the AUN transport is loaded
    (--aun, or a preset whose econet.transport is aun), addressed by the
    instance id EconetTransportService reports; with no AUN transport loaded,
    ExtensionRpc answers NOT_FOUND. AddPeer, RemovePeer and SetConnected work
    before the AUN socket is up (before EnableEconet, or with port=none): the
    edits are recorded and applied when the backend comes up.

    Validation failures are reported in-band (success=false and an error
    string) with an OK call status; only a malformed request is a non-OK status.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for AUN (peer table management, AUN-port reporting, the cable-plug
    simulation that drives DCD) lives here.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AunServiceAsyncStub: ...
    SetConnected: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunSetConnectedRequest, _aun_pb2.AunSetConnectedResponse]
    """Connect or disconnect the simulated network cable. While
    disconnected the ADLC sees DCD high (no carrier). Always succeeds;
    when the socket is not up yet the state is remembered and applied when
    it comes up, and the response's error field says so.
    """
    AddPeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunAddPeerRequest, _aun_pb2.AunAddPeerResponse]
    """Add or replace this client's (Api) entry mapping an Econet address to a
    UDP endpoint. It takes precedence over every other source for that
    (net, stn) (see AunPeerSource).
    """
    RemovePeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunRemovePeerRequest, _aun_pb2.AunRemovePeerResponse]
    """Remove the Api entry AddPeer made for an Econet address. Entries from
    other sources are untouched, so a station also named by the launch
    config, the map file or mDNS falls back to that entry rather than
    disappearing. Always succeeds, including when there was no Api entry.
    """
    ListPeers: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunListPeersRequest, _aun_pb2.AunListPeersResponse]
    """Enumerate the resolved routing table: one entry per (net, stn), from
    whichever source won it (see AunPeer.source).
    """
    GetStatus: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunGetStatusRequest, _aun_pb2.AunGetStatusResponse]
    """Read the AUN transport status (link state, port, peer count, map file,
    discovery mode).
    """
    ReloadMap: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunReloadMapRequest, _aun_pb2.AunReloadMapResponse]
    """Re-read the per-user aun-map.json now, replacing the map file's peers,
    its subnet rules and the Subnet peers materialised from subnet rules
    (Api, Launch and Discovered peers, and --aun subnet= rules, are
    untouched). A modification is picked up automatically by the mtime poll
    on the discovery sweep, which runs while discovery browses
    (discovery=on or browse); this forces it. Under discovery=announce or
    off there is no poll, so another instance's edit arrives only with a
    ReloadMap or this instance's own next map edit.
    """
    AddMapPeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapPeerRequest, _aun_pb2.AunAddMapPeerResponse]
    """Edit the per-user aun-map.json. The server owns the file (it may be on
    another host): it writes its own file atomically, preserving entry order
    and unknown keys, then applies the change to its own peer set at once;
    other instances pick it up from their poll (see ReloadMap). Add is
    add-or-replace, keyed by (net, stn) for a peer and by net for a subnet
    rule. Every edit fails with "the map file is disabled (map-file=none)"
    when it is.
    """
    RemoveMapPeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapPeerRequest, _aun_pb2.AunRemoveMapPeerResponse]
    AddMapSubnet: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapSubnetRequest, _aun_pb2.AunAddMapSubnetResponse]
    RemoveMapSubnet: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapSubnetRequest, _aun_pb2.AunRemoveMapSubnetResponse]
    ListMap: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunListMapRequest, _aun_pb2.AunListMapResponse]
    """List the map file's entries (with labels and host-resolution state),
    distinct from ListPeers which lists the live resolved routing table.
    Empty, with no error, when the map file is disabled.
    """

@_typing.type_check_only
class AunServiceAsyncStub(AunServiceStub):
    """AUN-specific service. Lives alongside the AunEconetTransportExtension
    in src/extensions/aun/ and is served via that extension's AunDispatcher
    over the core's ExtensionRpc channel (no gRPC stub is compiled from this
    service block). It is reachable whenever the AUN transport is loaded
    (--aun, or a preset whose econet.transport is aun), addressed by the
    instance id EconetTransportService reports; with no AUN transport loaded,
    ExtensionRpc answers NOT_FOUND. AddPeer, RemovePeer and SetConnected work
    before the AUN socket is up (before EnableEconet, or with port=none): the
    edits are recorded and applied when the backend comes up.

    Validation failures are reported in-band (success=false and an error
    string) with an OK call status; only a malformed request is a non-OK status.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for AUN (peer table management, AUN-port reporting, the cable-plug
    simulation that drives DCD) lives here.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SetConnected: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunSetConnectedRequest, _aun_pb2.AunSetConnectedResponse]  # type: ignore[assignment]
    """Connect or disconnect the simulated network cable. While
    disconnected the ADLC sees DCD high (no carrier). Always succeeds;
    when the socket is not up yet the state is remembered and applied when
    it comes up, and the response's error field says so.
    """
    AddPeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunAddPeerRequest, _aun_pb2.AunAddPeerResponse]  # type: ignore[assignment]
    """Add or replace this client's (Api) entry mapping an Econet address to a
    UDP endpoint. It takes precedence over every other source for that
    (net, stn) (see AunPeerSource).
    """
    RemovePeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunRemovePeerRequest, _aun_pb2.AunRemovePeerResponse]  # type: ignore[assignment]
    """Remove the Api entry AddPeer made for an Econet address. Entries from
    other sources are untouched, so a station also named by the launch
    config, the map file or mDNS falls back to that entry rather than
    disappearing. Always succeeds, including when there was no Api entry.
    """
    ListPeers: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunListPeersRequest, _aun_pb2.AunListPeersResponse]  # type: ignore[assignment]
    """Enumerate the resolved routing table: one entry per (net, stn), from
    whichever source won it (see AunPeer.source).
    """
    GetStatus: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunGetStatusRequest, _aun_pb2.AunGetStatusResponse]  # type: ignore[assignment]
    """Read the AUN transport status (link state, port, peer count, map file,
    discovery mode).
    """
    ReloadMap: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunReloadMapRequest, _aun_pb2.AunReloadMapResponse]  # type: ignore[assignment]
    """Re-read the per-user aun-map.json now, replacing the map file's peers,
    its subnet rules and the Subnet peers materialised from subnet rules
    (Api, Launch and Discovered peers, and --aun subnet= rules, are
    untouched). A modification is picked up automatically by the mtime poll
    on the discovery sweep, which runs while discovery browses
    (discovery=on or browse); this forces it. Under discovery=announce or
    off there is no poll, so another instance's edit arrives only with a
    ReloadMap or this instance's own next map edit.
    """
    AddMapPeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapPeerRequest, _aun_pb2.AunAddMapPeerResponse]  # type: ignore[assignment]
    """Edit the per-user aun-map.json. The server owns the file (it may be on
    another host): it writes its own file atomically, preserving entry order
    and unknown keys, then applies the change to its own peer set at once;
    other instances pick it up from their poll (see ReloadMap). Add is
    add-or-replace, keyed by (net, stn) for a peer and by net for a subnet
    rule. Every edit fails with "the map file is disabled (map-file=none)"
    when it is.
    """
    RemoveMapPeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapPeerRequest, _aun_pb2.AunRemoveMapPeerResponse]  # type: ignore[assignment]
    AddMapSubnet: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapSubnetRequest, _aun_pb2.AunAddMapSubnetResponse]  # type: ignore[assignment]
    RemoveMapSubnet: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapSubnetRequest, _aun_pb2.AunRemoveMapSubnetResponse]  # type: ignore[assignment]
    ListMap: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunListMapRequest, _aun_pb2.AunListMapResponse]  # type: ignore[assignment]
    """List the map file's entries (with labels and host-resolution state),
    distinct from ListPeers which lists the live resolved routing table.
    Empty, with no error, when the map file is disabled.
    """

class AunServiceServicer(metaclass=_abc_1.ABCMeta):
    """AUN-specific service. Lives alongside the AunEconetTransportExtension
    in src/extensions/aun/ and is served via that extension's AunDispatcher
    over the core's ExtensionRpc channel (no gRPC stub is compiled from this
    service block). It is reachable whenever the AUN transport is loaded
    (--aun, or a preset whose econet.transport is aun), addressed by the
    instance id EconetTransportService reports; with no AUN transport loaded,
    ExtensionRpc answers NOT_FOUND. AddPeer, RemovePeer and SetConnected work
    before the AUN socket is up (before EnableEconet, or with port=none): the
    edits are recorded and applied when the backend comes up.

    Validation failures are reported in-band (success=false and an error
    string) with an OK call status; only a malformed request is a non-OK status.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for AUN (peer table management, AUN-port reporting, the cable-plug
    simulation that drives DCD) lives here.
    """

    @_abc_1.abstractmethod
    def SetConnected(
        self,
        request: _aun_pb2.AunSetConnectedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunSetConnectedResponse, _abc.Awaitable[_aun_pb2.AunSetConnectedResponse]]:
        """Connect or disconnect the simulated network cable. While
        disconnected the ADLC sees DCD high (no carrier). Always succeeds;
        when the socket is not up yet the state is remembered and applied when
        it comes up, and the response's error field says so.
        """

    @_abc_1.abstractmethod
    def AddPeer(
        self,
        request: _aun_pb2.AunAddPeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunAddPeerResponse, _abc.Awaitable[_aun_pb2.AunAddPeerResponse]]:
        """Add or replace this client's (Api) entry mapping an Econet address to a
        UDP endpoint. It takes precedence over every other source for that
        (net, stn) (see AunPeerSource).
        """

    @_abc_1.abstractmethod
    def RemovePeer(
        self,
        request: _aun_pb2.AunRemovePeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunRemovePeerResponse, _abc.Awaitable[_aun_pb2.AunRemovePeerResponse]]:
        """Remove the Api entry AddPeer made for an Econet address. Entries from
        other sources are untouched, so a station also named by the launch
        config, the map file or mDNS falls back to that entry rather than
        disappearing. Always succeeds, including when there was no Api entry.
        """

    @_abc_1.abstractmethod
    def ListPeers(
        self,
        request: _aun_pb2.AunListPeersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunListPeersResponse, _abc.Awaitable[_aun_pb2.AunListPeersResponse]]:
        """Enumerate the resolved routing table: one entry per (net, stn), from
        whichever source won it (see AunPeer.source).
        """

    @_abc_1.abstractmethod
    def GetStatus(
        self,
        request: _aun_pb2.AunGetStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunGetStatusResponse, _abc.Awaitable[_aun_pb2.AunGetStatusResponse]]:
        """Read the AUN transport status (link state, port, peer count, map file,
        discovery mode).
        """

    @_abc_1.abstractmethod
    def ReloadMap(
        self,
        request: _aun_pb2.AunReloadMapRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunReloadMapResponse, _abc.Awaitable[_aun_pb2.AunReloadMapResponse]]:
        """Re-read the per-user aun-map.json now, replacing the map file's peers,
        its subnet rules and the Subnet peers materialised from subnet rules
        (Api, Launch and Discovered peers, and --aun subnet= rules, are
        untouched). A modification is picked up automatically by the mtime poll
        on the discovery sweep, which runs while discovery browses
        (discovery=on or browse); this forces it. Under discovery=announce or
        off there is no poll, so another instance's edit arrives only with a
        ReloadMap or this instance's own next map edit.
        """

    @_abc_1.abstractmethod
    def AddMapPeer(
        self,
        request: _aun_pb2.AunAddMapPeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunAddMapPeerResponse, _abc.Awaitable[_aun_pb2.AunAddMapPeerResponse]]:
        """Edit the per-user aun-map.json. The server owns the file (it may be on
        another host): it writes its own file atomically, preserving entry order
        and unknown keys, then applies the change to its own peer set at once;
        other instances pick it up from their poll (see ReloadMap). Add is
        add-or-replace, keyed by (net, stn) for a peer and by net for a subnet
        rule. Every edit fails with "the map file is disabled (map-file=none)"
        when it is.
        """

    @_abc_1.abstractmethod
    def RemoveMapPeer(
        self,
        request: _aun_pb2.AunRemoveMapPeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunRemoveMapPeerResponse, _abc.Awaitable[_aun_pb2.AunRemoveMapPeerResponse]]: ...

    @_abc_1.abstractmethod
    def AddMapSubnet(
        self,
        request: _aun_pb2.AunAddMapSubnetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunAddMapSubnetResponse, _abc.Awaitable[_aun_pb2.AunAddMapSubnetResponse]]: ...

    @_abc_1.abstractmethod
    def RemoveMapSubnet(
        self,
        request: _aun_pb2.AunRemoveMapSubnetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunRemoveMapSubnetResponse, _abc.Awaitable[_aun_pb2.AunRemoveMapSubnetResponse]]: ...

    @_abc_1.abstractmethod
    def ListMap(
        self,
        request: _aun_pb2.AunListMapRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunListMapResponse, _abc.Awaitable[_aun_pb2.AunListMapResponse]]:
        """List the map file's entries (with labels and host-resolution state),
        distinct from ListPeers which lists the live resolved routing table.
        Empty, with no error, when the map file is disabled.
        """

def add_AunServiceServicer_to_server(servicer: AunServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...