# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
import abc as _abc_1
from . import aun_pb2 as _aun_pb2
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class AunServiceStub:
    """AUN-specific service. Lives alongside the AunEconetTransportExtension
    in src/extensions/aun/ and is served via that extension's AunDispatcher
    over the core's ExtensionRpc channel (no gRPC stub is compiled from this
    service block). It is reachable only when AUN is the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for AUN (peer table management, AUN-port reporting, the cable-plug
    simulation that drives DCD) lives here.
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> AunServiceAsyncStub: ...
    SetConnected: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunSetConnectedRequest, _aun_pb2.AunSetConnectedResponse]
    """Connect or disconnect the simulated network cable. While
    disconnected the ADLC sees DCD high (no carrier).
    """
    AddPeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunAddPeerRequest, _aun_pb2.AunAddPeerResponse]
    """Add an Econet address <-> UDP endpoint peer mapping."""
    RemovePeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunRemovePeerRequest, _aun_pb2.AunRemovePeerResponse]
    """Remove a peer mapping by Econet address."""
    ListPeers: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunListPeersRequest, _aun_pb2.AunListPeersResponse]
    """Enumerate all configured peers."""
    GetStatus: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunGetStatusRequest, _aun_pb2.AunGetStatusResponse]
    """Read the current AUN backend status (port, peer count, link state)."""
    ReloadMap: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunReloadMapRequest, _aun_pb2.AunReloadMapResponse]
    """Re-read the per-user aun-map.json now, replacing the MapFile and Subnet
    state (Api, Launch and Discovered are untouched). Normally a modification
    is picked up automatically on the poll; this forces it.
    """
    AddMapPeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapPeerRequest, _aun_pb2.AunAddMapPeerResponse]
    """Edit the per-user aun-map.json. The server owns the file (it may be on
    another host): it writes its own file atomically, preserving entry order
    and unknown keys, then applies the change to its own peer set at once;
    other instances pick it up from their poll. Add is add-or-replace.
    """
    RemoveMapPeer: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapPeerRequest, _aun_pb2.AunRemoveMapPeerResponse]
    AddMapSubnet: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapSubnetRequest, _aun_pb2.AunAddMapSubnetResponse]
    RemoveMapSubnet: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapSubnetRequest, _aun_pb2.AunRemoveMapSubnetResponse]
    ListMap: _grpc.UnaryUnaryMultiCallable[_aun_pb2.AunListMapRequest, _aun_pb2.AunListMapResponse]
    """List the map file's entries (with labels and host-resolution state),
    distinct from ListPeers which lists the live resolved routing table.
    """

@_typing.type_check_only
class AunServiceAsyncStub(AunServiceStub):
    """AUN-specific service. Lives alongside the AunEconetTransportExtension
    in src/extensions/aun/ and is served via that extension's AunDispatcher
    over the core's ExtensionRpc channel (no gRPC stub is compiled from this
    service block). It is reachable only when AUN is the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for AUN (peer table management, AUN-port reporting, the cable-plug
    simulation that drives DCD) lives here.
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    SetConnected: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunSetConnectedRequest, _aun_pb2.AunSetConnectedResponse]  # type: ignore[assignment]
    """Connect or disconnect the simulated network cable. While
    disconnected the ADLC sees DCD high (no carrier).
    """
    AddPeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunAddPeerRequest, _aun_pb2.AunAddPeerResponse]  # type: ignore[assignment]
    """Add an Econet address <-> UDP endpoint peer mapping."""
    RemovePeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunRemovePeerRequest, _aun_pb2.AunRemovePeerResponse]  # type: ignore[assignment]
    """Remove a peer mapping by Econet address."""
    ListPeers: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunListPeersRequest, _aun_pb2.AunListPeersResponse]  # type: ignore[assignment]
    """Enumerate all configured peers."""
    GetStatus: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunGetStatusRequest, _aun_pb2.AunGetStatusResponse]  # type: ignore[assignment]
    """Read the current AUN backend status (port, peer count, link state)."""
    ReloadMap: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunReloadMapRequest, _aun_pb2.AunReloadMapResponse]  # type: ignore[assignment]
    """Re-read the per-user aun-map.json now, replacing the MapFile and Subnet
    state (Api, Launch and Discovered are untouched). Normally a modification
    is picked up automatically on the poll; this forces it.
    """
    AddMapPeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapPeerRequest, _aun_pb2.AunAddMapPeerResponse]  # type: ignore[assignment]
    """Edit the per-user aun-map.json. The server owns the file (it may be on
    another host): it writes its own file atomically, preserving entry order
    and unknown keys, then applies the change to its own peer set at once;
    other instances pick it up from their poll. Add is add-or-replace.
    """
    RemoveMapPeer: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapPeerRequest, _aun_pb2.AunRemoveMapPeerResponse]  # type: ignore[assignment]
    AddMapSubnet: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunAddMapSubnetRequest, _aun_pb2.AunAddMapSubnetResponse]  # type: ignore[assignment]
    RemoveMapSubnet: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunRemoveMapSubnetRequest, _aun_pb2.AunRemoveMapSubnetResponse]  # type: ignore[assignment]
    ListMap: _aio.UnaryUnaryMultiCallable[_aun_pb2.AunListMapRequest, _aun_pb2.AunListMapResponse]  # type: ignore[assignment]
    """List the map file's entries (with labels and host-resolution state),
    distinct from ListPeers which lists the live resolved routing table.
    """

class AunServiceServicer(metaclass=_abc_1.ABCMeta):
    """AUN-specific service. Lives alongside the AunEconetTransportExtension
    in src/extensions/aun/ and is served via that extension's AunDispatcher
    over the core's ExtensionRpc channel (no gRPC stub is compiled from this
    service block). It is reachable only when AUN is the active transport.

    EconetService remains the place for transport-agnostic Econet RPCs
    (status, station ID, enable/disable). Anything that only makes sense
    for AUN (peer table management, AUN-port reporting, the cable-plug
    simulation that drives DCD) lives here.
    """

    @_abc_1.abstractmethod
    def SetConnected(
        self,
        request: _aun_pb2.AunSetConnectedRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunSetConnectedResponse, _abc.Awaitable[_aun_pb2.AunSetConnectedResponse]]:
        """Connect or disconnect the simulated network cable. While
        disconnected the ADLC sees DCD high (no carrier).
        """

    @_abc_1.abstractmethod
    def AddPeer(
        self,
        request: _aun_pb2.AunAddPeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunAddPeerResponse, _abc.Awaitable[_aun_pb2.AunAddPeerResponse]]:
        """Add an Econet address <-> UDP endpoint peer mapping."""

    @_abc_1.abstractmethod
    def RemovePeer(
        self,
        request: _aun_pb2.AunRemovePeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunRemovePeerResponse, _abc.Awaitable[_aun_pb2.AunRemovePeerResponse]]:
        """Remove a peer mapping by Econet address."""

    @_abc_1.abstractmethod
    def ListPeers(
        self,
        request: _aun_pb2.AunListPeersRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunListPeersResponse, _abc.Awaitable[_aun_pb2.AunListPeersResponse]]:
        """Enumerate all configured peers."""

    @_abc_1.abstractmethod
    def GetStatus(
        self,
        request: _aun_pb2.AunGetStatusRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunGetStatusResponse, _abc.Awaitable[_aun_pb2.AunGetStatusResponse]]:
        """Read the current AUN backend status (port, peer count, link state)."""

    @_abc_1.abstractmethod
    def ReloadMap(
        self,
        request: _aun_pb2.AunReloadMapRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunReloadMapResponse, _abc.Awaitable[_aun_pb2.AunReloadMapResponse]]:
        """Re-read the per-user aun-map.json now, replacing the MapFile and Subnet
        state (Api, Launch and Discovered are untouched). Normally a modification
        is picked up automatically on the poll; this forces it.
        """

    @_abc_1.abstractmethod
    def AddMapPeer(
        self,
        request: _aun_pb2.AunAddMapPeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunAddMapPeerResponse, _abc.Awaitable[_aun_pb2.AunAddMapPeerResponse]]:
        """Edit the per-user aun-map.json. The server owns the file (it may be on
        another host): it writes its own file atomically, preserving entry order
        and unknown keys, then applies the change to its own peer set at once;
        other instances pick it up from their poll. Add is add-or-replace.
        """

    @_abc_1.abstractmethod
    def RemoveMapPeer(
        self,
        request: _aun_pb2.AunRemoveMapPeerRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunRemoveMapPeerResponse, _abc.Awaitable[_aun_pb2.AunRemoveMapPeerResponse]]: ...

    @_abc_1.abstractmethod
    def AddMapSubnet(
        self,
        request: _aun_pb2.AunAddMapSubnetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunAddMapSubnetResponse, _abc.Awaitable[_aun_pb2.AunAddMapSubnetResponse]]: ...

    @_abc_1.abstractmethod
    def RemoveMapSubnet(
        self,
        request: _aun_pb2.AunRemoveMapSubnetRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunRemoveMapSubnetResponse, _abc.Awaitable[_aun_pb2.AunRemoveMapSubnetResponse]]: ...

    @_abc_1.abstractmethod
    def ListMap(
        self,
        request: _aun_pb2.AunListMapRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_aun_pb2.AunListMapResponse, _abc.Awaitable[_aun_pb2.AunListMapResponse]]:
        """List the map file's entries (with labels and host-resolution state),
        distinct from ListPeers which lists the live resolved routing table.
        """

def add_AunServiceServicer_to_server(servicer: AunServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...