# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _AunPeerSource:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AunPeerSourceEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AunPeerSource.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUN_PEER_SOURCE_UNSPECIFIED: _AunPeerSource.ValueType  # 0
    """Default for uninitialised messages; no source should emit it."""
    AUN_PEER_SOURCE_LAUNCH: _AunPeerSource.ValueType  # 1
    """Added via --aun map= or the preset's econet.transport.parameters
    for this launch.
    """
    AUN_PEER_SOURCE_API: _AunPeerSource.ValueType  # 2
    """Added at runtime via AunService::AddPeer."""
    AUN_PEER_SOURCE_MAP_FILE: _AunPeerSource.ValueType  # 3
    """Read from the map file (the per-user aun-map.json, or the file named
    by --aun map-file=): its peers[] entries whose host resolved.
    """
    AUN_PEER_SOURCE_DISCOVERED: _AunPeerSource.ValueType  # 4
    """Added by the AUN extension's mDNS subscriber from a
    _aun._udp announcement on the LAN.
    """
    AUN_PEER_SOURCE_SUBNET: _AunPeerSource.ValueType  # 5
    """Materialised from a subnet rule (the map file's subnets[] or
    --aun subnet=): an inbound sender identified by its address, or an
    outbound guess. Lowest precedence; every other source wins.
    """

class AunPeerSource(_AunPeerSource, metaclass=_AunPeerSourceEnumTypeWrapper):
    """Where a peer entry came from, mirroring the AunPeerProvenance the AUN
    transport resolves by. Each (net, stn) resolves to one winner by
    precedence, highest first: Api > Launch > MapFile > Discovered > Subnet.
    The three operator sources (Api, Launch, MapFile) all beat Discovered, so a
    discovered announcement that claims a (net, stn) an operator source already
    holds is shadowed rather than displacing it. Removing the winner falls back
    to the next source still present. Named AunPeerSource
    so the proto-generated C++ symbol does not collide with the transport's
    beebium::AunPeerProvenance enum class.
    """

AUN_PEER_SOURCE_UNSPECIFIED: AunPeerSource.ValueType  # 0
"""Default for uninitialised messages; no source should emit it."""
AUN_PEER_SOURCE_LAUNCH: AunPeerSource.ValueType  # 1
"""Added via --aun map= or the preset's econet.transport.parameters
for this launch.
"""
AUN_PEER_SOURCE_API: AunPeerSource.ValueType  # 2
"""Added at runtime via AunService::AddPeer."""
AUN_PEER_SOURCE_MAP_FILE: AunPeerSource.ValueType  # 3
"""Read from the map file (the per-user aun-map.json, or the file named
by --aun map-file=): its peers[] entries whose host resolved.
"""
AUN_PEER_SOURCE_DISCOVERED: AunPeerSource.ValueType  # 4
"""Added by the AUN extension's mDNS subscriber from a
_aun._udp announcement on the LAN.
"""
AUN_PEER_SOURCE_SUBNET: AunPeerSource.ValueType  # 5
"""Materialised from a subnet rule (the map file's subnets[] or
--aun subnet=): an inbound sender identified by its address, or an
outbound guess. Lowest precedence; every other source wins.
"""
Global___AunPeerSource: _TypeAlias = AunPeerSource  # noqa: Y015

@_typing.final
class AunGetStatusRequest(_message.Message):
    """--- Status ---

    Empty.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunGetStatusRequest: _TypeAlias = AunGetStatusRequest  # noqa: Y015

@_typing.final
class AunGetStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONNECTED_FIELD_NUMBER: _builtins.int
    LOCAL_PORT_FIELD_NUMBER: _builtins.int
    PEER_COUNT_FIELD_NUMBER: _builtins.int
    MAP_FILE_PATH_FIELD_NUMBER: _builtins.int
    MAP_FILE_ENTRY_COUNT_FIELD_NUMBER: _builtins.int
    MAP_FILE_ERROR_FIELD_NUMBER: _builtins.int
    DISCOVERY_MODE_FIELD_NUMBER: _builtins.int
    connected: _builtins.bool
    """True if the AUN UDP socket is bound and the cable is connected; false
    while there is no socket.
    """
    local_port: _builtins.int
    """The local UDP port the AUN backend is bound to (0 if none)."""
    peer_count: _builtins.int
    """Number of (net, stn) pairs in the resolved routing table (what ListPeers
    returns). Reported even before the socket is up.
    """
    map_file_path: _builtins.str
    """The map file's path on the server's host: --aun map-file=, else
    BEEBIUM_AUN_MAP_FILEPATH, else the per-user aun-map.json. Empty when
    the map file is disabled with map-file=none.
    """
    map_file_entry_count: _builtins.int
    """Number of entries (peers + subnets) read from the map file on the last
    load, including peers whose host did not resolve.
    """
    map_file_error: _builtins.str
    """The last map-file load error, or empty when the last load succeeded (or
    the file is absent, which is not an error).
    """
    discovery_mode: _builtins.str
    """The mDNS discovery mode set by --aun discovery=: "on", "announce",
    "browse" or "off". A frontend shows it when it is not "on". (aun.proto
    is served over ExtensionRpc and is NOT part of the fingerprinted service
    protocol.)
    """
    def __init__(
        self,
        *,
        connected: _builtins.bool = ...,
        local_port: _builtins.int = ...,
        peer_count: _builtins.int = ...,
        map_file_path: _builtins.str = ...,
        map_file_entry_count: _builtins.int = ...,
        map_file_error: _builtins.str = ...,
        discovery_mode: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connected", b"connected", "discovery_mode", b"discovery_mode", "local_port", b"local_port", "map_file_entry_count", b"map_file_entry_count", "map_file_error", b"map_file_error", "map_file_path", b"map_file_path", "peer_count", b"peer_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunGetStatusResponse: _TypeAlias = AunGetStatusResponse  # noqa: Y015

@_typing.final
class AunReloadMapRequest(_message.Message):
    """--- Map file reload ---

    Empty.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunReloadMapRequest: _TypeAlias = AunReloadMapRequest  # noqa: Y015

@_typing.final
class AunReloadMapResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELOADED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    reloaded: _builtins.bool
    """True if the reload ran (even if the file was absent); false only when the
    map file is disabled (map-file=none).
    """
    error: _builtins.str
    """The load error, if the file was present but could not be parsed."""
    def __init__(
        self,
        *,
        reloaded: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "reloaded", b"reloaded"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunReloadMapResponse: _TypeAlias = AunReloadMapResponse  # noqa: Y015

@_typing.final
class AunAddMapPeerRequest(_message.Message):
    """--- Map file editing ---"""

    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    STN_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    """0..255"""
    stn: _builtins.int
    """1..254"""
    host: _builtins.str
    """IPv4 literal or DNS name, resolved on the server's"""
    port: _builtins.int
    """host at each load
    1..65535
    """
    label: _builtins.str
    """optional note"""
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        stn: _builtins.int = ...,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        label: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["host", b"host", "label", b"label", "net", b"net", "port", b"port", "stn", b"stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunAddMapPeerRequest: _TypeAlias = AunAddMapPeerRequest  # noqa: Y015

@_typing.final
class AunAddMapPeerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunAddMapPeerResponse: _TypeAlias = AunAddMapPeerResponse  # noqa: Y015

@_typing.final
class AunRemoveMapPeerRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    STN_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    stn: _builtins.int
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        stn: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net", b"net", "stn", b"stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunRemoveMapPeerRequest: _TypeAlias = AunRemoveMapPeerRequest  # noqa: Y015

@_typing.final
class AunRemoveMapPeerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    removed: _builtins.bool
    """false if there was no such entry"""
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        removed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "removed", b"removed", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunRemoveMapPeerResponse: _TypeAlias = AunRemoveMapPeerResponse  # noqa: Y015

@_typing.final
class AunAddMapSubnetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    SUBNET_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    """0..255"""
    subnet: _builtins.str
    """a.b.c.0/24: station = last octet, port 32768"""
    label: _builtins.str
    """optional note"""
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        subnet: _builtins.str = ...,
        label: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "net", b"net", "subnet", b"subnet"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunAddMapSubnetRequest: _TypeAlias = AunAddMapSubnetRequest  # noqa: Y015

@_typing.final
class AunAddMapSubnetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunAddMapSubnetResponse: _TypeAlias = AunAddMapSubnetResponse  # noqa: Y015

@_typing.final
class AunRemoveMapSubnetRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net", b"net"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunRemoveMapSubnetRequest: _TypeAlias = AunRemoveMapSubnetRequest  # noqa: Y015

@_typing.final
class AunRemoveMapSubnetResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    removed: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        removed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "removed", b"removed", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunRemoveMapSubnetResponse: _TypeAlias = AunRemoveMapSubnetResponse  # noqa: Y015

@_typing.final
class AunListMapRequest(_message.Message):
    """Empty."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunListMapRequest: _TypeAlias = AunListMapRequest  # noqa: Y015

@_typing.final
class AunMapPeerEntry(_message.Message):
    """One peers[] entry as written in the file, with its host-resolution state."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    STN_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    RESOLVED_FIELD_NUMBER: _builtins.int
    RESOLVED_IP_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    stn: _builtins.int
    host: _builtins.str
    """as written (IPv4 literal or DNS name)"""
    port: _builtins.int
    label: _builtins.str
    resolved: _builtins.bool
    """false if the host did not resolve"""
    resolved_ip: _builtins.str
    """dotted-quad when resolved, else empty"""
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        stn: _builtins.int = ...,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        label: _builtins.str = ...,
        resolved: _builtins.bool = ...,
        resolved_ip: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["host", b"host", "label", b"label", "net", b"net", "port", b"port", "resolved", b"resolved", "resolved_ip", b"resolved_ip", "stn", b"stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunMapPeerEntry: _TypeAlias = AunMapPeerEntry  # noqa: Y015

@_typing.final
class AunMapSubnetEntry(_message.Message):
    """One subnets[] entry as written in the file."""

    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    SUBNET_FIELD_NUMBER: _builtins.int
    LABEL_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    subnet: _builtins.str
    label: _builtins.str
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        subnet: _builtins.str = ...,
        label: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["label", b"label", "net", b"net", "subnet", b"subnet"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunMapSubnetEntry: _TypeAlias = AunMapSubnetEntry  # noqa: Y015

@_typing.final
class AunListMapResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PEERS_FIELD_NUMBER: _builtins.int
    SUBNETS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    error: _builtins.str
    """A load error, if the file was present but malformed; the lists are then
    empty.
    """
    @_builtins.property
    def peers(self) -> _containers.RepeatedCompositeFieldContainer[Global___AunMapPeerEntry]: ...
    @_builtins.property
    def subnets(self) -> _containers.RepeatedCompositeFieldContainer[Global___AunMapSubnetEntry]: ...
    def __init__(
        self,
        *,
        peers: _abc.Iterable[Global___AunMapPeerEntry] | None = ...,
        subnets: _abc.Iterable[Global___AunMapSubnetEntry] | None = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "peers", b"peers", "subnets", b"subnets"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunListMapResponse: _TypeAlias = AunListMapResponse  # noqa: Y015

@_typing.final
class AunSetConnectedRequest(_message.Message):
    """--- Cable plug ---"""

    DESCRIPTOR: _descriptor.Descriptor

    CONNECTED_FIELD_NUMBER: _builtins.int
    connected: _builtins.bool
    """True to plug in the cable, false to unplug it."""
    def __init__(
        self,
        *,
        connected: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connected", b"connected"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunSetConnectedRequest: _TypeAlias = AunSetConnectedRequest  # noqa: Y015

@_typing.final
class AunSetConnectedResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunSetConnectedResponse: _TypeAlias = AunSetConnectedResponse  # noqa: Y015

@_typing.final
class AunAddPeerRequest(_message.Message):
    """--- Peer table ---"""

    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    STN_FIELD_NUMBER: _builtins.int
    IP_ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    """Econet network number (0-255, the full Econet net byte)."""
    stn: _builtins.int
    """Econet station number (1-254)."""
    ip_address: _builtins.str
    """Dotted-quad IPv4 address (e.g. "192.168.1.100"); a DNS name is
    rejected (use AddMapPeer for a name).
    """
    port: _builtins.int
    """UDP port (0 = use AUN default 32768)."""
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        stn: _builtins.int = ...,
        ip_address: _builtins.str = ...,
        port: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ip_address", b"ip_address", "net", b"net", "port", b"port", "stn", b"stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunAddPeerRequest: _TypeAlias = AunAddPeerRequest  # noqa: Y015

@_typing.final
class AunAddPeerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunAddPeerResponse: _TypeAlias = AunAddPeerResponse  # noqa: Y015

@_typing.final
class AunRemovePeerRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    STN_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    stn: _builtins.int
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        stn: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["net", b"net", "stn", b"stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunRemovePeerRequest: _TypeAlias = AunRemovePeerRequest  # noqa: Y015

@_typing.final
class AunRemovePeerResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    error: _builtins.str
    removed: _builtins.bool
    """false if there was no such entry"""
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        removed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "removed", b"removed", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunRemovePeerResponse: _TypeAlias = AunRemovePeerResponse  # noqa: Y015

@_typing.final
class AunListPeersRequest(_message.Message):
    """Empty."""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunListPeersRequest: _TypeAlias = AunListPeersRequest  # noqa: Y015

@_typing.final
class AunListPeersResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PEERS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def peers(self) -> _containers.RepeatedCompositeFieldContainer[Global___AunPeer]: ...
    def __init__(
        self,
        *,
        peers: _abc.Iterable[Global___AunPeer] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["peers", b"peers"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunListPeersResponse: _TypeAlias = AunListPeersResponse  # noqa: Y015

@_typing.final
class AunPeer(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NET_FIELD_NUMBER: _builtins.int
    STN_FIELD_NUMBER: _builtins.int
    IP_ADDRESS_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    net: _builtins.int
    stn: _builtins.int
    ip_address: _builtins.str
    port: _builtins.int
    source: Global___AunPeerSource.ValueType
    """Provenance of this resolved entry (the source it won from). The AUN
    panel captions it "launch", "API", "map file", "mDNS" or "subnet".
    """
    def __init__(
        self,
        *,
        net: _builtins.int = ...,
        stn: _builtins.int = ...,
        ip_address: _builtins.str = ...,
        port: _builtins.int = ...,
        source: Global___AunPeerSource.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ip_address", b"ip_address", "net", b"net", "port", b"port", "source", b"source", "stn", b"stn"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AunPeer: _TypeAlias = AunPeer  # noqa: Y015