// Copyright © 2026 Robert Smallshire <robert@smallshire.org.uk>
//
// This file is part of Beebium.
//
// Beebium is free software: you can redistribute it and/or modify it under the terms of the
// GNU General Public License as published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version. Beebium is distributed in the hope that it will
// be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
// You should have received a copy of the GNU General Public License along with Beebium.
// If not, see <https://www.gnu.org/licenses/>.

#ifndef SCREENTEXT_BUILTINGLYPHSETS_HPP
#define SCREENTEXT_BUILTINGLYPHSETS_HPP

#include "screentext/Glyph.hpp"

namespace screentext::builtin {

// Each built-in set is produced by a generated function, so the glyph data is
// committed source rather than something read at runtime. Generated by
// tools/generate_acorn_glyphs.py; see the header of the generated file for
// the ROM it came from.
GlyphSet make_acorn_mos_1_20();

} // namespace screentext::builtin

#endif // SCREENTEXT_BUILTINGLYPHSETS_HPP
