# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""Generate a package's README.md from readme/README.md.j2 and tested snippets.

    generate_readme.py <project-dir> [--check]

One generator serves every package whose README is generated (the `beebium`
client and the `beebium-server` wheel today): each passes its own project
directory, which must contain ``readme/README.md.j2`` and ``readme/snippets/``,
and whose ``README.md`` is (re)written. Hosting it at the repo root rather than
inside one package keeps a shared tool from coupling to either package.

The README is generated, never hand-edited, so its code examples cannot drift
from working code: every Usage example lives in readme/snippets/ as a real
pytest test that runs against the built wheel, and this script splices the
tested code into the prose.

Snippet extraction rule (deliberately simple, so what renders is exactly what
runs): a snippet is the block of lines strictly between the first
``# readme:begin`` and the next ``# readme:end`` marker in
readme/snippets/test_readme_<name>.py, with common leading indentation removed.
The two marker lines are dropped; nothing else is added, removed or reformatted.
Keep any assertions or fixtures a snippet should not show OUTSIDE the marked
region.

Output is deterministic (no timestamps), so the committed README.md is a pure
function of the template and the snippets; scripts/check_readme_regen.sh fails
CI if a committed file drifts from a fresh render.

This script is a development/CI tool: run it with jinja2 available (e.g. under
the client project's uv dev group). It never runs at package install time.
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

BEGIN_MARKER = "# readme:begin"
END_MARKER = "# readme:end"
TEMPLATE_FILENAME = "README.md.j2"

HEADER = (
    "<!-- Generated by scripts/generate_readme.py from readme/README.md.j2 and\n"
    "     the tested snippets in readme/snippets/. Do not edit this file directly:\n"
    "     edit the template or a snippet and run scripts/generate_readme.py.\n"
    "     See CONTRIBUTING.md. -->\n"
)


def extract_snippet(snippets_dirpath: Path, name: str) -> str:
    """Return the marked, dedented code region from test_readme_<name>.py.

    Snippet files carry a ``test_readme_`` prefix (not a bare ``test_``) so their
    basenames never collide with a package's tests/ when pytest collects both.
    """
    snippet_filepath = snippets_dirpath / f"test_readme_{name}.py"
    if not snippet_filepath.exists():
        raise FileNotFoundError(f"no snippet file for {name!r}: {snippet_filepath}")

    lines = snippet_filepath.read_text().splitlines()
    begin = end = None
    for index, line in enumerate(lines):
        if line.strip() == BEGIN_MARKER and begin is None:
            begin = index
        elif line.strip() == END_MARKER and begin is not None:
            end = index
            break
    if begin is None or end is None:
        raise ValueError(
            f"{snippet_filepath} must contain a {BEGIN_MARKER} ... {END_MARKER} region"
        )

    region = "\n".join(lines[begin + 1 : end])
    return textwrap.dedent(region).strip("\n")


def render(project_dirpath: Path) -> str:
    readme_dirpath = project_dirpath / "readme"
    snippets_dirpath = readme_dirpath / "snippets"
    if not (readme_dirpath / TEMPLATE_FILENAME).exists():
        raise FileNotFoundError(f"no {TEMPLATE_FILENAME} under {readme_dirpath}")

    environment = Environment(
        loader=FileSystemLoader(str(readme_dirpath)),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        autoescape=False,
        trim_blocks=False,
        lstrip_blocks=False,
    )
    environment.globals["snippet"] = lambda name: extract_snippet(snippets_dirpath, name)
    template = environment.get_template(TEMPLATE_FILENAME)
    body = template.render()
    if not body.endswith("\n"):
        body += "\n"
    return HEADER + body


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate a package README from its template and snippets.")
    parser.add_argument("project_dir", help="package directory holding readme/README.md.j2 and readme/snippets/")
    parser.add_argument("--check", action="store_true", help="fail if README.md is out of date instead of writing it")
    args = parser.parse_args(argv[1:])

    project_dirpath = Path(args.project_dir).resolve()
    output_filepath = project_dirpath / "README.md"
    rendered = render(project_dirpath)

    if args.check:
        current = output_filepath.read_text() if output_filepath.exists() else ""
        if current != rendered:
            print(f"{output_filepath} is out of date. Run scripts/generate_readme.py.", file=sys.stderr)
            return 1
        print(f"{output_filepath} is up to date.")
        return 0

    output_filepath.write_text(rendered)
    print(f"Wrote {output_filepath}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
