# Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
#
# This file is part of Beebium.
#
# Beebium is free software: you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version. Beebium is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with Beebium.
# If not, see <https://www.gnu.org/licenses/>.

"""Generate (or verify) the committed protocol-fingerprint constants.

Computes the single Beebium protocol fingerprint from the canonical core proto
set and writes it, identically, into the server (C++ header), the Python client,
the TypeScript client, and the macOS/Swift client. Run as part of proto
regeneration; the same value ends up in all four so the connect-time handshake
compares one constant built once -- never each language hashing its own
(differing) stub subset.

    python scripts/sync_protocol_fingerprint.py            # write the files
    python scripts/sync_protocol_fingerprint.py --check    # CI: fail on drift

The canonical set is the always-present contract: the core service protos plus
extension_ui. Per-extension protos are intentionally excluded (their
compatibility, if needed, is a separate per-extension concern).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from protocol_fingerprint import compute_fingerprint  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent

SERVICE_PROTO_DIR = REPO_ROOT / "src/service/proto"
EXT_UI_PROTO_DIR = REPO_ROOT / "src/core/extension-api/proto"

INCLUDES = [str(SERVICE_PROTO_DIR), str(EXT_UI_PROTO_DIR)]


def canonical_protos() -> list[str]:
    protos = sorted(str(p) for p in SERVICE_PROTO_DIR.glob("*.proto"))
    protos.append(str(EXT_UI_PROTO_DIR / "extension_ui.proto"))
    return protos


_GPL = """\
{c} Copyright 2026 Robert Smallshire <robert@smallshire.org.uk>
{c}
{c} This file is part of Beebium.
{c}
{c} Beebium is free software: you can redistribute it and/or modify it under the terms of the
{c} GNU General Public License as published by the Free Software Foundation, either version 3 of the
{c} License, or (at your option) any later version. Beebium is distributed in the hope that it will
{c} be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
{c} FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
{c} You should have received a copy of the GNU General Public License along with Beebium.
{c} If not, see <https://www.gnu.org/licenses/>.
"""

_GENERATED = "Generated by scripts/sync_protocol_fingerprint.py. DO NOT EDIT."


def render_cpp(fp: str) -> str:
    return (
        _GPL.format(c="//")
        + f"""
// {_GENERATED}
#ifndef BEEBIUM_SERVICE_PROTOCOL_FINGERPRINT_HPP
#define BEEBIUM_SERVICE_PROTOCOL_FINGERPRINT_HPP

#include <string_view>

namespace beebium::service {{

inline constexpr std::string_view PROTOCOL_FINGERPRINT = "{fp}";

}}  // namespace beebium::service

#endif  // BEEBIUM_SERVICE_PROTOCOL_FINGERPRINT_HPP
"""
    )


def render_python(fp: str) -> str:
    return (
        _GPL.format(c="#")
        + f'''
"""{_GENERATED}"""

PROTOCOL_FINGERPRINT = "{fp}"
'''
    )


def render_typescript(fp: str) -> str:
    return f"""\
/**
 * {_GENERATED}
 */
export const PROTOCOL_FINGERPRINT = "{fp}";
"""


def render_swift(fp: str) -> str:
    return (
        _GPL.format(c="//")
        + f"""
// {_GENERATED}

enum ProtocolFingerprint {{
    static let value = "{fp}"
}}
"""
    )


_TARGETS = [
    ("src/service/include/beebium/service/ProtocolFingerprint.hpp", render_cpp),
    ("clients/beebium-python-client/src/beebium/client/_proto/protocol_fingerprint.py", render_python),
    ("clients/beebium-typescript-client/src/protocol_fingerprint.ts", render_typescript),
    ("clients/macos/Beebium/Beebium/ProtocolFingerprint.swift", render_swift),
]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the committed files match the current fingerprint (CI); do not write",
    )
    args = parser.parse_args()

    fingerprint = compute_fingerprint(canonical_protos(), INCLUDES)

    if args.check:
        drift = []
        for rel, render in _TARGETS:
            path = REPO_ROOT / rel
            expected = render(fingerprint)
            if not path.exists() or path.read_text() != expected:
                drift.append(rel)
        if drift:
            print(f"Protocol fingerprint is {fingerprint}", file=sys.stderr)
            print("These committed files are out of date:", file=sys.stderr)
            for rel in drift:
                print(f"  {rel}", file=sys.stderr)
            print(
                "Run: python scripts/sync_protocol_fingerprint.py "
                "(after regenerating the proto stubs), then commit.",
                file=sys.stderr,
            )
            return 1
        print(f"Protocol fingerprint up to date: {fingerprint}")
        return 0

    for rel, render in _TARGETS:
        (REPO_ROOT / rel).write_text(render(fingerprint))
    print(f"Wrote protocol fingerprint {fingerprint} to {len(_TARGETS)} files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
